### PR TITLE
[Bugfix:InstructorUI] Intercept absolute paths

### LINKED ISSUE #11476: course material edits with absolute path (beginning with '/') fail and cause frog robot
To Reproduce:

1. Upload a file to course materials, e.g., x.pdf
2. Click the pencil next to the course material file to edit the course material.
3. We can successfully edit the filename and/or the directory of the file, as long as we use a relative path.  E.g., we can change the file name to "foo/y.pdf" and it adds a subdirectory named foo and changes the name of the file.
4. We CANNOT start with the root directory, we cannot successfully edit it to "/bar/z.pdf".  
5. This causes a popup error at the attempt to edit, and all future attempts to even view the course materials page are broken.

Here is the frog robot:

```
Oh no! Something irrecoverable has happened...

TypeError (Code: 0) thrown in /usr/local/submitty/site/app/views/course/CourseMaterialsView.php (Line 133) by:
            $path_to_place = array_slice($path_to_place, 0, $index, true) +


Message:
array_slice(): Argument #1 ($array) must be of type array, null given

Stack Trace:
#0 /usr/local/submitty/site/app/views/course/CourseMaterialsView.php(133): array_slice()
#1 unknown file(unknown line): app\views\course\CourseMaterialsView->listCourseMaterials()
#2 /usr/local/submitty/site/app/libraries/Output.php(251): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/Output.php(220): app\libraries\Output->renderTemplate()
#4 /usr/local/submitty/site/app/libraries/response/WebResponse.php(43): app\libraries\Output->renderOutput()
#5 /usr/local/submitty/site/public/index.php(160): app\libraries\response\WebResponse->render()

USER: instructor
```

--------------------------------------------

**Describe the bug**
Unrecoverable crash of site after performing certain actions. 

Crashing Course Materials
- Upload the file to course materials.  
- Now edit the file, and edit the file link field to something like a folder path `/folder1/folder/`
- This triggers an error on the instructors side, permanently.  

<video src="https://github.com/user-attachments/assets/d3341392-e30b-4fda-826e-707dadf72571">
Seems to happen only to instructor and not student.

### PR DESCRIPTION
**Pull request by Troy-bailan-King**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Upload a file to course materials, e.g., x.pdf
Click the pencil next to the course material file to edit the course material.
We can successfully edit the filename and/or the directory of the file, as long as we use a relative path. E.g., we can change the file name to "foo/y.pdf" and it adds a subdirectory named foo and changes the name of the file.
We CANNOT start with the root directory, we cannot successfully edit it to "/bar/z.pdf".
This causes a popup error at the attempt to edit, and all future attempts to even view the course materials page are broken.
Here is the frog robot:

Oh no! Something irrecoverable has happened...

TypeError (Code: 0) thrown in /usr/local/submitty/site/app/views/course/CourseMaterialsView.php (Line 133) by:
            $path_to_place = array_slice($path_to_place, 0, $index, true) +

Message:
array_slice(): Argument #1 ($array) must be of type array, null given

Stack Trace:
#0 /usr/local/submitty/site/app/views/course/CourseMaterialsView.php(133): array_slice()
#1 unknown file(unknown line): app\views\course\CourseMaterialsView->listCourseMaterials()
#2 /usr/local/submitty/site/app/libraries/Output.php(251): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/Output.php(220): app\libraries\Output->renderTemplate()
#4 /usr/local/submitty/site/app/libraries/response/WebResponse.php(43): app\libraries\Output->renderOutput()
#5 /usr/local/submitty/site/public/index.php(160): app\libraries\response\WebResponse->render()

USER: instructor

https://github.com/user-attachments/assets/3c0ceb7b-a03c-42e3-b62f-dccdf055b309

### What is the new behavior?
image

### Other information?
closes #11476

### CODE REVIEW

File: site/app/controllers/course/CourseMaterialsController.php [hunk 1]
```diff
@@ -453,6 +453,9 @@ public function ajaxEditCourseMaterialsFiles(bool $flush = true): JsonResponse {
             $path = $course_material->getPath();
             $upload_path = FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), "uploads", "course_materials");
             $requested_path = $_POST['file_path'];
+            if (strpos($requested_path, '/') === 0) {
```
Comment (jeffrey-cordero) [inline site/app/controllers/course/CourseMaterialsController.php:456]: One potential edge case is if the provided path within the POST object contains whitespace at the start of the string, such as `' /path...'`, which won't throw the expected error.

**Review by jeffrey-cordero — CHANGES_REQUESTED** [review]
The proposed changes do prevent instructors from submitting an absolute path within the course materials page. I did note a potential edge case within the backend validation, which should be addressed.

File: site/app/controllers/course/CourseMaterialsController.php (hunk 1 above)
Comment (Troy-bailan-King) [reply site/app/controllers/course/CourseMaterialsController.php:456]: I test the edge case and It can throw the expected error. I think the input frame will delete whitespace at the start of string

**Review by jeffrey-cordero — APPROVED** [review]
The backend appears to handle absolute paths gracefully compared to errors thrown on the main branch after testing it again.

**Review by JManion32 — APPROVED** [review]
I replicated the issue on main and found that this PR resolves it. The new implementation of an alert is much better than getting the frog robot and not being able to access the course materials page.
