### PR TITLE
TA Grading Team Name Fix

### LINKED ISSUE #1594: TA grading index page for Teams
Change request:
Instead of listing the usernames of the team members, let's instead list the real names of the team members.  

Previous
Team_id      Team_Members
00001_smithj     smithj,jonesb

New
Team_id      Team_Members
00001_smithj     John Smith, Bob Jones

### PR DESCRIPTION
**Pull request by RylanOC**
closes #1594, where team names consisted of list of user IDs, not full names

### CODE REVIEW

File: site/app/views/grading/ElectronicGraderView.php [hunk 1]
```diff
@@ -593,10 +593,25 @@ public function detailsPage($gradeable, $rows, $graders, $empty_teams) {
...
-                        $return .= <<<HTML
+                    // Construct a string containing the names of all team members
+                     else {
+                        $member_list = "";
+                        foreach($row->getTeam()->getMembers() as $team_member) {
+                            if ($member_list !== "") {
+                                $member_list = $member_list . ", ";
+                            }
+ 	 
+                            $first_name = $this->core->getQueries()->getUserById($team_member)->getPreferredFirstName();
```
Comment (bmcutler) [inline site/app/views/grading/ElectronicGraderView.php]: use getDisplayedFirstName instead, then you don't need this logic

**Comment by saxocellphone** [comment]
Cactus boi!
