### PR TITLE
[Bugfix:TAGrading] peer grader pdf permissions fix [revision]

### LINKED ISSUE #5234: Peer graders cannot view upload.pdf
**Describe the bug**

When an assigned peer clicks on upload.pdf (a bulk pdf) or perhaps any pdf(?)
they get a permission error.

This happens either when viewing within the submission frame or when using the "popout" to a separate window.

**Other notes**

The peer grader is able to download the zip of the assignment and the upload.pdf file is included.

The peer grader is able to view the names of the files in the results folder, but gets a permission error on all of those files.  Did we make a decision about whether any of these files were important for grading.  I'm not sure.  I think perhaps we should just be hiding all files in the results folder and not including them in the downloaded zip.

### PR DESCRIPTION
**Pull request by jchulton**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
A peer grader cannot view a pdf submitted by a peer they are assigned to grade (get a permissions error)
### What is the new behavior?
The peer grader can view the pdf. Closes #5234 (This is an updated version of PR #5253)

### CODE REVIEW

File: site/app/controllers/pdf/PDFController.php [hunk 1]
```diff
@@ -141,11 +145,14 @@ public function showGraderPDFEmbedded($gradeable_id) {
         }
         
         $grader_id = $this->core->getUser()->getId();
-        
-        if ($gradeable->isPeerGrading() && $this->core->getQueries()->getUserById($grader_id)->getGroup() === User::GROUP_STUDENT) {
-            $user_ids = $this->core->getQueries()->getPeerAssignment($gradeable_id, $grader_id);
-        
-            if (!in_array($id, $user_ids)) {
+        if ($this->core->getQueries()->getUserById($grader_id)->getGroup() === User::GROUP_STUDENT) {
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:148]:
```suggestion
        if ($this->core->getUser()->getGroup() === User::GROUP_STUDENT) {
```

File: site/app/controllers/pdf/PDFController.php [hunk 2]
```diff
@@ -81,11 +81,15 @@ public function savePDFAnnotation($gradeable_id) {
         if ($gradeable === false) {
             return false;
         }
+        if ($this->core->getQueries()->getUserById($grader_id)->getGroup() === User::GROUP_STUDENT) {
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:84]:
```suggestion
        if ($this->core->getUser()->getGroup() === User::GROUP_STUDENT) {
```
