### PR TITLE
[Bugfix:Submission] Clamp timer progress

### LINKED ISSUE #10440: Bugs with Timed Notebook Gradeable
**Describe the bug**
Initially reported by another instructor, I observe the following bugs in timed notebook gradeable on the vagrant machine.  "Development" course, "Notebook Time Limit" gradeable (based on the "more_autograding_examples/notebook_time_limit" configuration).

First, I adjusted the due date to be less than 10 minutes from now:
Screenshot 2024-05-15 at 5 00 35 PM

As reported by the instructor, if the student starts very late in the gradeable window, with less than 10 minutes before the due date time, they are incorrectly given a countdown timer of 10 minutes, when they should be given the minimum/smaller of 10 minutes and the time remaining until the due date.  Students have mistakenly used most of the 10 minutes, submitted AFTER the deadline, and received a zero and complained it was unfair.  If a student starts very late, they will have less than 10 minutes, and that must be made clear on the UI.

Screenshot 2024-05-15 at 3 10 27 PM

Screenshot 2024-05-15 at 3 10 31 PM

---------------------------
Edit to clear up bug report in first version of this issue:

A separate confusion happens if there is a clock skew between the server/VM and the client/webbrowser machine.  This is hopefully a rare/non-real-world event, but I have encountered it often enough during my own development & testing I think we should fix it.  

This can be reproduced by manually setting the VM/server clock to be in the past (e.g., 6 days in the past) relative to the client/webbrowser machine clock.   NOTE:  This is not just changing the timezone, but rather changing the actual time.  Then, the following bugs/confusions happen:

- [ ] The rendering of the timer bar is buggy.  It is always dark red.  It is always full.  I think it's supposed to be a visualization of time remaining.  And it extends to the right beyond the end of the bar causing a useless horizontal scroll bar.  I see this on Mac Chrome and Mac Safari in light mode.  I haven't tested other OS/browsers or dark mode.

Screenshot 2024-05-15 at 2 43 31 PM

Screenshot 2024-05-15 at 2 43 36 PM

- [ ] The display indicates that we have many additional days until the deadline.  "06 days 03 hours" is roughly the time skew.  

- [ ] I would like to see this solved by adding a banner message on this page (on every page?) if the VM/server clock is more than a minute different than the clock on the client/browser.  NOTE: This is not just that the timezone is different -- which is a real and normal situation -- but that factoring out the timezone, the clocks are different.

### PR DESCRIPTION
**Pull request by akshitaa011**
### Why is this Change Important & Necessary?
Fixes #10440

The timed notebook gradeable had two bugs:
1. Timer showed wrong countdown when student starts late
2. Progress bar width could exceed 100% causing UI glitches

### What is the New Behavior?
- allowedTime is now clamped to not exceed time remaining until deadline
- Progress bar width clamped between 0% and 100%
- No more horizontal scrollbar overflow

### What steps should a reviewer take to reproduce or test the bug or new feature?
1. Create a timed notebook gradeable (10 min limit)
2. Set due date to less than 10 minutes from now
3. Start the gradeable as a student
4. Observe timer shows correct reduced time
5. Observe progress bar stays within bounds

### Automated Testing & Documentation
No existing automated tests cover this UI calculation.

### Other information
No breaking changes. No database migrations required.

### CODE REVIEW

File: site/public/js/submission-page.js [hunk 1]
```diff
@@ -166,7 +172,13 @@ function updateTime() {
...
                     hours = Math.floor(time / 3600) % 24;
                     days = Math.floor(time / (3600 * 24));
-                    width = ((Date.now() - startTime) / 1000 / 60 / allowedTime * 100) * 0.95 + 5;
+                    let percent_used = 0;
+                    if (allowedTime > 0 && startTime > 0) {
+                        percent_used = ((Date.now() - startTime) / 1000 / 60) / allowedTime;
+                    }
+                    percent_used = Math.min(1, Math.max(0, percent_used));
+                    width = (percent_used * 95) + 5;
+                    width = Math.min(100, Math.max(0, width));
```
Comment (Eli-J-Schwartz) [inline site/public/js/submission-page.js]: Isn't this line redundant with the two previous lines?

File: site/public/js/submission-page.js [hunk 2]
```diff
@@ -64,6 +64,12 @@ function syncWithServer(criticalSync) {
                 }
                 curTime = data.current_time;
                 deadline = data.deadline;
+                if (isTimed && user_deadline !== 0 && startTime !== 0 && allowedTime !== 0 && deadline !== 0) {
+                    const max_minutes_until_due_at_start = Math.max(0, Math.ceil((deadline - startTime) / 1000 / 60));
+                    allowedTime = Math.min(allowedTime, max_minutes_until_due_at_start);
+                    user_deadline = startTime + (allowedTime * 60 * 1000);
+                    user_deadline = Math.min(user_deadline, deadline);
+                }
```
Comment (Eli-J-Schwartz) [inline site/public/js/submission-page.js:69]: Why are we recalculating the timed deadline?
It looks like this whole block could be simplified to just:
`if (isTimed && user_deadline !== 0) {
                    user_deadline = Math.min(user_deadline, deadline);
}`

File: site/public/js/submission-page.js [hunk 3]
```diff
@@ -166,7 +172,13 @@ function updateTime() {
                     mins = Math.floor(time / 60) % 60;
                     hours = Math.floor(time / 3600) % 24;
                     days = Math.floor(time / (3600 * 24));
-                    width = ((Date.now() - startTime) / 1000 / 60 / allowedTime * 100) * 0.95 + 5;
+                    let percent_used = 0;
+                    if (allowedTime > 0 && startTime > 0) {
+                        percent_used = ((Date.now() - startTime) / 1000 / 60) / allowedTime;
+                    }
```
Comment (Eli-J-Schwartz) [inline site/public/js/submission-page.js]: Whats the point of wrapping the calculation in an if statement? Both allowedTime and startTime should always be above 0.

**Comment by akshitaa011** [comment]
Thank you for the detailed review @Eli-J-Schwartz! I’ve addressed all three points:

1. Removed the redundant `width = Math.min(100, Math.max(0, width))` line
2. Simplified the deadline logic to clamp `user_deadline` as suggested
3. Removed the conditional wrapper around the `percent_used` calculation

Please let me know if any further changes are needed. Thanks again!

File: site/public/js/submission-page.js
Comment (Eli-J-Schwartz) [inline site/public/js/submission-page.js:164]: If you add the following line:
`document.getElementById('gradeable-time-remaining-text").style.visibility="hidden";`
here, it should hide the duplicate time remaining boxes.

**Comment by akshitaa011** [comment]
Hi @Eli-J-Schwartz! I've implemented the change to hide the duplicate gradeable time remaining text using visibility: hidden, along with a null check for safety. Please let me know if anything else needs to be changed. Thank you!

**Comment by akshitaa011** [comment]
Thank you so much @Eli-J-Schwartz for the thorough review and 
testing! Really appreciate your time and patience!

**Comment by akshitaa011** [comment]
Thank you so much @Eli-J-Schwartz, @roye2, and @bmcutler for 
reviewing, testing, and merging this PR! I really appreciate 
the detailed feedback — it helped me write much cleaner code. 
Looking forward to contributing more!
