### PR TITLE
[Bugfix:CourseMaterials] Add Course Material Path Length Limit

### LINKED ISSUE #11468: course materials error when extra long title is specified for a URL
**Describe the bug**

An instructor reported a bug with course materials.  I found this in the logs:

```
09:37:08 02/13/2025 - FATAL ERROR
Doctrine\DBAL\Exception\DriverException (Code: 7) thrown in /usr/local/submitty/site/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php (Line 8
7) by:
        return new DriverException($exception, $query);


Message:
An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)

Stack Trace:
#0 /usr/local/submitty/site/vendor/doctrine/dbal/src/Connection.php(1943): Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert()
#1 /usr/local/submitty/site/vendor/doctrine/dbal/src/Connection.php(1885): Doctrine\DBAL\Connection->handleDriverException()
#2 /usr/local/submitty/site/vendor/doctrine/dbal/src/Statement.php(194): Doctrine\DBAL\Connection->convertExceptionDuringQuery()
#3 /usr/local/submitty/site/vendor/doctrine/dbal/src/Statement.php(249): Doctrine\DBAL\Statement->execute()
#4 /usr/local/submitty/site/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php(285): Doctrine\DBAL\Statement->executeStatement()
#5 /usr/local/submitty/site/vendor/doctrine/orm/src/UnitOfWork.php(1183): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#6 /usr/local/submitty/site/vendor/doctrine/orm/src/UnitOfWork.php(447): Doctrine\ORM\UnitOfWork->executeInserts()
#7 /usr/local/submitty/site/vendor/doctrine/orm/src/EntityManager.php(403): Doctrine\ORM\UnitOfWork->commit()
#8 /usr/local/submitty/site/app/controllers/course/CourseMaterialsController.php(887): Doctrine\ORM\EntityManager->flush()
#9 unknown file(unknown line): app\controllers\course\CourseMaterialsController->ajaxUploadCourseMaterialsFiles()
#10 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(268): call_user_func_array()
#11 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(246): app\libraries\routers\WebRouter->run()
#12 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()

USER: REDACTED
URL: https://submitty.cs.rpi.edu//courses/s25/REDACTED/course_materials/upload
```

I believe the error happened when the instructor specified an extra long title for url shared through course materials.  The attempted addition of this item to course materials failed with a non helpful error message.

**Expected behavior**

I think 255 chars is probably long enough for the title (even longer will just be more challenging to display) but let's have more clear warnings/errors when the user tries to input this long title.

### PR DESCRIPTION
**Pull request by raghavg332**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

**Fixes #11468**  
Instructors encountered an error when uploading course materials with **long titles** for external URLs. The logs showed:  
`Doctrine\DBAL\Exception\DriverException (Code: 7) ERROR: value too long for type character varying(255)`

Upon investigation, I found that the issue was not just with the title but with the entire file path being stored in the database. The path includes directory structures, making it **longer than 255 characters**, exceeding the database limit.  

For example, an input like:  
Title: `VeryLongTitleThatExceedsCharacterLimitAndKeepsGoingForAReallyLongTime`
Stored Path: `/var/local/submitty/courses/s25/blank/uploads/course_materials/VeryLongTitleThatExceedsCharacterLimitAndKeepsGoingForAReallyLongTime`

Result: The path exceeds the allowed length, causing a database failure. 

### What is the new behavior?
This PR **adds a pre-validation step** before storing the file path:  
- Checks if the generated file path exceeds 255 characters
- If too long, it prevents file creation and returns an error 
- Shows a clear message to the user, suggesting how many characters to reduce
- Prevents the "Failed to open stream" error when trying to write an invalid file 

Example Error Message:
Screenshot 2025-02-15 at 3 48 41 AM

### Other information?
- This is **not a breaking change** and only improves error handling.  
- **Tested** with various title lengths to ensure proper validation.

### CODE REVIEW

**Comment by bmcutler** [comment]
please improve this PR by incorporating
https://github.com/Submitty/Submitty/pull/11473

**Comment by raghavg332** [comment]
@bmcutler Edited to include changes proposed in PR #11473 by @mrtechtroid.

File: site/app/controllers/course/CourseMaterialsController.php [hunk 1]
```diff
@@ -670,6 +681,16 @@ public function ajaxUploadCourseMaterialsFiles(): JsonResponse {
                 );
             }
             $details['path'][0] = FileUtils::joinPaths($final_path, $file_name);
+
+            // Define max path length
+            define('MAX_PATH_LENGTH', 255);
+            // Ensure the key exists before checking the path length
+            if (isset($details['path'][0]) && strlen($details['path'][0]) > MAX_PATH_LENGTH) {
```
Comment (shailpatels) [inline site/app/controllers/course/CourseMaterialsController.php:688]: This looks like you're checking the max length of the requested file path + title together but those are stored in separate columns:
image

I think the path and title should be checked separately, similar to how you implemented it in the edit course materials function

**Review by shailpatels — CHANGES_REQUESTED** [review]

File: site/app/controllers/course/CourseMaterialsController.php (hunk 1 above)
Comment (raghavg332) [reply site/app/controllers/course/CourseMaterialsController.php:688]: added this!

**Comment by mrtechtroid** [comment]
@raghavg332 Common functions arent used, instead same code is duplicated in both places. (As @bmcutler mentioned on my PR, dont duplicate code. )

File: site/app/controllers/course/CourseMaterialsController.php [hunk 2]
```diff
@@ -670,6 +681,20 @@ public function ajaxUploadCourseMaterialsFiles(): JsonResponse {
                 );
             }
             $details['path'][0] = FileUtils::joinPaths($final_path, $file_name);
+
+            // Define max path length
+            define('MAX_PATH_LENGTH', 255);
```
Comment (Troy-bailan-King) [inline site/app/controllers/course/CourseMaterialsController.php:686]: Maybe just define "MAX_PATH_LENGTH" once?

**Review by Troy-bailan-King — CHANGES_REQUESTED** [review]

File: site/app/controllers/course/CourseMaterialsController.php [hunk 3]
```diff
@@ -471,6 +471,10 @@ public function ajaxEditCourseMaterialsFiles(bool $flush = true): JsonResponse {
                     return JsonResponse::getErrorResponse("Invalid path or filename");
                 }
 
+                if (($overflow = strlen($new_path) - 255) > 0) {
+                    return JsonResponse::getErrorResponse("The new file name is too long. Please reduce it by {$overflow} characters.");
```
Comment (williamschen23) [inline site/app/controllers/course/CourseMaterialsController.php:475]: a more apropriate message here would be title is too long. Do you know what this tests for?

**Review by williamschen23 — CHANGES_REQUESTED** [review]

File: site/app/controllers/course/CourseMaterialsController.php (hunk 3 above)
Comment (Chriun) [reply site/app/controllers/course/CourseMaterialsController.php:475]: That's true. This part checks, when editing the course material title, if the path + title is greater than 255 characters. The other part checks if the original uploaded course material has a path + title greater than 255 characters, if that makes sense.

**Review by williamschen23 — APPROVED** [review]
Tested and error messages do exist
