### PR TITLE
[Bugfix:InstructorUI] Due date validation for isStudentSubmit

### LINKED ISSUE #9720: Dates in Edit Gradeables
**Describe the bug**
When an instructor creates a gradeable and on the Submissions/Autograding Page, the setting "Make new submissions and access all prior versions?" is set to "NO", you can't properly edit dates. 
See below the comparison of the expected behavior vs the bug. Notice the expected behavior: When you try to put an incorrect date ( for example due date before submission open date), the "submission open date" box becomes red, warning you and allowing you the chance to put it earlier. 
However with this bug, when you try to put the due date before the submission open date, the due date gets locked and copies the value of the submission open date.
**Expected behavior**
When the setting "Make new submissions and access all prior versions?" is set to "NO", the dates should have the same behavior as when the setting is set to YES.
**To Reproduce**
1. Create a gradeable
2. Go to Submissions/Autograding
3. Choose "No" for: "New submissions and access all prior versions?" 
4. Go to Dates
5. Try putting incorrect dates
6. See error

**Screenshots**
This is the expected behavior:
https://github.com/Submitty/Submitty/assets/131885371/5c56e77f-842b-4be7-8b5d-6560520974b8

This is the bug:

https://github.com/Submitty/Submitty/assets/131885371/24f77dd0-3045-49a4-8df6-3ca58b97e06a

**Additional context**

### PR DESCRIPTION
**Pull request by GO-viper7**
Closes #9720 

### Please check if the PR fulfills these requirements:

* [✅] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

An instructor logs in and edits a gradeable
Instructor changes this setting "Make new submissions and access all prior versions?" to NO
Then due date validation stops working due to a bug.

### What is the new behavior?

Even if the  "Make new submissions and access all prior versions?" is set to NO
Due date validation works as intended.

[Due-date-validation.webm](https://github.com/Submitty/Submitty/assets/81346327/538d2544-0e46-4cb5-ada9-24c01542b7e6)

### CODE REVIEW

File: site/app/models/gradeable/Gradeable.php [hunk 1]
```diff
@@ -784,23 +784,16 @@ private static function validateDateSet(array $date_properties, array $date_valu
...
-            if (!$this->isStudentSubmit()) {
-                if ($this->isTaGrading()) {
-                    $result = self::date_properties_elec_exam;
-                }
-                else {
-                    $result = self::date_properties_bare;
-                }
-            }
-            elseif ($this->isTaGrading()) {
+            // $this->isStudentSubmit() == true indicates student can make multiple submissions
```
Comment (wuj18) [inline site/app/models/gradeable/Gradeable.php:787]: I don't think we need to include this comment here since we are not using isStudentSubmit() anymore, and the meaning of 'student submit' is already commented on at line 231

Comment (GO-viper7) [reply site/app/models/gradeable/Gradeable.php]: Got it, removed the comment
you may run the tests.

**Review by wuj18 — APPROVED** [review]

File: site/app/models/gradeable/Gradeable.php [hunk 2]
```diff
@@ -784,23 +784,16 @@ private static function validateDateSet(array $date_properties, array $date_valu
...
+            // Even if student cannot make multiple submissions, submission_open_date has to be included for validation
```
[the remark this answers is not in the document]
Comment (GO-viper7) [reply site/app/models/gradeable/Gradeable.php]: Yes you are right, I misunderstood the part
Updated the comments and pushed the changes 👍

**Review by williamlin6803 — APPROVED** [review]
I tested it on my system and it works as seen in the video. The code looks fine as well.

**Comment by bmcutler** [comment]
@GO-viper7 Thanks for the contribution!
