### PR TITLE
[Bugfix:Forum] Fix edit post from main page

### LINKED ISSUE #9966: Error when editing a post without clicking into it on the discussion forum
**Describe the bug**
On the discussion forum, when attempting to  edit a post from the main discussion forum page, an error message is given and the message isn't updated.

**Expected behavior**
The post should be able to be edited with no errors.

**To Reproduce**
1.  Create a discussion forum post
2.  From the main discussion forum page, attempt to edit the post
3. See error

**Configuration**
 - OS: Windows
 - Browser: Edge

**Screenshots**

image

**Additional context**

Let me know if you're able to reproduce this bug!

### PR DESCRIPTION
**Pull request by DarthNyan**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Closes #9966 . Currently, there is an error when trying to edit a post from the main forum page.

### What is the new behavior?
This fixes the error and allows users to edit posts from the main forum page.

### CODE REVIEW

**Review by taorif25 — APPROVED** [review]
Works as intended, bug is gone on this branch. Code changes are minimal and are isolated to the bug.

File: site/public/js/forum.js [hunk 1]
```diff
@@ -2216,13 +2216,13 @@ function updateThread(e) {
         edit_post_id: $('#edit_post_id').val(),
         csrf_token: $('input[name="csrf_token"]').val(),
         title: $('input#title').val(),
-        thread_post_content: $('textarea#reply_box_').val(),
+        thread_post_content: $('textarea#reply_box_0').val(),
```
Comment (ziesski) [inline site/public/js/forum.js:2219]: The `.val()` is used to get the current value of selected element, which will return the corresponding value of `reply_box_` so manually inserting a digit should not be the solution.

File: site/public/js/forum.js [hunk 2]
```diff
@@ -2216,13 +2216,13 @@ function updateThread(e) {
...
         thread_status: $('#thread_status').val(),
         Anon: $('input#thread_post_anon_edit').is(':checked') ? $('input#thread_post_anon_edit').val() : 0,
         lock_thread_date: $('input#lock_thread_date').text(),
         expirationDate: $('input#expirationDate').val(),
         cat,
-        markdown_status: parseInt($('input#markdown_input_').val()),
+        markdown_status: parseInt($('input#markdown_input_0').val()),
```
Comment (ziesski) [inline site/public/js/forum.js:2225]: same thing here

File: site/public/js/forum.js (hunk 1 above)
Comment (DarthNyan) [reply site/public/js/forum.js]: The bug was that '#reply_box' didn't select anything because each reply box has an int appended to their id to distinguish them. The box in the edit post form is always zero (EditPostForm.twig line 13), so the hardcoded number would have worked. I did just make the change to select the post box id and use that though.

**Comment by DarthNyan** [comment]
This shouldn't affect the forum cypress test. At present, it only tests creating, replying, merging, and deleting but not editing or splitting threads as far as I can tell.

**Comment by IDzyre** [comment]
Correct, the forum tests currently only test creating, commenting, merging, and deleting forum posts. This may be a thing you can create an issue on, more tests for the forum so we catch this type of bug before it happens.

**Review by ziesski — APPROVED** [review]
Looks good to me :)
