### PR TITLE
[Bugfix:TAGrading] Improve grading index column order

### LINKED ISSUE #7732: Columns are inconsistent: anon vs non-anon mode
**Describe the bug**
non anon mode:

Screen Shot 2022-03-13 at 1 53 15 PM

The blue "Grade" button is replaced by the white button with the final grade when all manual grading parts are finished.

anon mode:
Screen Shot 2022-03-13 at 1 53 24 PM

The blue "Grade" button is always there.

Why in anon mode do we get a different ordering of columns and different behavior?  The only difference should be that the multiple name columns are merged & replaced with an anon id column.

(Sorry if this is already fixed by an open PR...)

### PR DESCRIPTION
**Pull request by DefinitiveAbove**
### What is the current behavior?
* #7732 

### What is the new behavior?
Closes #7732 
Grading index in anon mode changed to have columns in the same order as non-anon mode.

The `Grading` column in anon-mode now behaves identically to non-anon mode when a limited-access grader or above is viewing the grading index (students will only see their own grading score in peer grading).
image

### CODE REVIEW

File: site/app/views/grading/ElectronicGraderView.php [hunk 1]
```diff
@@ -477,93 +475,65 @@ public function detailsPage(Gradeable $gradeable, $graded_gradeables, $teamless_
...
-                $columns[]     = ["width" => "7%",  "title" => "Total",            "function" => "total"];
-                $columns[]     = ["width" => "10%", "title" => "Active Version",   "function" => "active_version"];
-                if ($gradeable->isTaGradeReleased()) {
-                    $columns[] = ["width" => "8%",  "title" => "Viewed Grade",     "function" => "viewed_grade"];
-                }
+            }
+            if ($gradeable->isTaGrading()) {
+                $columns[]     = ["width" => "8%",  "title" => "Graded Questions", "function" => "graded_questions"];
+            }
+            if ($this->core->getUser()->getGroup() == User::GROUP_LIMITED_ACCESS_GRADER && $gradeable->getLimitedAccessBlind() == 2) {
```
Comment (williamjallen) [inline site/app/views/grading/ElectronicGraderView.php:527]:
```suggestion
            if ($this->core->getUser()->getGroup() === User::GROUP_LIMITED_ACCESS_GRADER && $gradeable->getLimitedAccessBlind() === 2) {
```

Comment (williamjallen) [reply site/app/views/grading/ElectronicGraderView.php:527]: Is it possible to replace `2` with a constant here?

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/templates/grading/electronic/Details.twig [hunk 2]
```diff
@@ -491,11 +491,14 @@
...
                 {% set contents = "Grading Incomplete" %}
             {% elseif graded_gradeable.isTaGradingComplete() and core.getUser().getGroup() == 4 and graded_gradeable.isPeerGradingComplete() %}
-            {% set contents = graded_gradeable.getTaGradedGradeable.getTotalScore(core.getUser()) ~ " / " ~ graded_gradeable.getGradeable().getPeerPoints() %}
+                {% set contents = graded_gradeable.getTaGradedGradeable.getTotalScore(core.getUser()) ~ " / " ~ graded_gradeable.getGradeable().getPeerPoints() %}
                 {% set btn_class = "btn-default" %}
             {% elseif not graded_gradeable.isTaGradingComplete() and core.getUser().getGroup() == 4 and graded_gradeable.isPeerGradingComplete() %}
                 {% set contents = graded_gradeable.getTaGradedGradeable.getTotalScore(core.getUser()) ~ " / " ~ graded_gradeable.getGradeable().getPeerPoints() %}
-            {% set btn_class = "btn-default" %}
+                {% set btn_class = "btn-default" %}
+            {% elseif graded_gradeable.isTaGradingComplete() and core.getUser().getGroup() < 4 and graded_gradeable.isPeerGradingComplete() %}
```
Comment (shailpatels) [inline site/app/templates/grading/electronic/Details.twig:499]: Could use the function `accessGrading` to make it more explicit what that check is doing

```suggestion
            {% elseif graded_gradeable.isTaGradingComplete() and core.getUser().accessGrading() and graded_gradeable.isPeerGradingComplete() %}
```

**Comment by bmcutler** [comment]
@williamjallen @shailpatels 
Please re-review

**Review by williamjallen — APPROVED** [review]
Changes look good and appear to work correctly.  My only comment is that one column is labeled "Grading" in anonymous mode and "TA Grading" otherwise.

**Review by williamjallen — APPROVED** [review]
