### PR TITLE
[Bugfix:Autograding] Fix Leaderboard Error With No Tests

### LINKED ISSUE #11251: Gradeable with Leaderboard with no matching test cases
**Describe the bug**

I was preparing a gradeable with the leaderboard feature. 

e.g.,
https://github.com/Submitty/Submitty/blob/main/more_autograding_examples/leaderboard/config/config.json

and on the developement machine:
http://localhost:1511/courses/f24/sample/gradeable/leaderboard

I created a number of leaderboards, and assigned test cases to leaderboards.   I was writing & testing incrementally, and when I tested a configuration where there was a leaderboard tag (in the "leaderboards" json object) with no assigned test cases (no test case "leaderboard_tags" includes that tag).

When I attempted to view the unused leaderboard, the page gave a frog robot error:

```
23:56:40 12/09/2024 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 166) by:
           throw new DatabaseException($dbalException->getMessage(), $query, $parameters);


Message:
An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"
LINE 25:                    AND        testcase_id in ()
                                                      ^

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(9216): app\libraries\database\AbstractDatabase->query()
#1 /usr/local/submitty/site/app/controllers/student/LeaderboardController.php(82): app\libraries\database\DatabaseQueries->getLeaderboard()
#2 unknown file(unknown line): app\controllers\student\LeaderboardController->getLeaderboardData()
#3 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(268): call_user_func_array()
#4 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(246): app\libraries\routers\WebRouter->run()
#5 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()
Extra Details:
	query: 
SELECT    leaderboard.*,
         gradeable_anon.anon_id,
         user_group,
         anonymous_leaderboard,
         Concat(
             COALESCE (NULLIF(user_preferred_givenname, ''), user_givenname),
             ' ',
             COALESCE (NULLIF(user_preferred_familyname, ''), user_familyname)
         ) as name
FROM (
                  SELECT     Round(Cast(Sum(elapsed_time) AS NUMERIC), 1) AS time,
                             Sum(max_rss_size)                            AS memory,
                             metrics.g_id                                 AS gradeable_id,
                             metrics.user_id                              AS user_id,
                             metrics.team_id                              AS team_id,
                             Sum(points)                                  AS points
                  FROM       autograding_metrics                          AS metrics
                  INNER JOIN electronic_gradeable_version                 AS version
                  ON         NULLIF(metrics.user_id, '') = NULLIF(version.user_id, '')
                  AND        metrics.g_id = version.g_id
                  AND        metrics.g_version = version.active_version
                  WHERE      metrics.g_id = ?
                  AND        passed = true
                  AND        testcase_id in ()
                             -- When true, this statement is always true, and so the value in the hidden column is ignored
                             -- When false, hidden values are left out of the query
                  AND        (
                                        hidden = false
                             OR         hidden = ?)
                  GROUP BY   metrics.user_id,
                             metrics.team_id,
                             metrics.g_id
) AS leaderboard
LEFT JOIN users
ON        leaderboard.user_id = users.user_id
LEFT JOIN gradeable_anon
ON leaderboard.user_id = gradeable_anon.user_id AND leaderboard.gradeable_id = gradeable_anon.g_id
LEFT JOIN electronic_gradeable_version
ON        leaderboard.gradeable_id = electronic_gradeable_version.g_id
         AND leaderboard.user_id = electronic_gradeable_version.user_id
ORDER BY
   points DESC,
   time,
   memory

	parameters:
		REDACTED
		true

URL: https://submitty.cs.rpi.edu//courses/f24/REDACTED/gradeable/REDACTED/leaderboard_data/all_solutions
```

### PR DESCRIPTION
**Pull request by lllinging**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently, when using a configuration with a leaderboard tag (in the "leaderboards" json object) and without assigned test cases (no test case "leaderboard_tags" includes that tag), the unused leaderboard page shows the frog robot error.

### What is the new behavior?
Fixes #11251 

The unused leaderboard page shows an empty table.

### CODE REVIEW

**Review by lavalleeale — CHANGES_REQUESTED** [review]
I'm unsure this is the best way to fix this issue. Testing locally proves that the change does produce the correct functionality, but querying for `testcase_id in (NULL)` seems like a strange query, and modifying the behavior of `createParameterList` likely requires a review of all of its usages to make sure that it is not possibly breaking things elsewhere. I think adding a comment above the function to explain that case and looking at all of its callers to make sure this wont break anything else is important.

**Comment by lllinging** [comment]
> I'm unsure this is the best way to fix this issue. Testing locally proves that the change does produce the correct functionality, but querying for `testcase_id in (NULL)` seems like a strange query, and modifying the behavior of `createParameterList` likely requires a review of all of its usages to make sure that it is not possibly breaking things elsewhere. I think adding a comment above the function to explain that case and looking at all of its callers to make sure this wont break anything else is important.

My understanding is, the purpose of having `createParameterList($len)` is to generate a string that consists of `$len` number of placeholder parameters (?) enclosed in parentheses. These placeholders will then be used for parameter binding when executing the SQL query.

After reviewing all of its usage, I found that they could be categorized into three cases:
1. Taking a positive integer as input, such as [code link 1](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L679). There's only one usage like this, and the changes introduced by this PR certainly won't break it, because the input is greater than 1.
2. Taking the count of an array as input, while the count validated to be greater than 0 before calling this method. Such as [code link 2](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L781), where right before calling this method, there's a if statement that will return empty list if the count is zero. In this case, the changes introduced by this PR also won't break the current behavior, because the input is guaranteed to be greater than or equal to 1.
3. Taking the count of an array as input, while the count is not validated to be greater than 0. I found 12 such cases: [1](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L1314), [2](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L2168), [3](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L3211), [4](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L3684), [5](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L4832), [6](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L5096), [7](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L5112), [8](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L5123), [9](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L5136), [10](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L5213), [11](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L7230), [12](https://github.com/Submitty/Submitty/blob/1056109556d116f9bac538c76be045abdf16ba1d/site/app/libraries/database/DatabaseQueries.php#L9118) (this is the one that caused the [original issue](https://github.com/Submitty/Submitty/issues/11251)). In these cases, the input to the createParameterList could be 0. When that happens, the current behavior is returning `()`. However, `IN ()` is not valid SQL syntax, so it will cause error. With this PR's change, when input is 0, this method will return `(NULL)`, and `IN (NULL)` is valid SQL syntax. Therefore, it won't causing any breaking, instead, it can help avoid some potential errors.

I will add some comment above the function to explain it.

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -1252,7 +1252,19 @@ public function getGradeableVersionHasAutogradingResults($g_id, $version, $user_
...
+    /**
+     * Create a string that consists placeholder parameters (?) enclosed in parentheses.
+     * These placeholders will then be used for parameter binding when executing the SQL query.
+     * When $len is zero, this function will return '(NULL)' so that it won't break SQL syntax.
+     *
+     * @param integer $len the number of placeholder parameters.
+     *
+     * @return string
+     */
     protected function createParameterList($len) {
```
Comment (lavalleeale) [inline site/app/libraries/database/DatabaseQueries.php:1264]: We want to make all new types also use native PHP syntax
```suggestion
     */
    protected function createParameterList(int $len): string {
```

**Review by lavalleeale — CHANGES_REQUESTED** [review]
After my suggested changes are resolved I am ready to approve, code looks good and tested locally

**Review by williamjallen — APPROVED** [review]
