### PR TITLE
Fix "redo rotating sections" causing errors with teams

### LINKED ISSUE #2671: Rotating sections broken :(
From the setup sections page:
Attempting to redo the rotating sections completely...

FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 175) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "sections_rotating" violates foreign key constraint "gradeable_teams_rotating_section_fkey" on table "gradeable_teams"
DETAIL:  Key (sections_rotating_id)=(1) is still referenced from table "gradeable_teams".

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(1194): app\libraries\database\AbstractDatabase->query('DELETE FROM sections_rotating')
#1 /usr/local/submitty/site/app/controllers/admin/UsersController.php(361): app\libraries\database\DatabaseQueries->deleteAllRotatingSections()
#2 /usr/local/submitty/site/app/controllers/admin/UsersController.php(37): app\controllers\admin\UsersController->updateRotatingSections()
#3 /usr/local/submitty/site/app/controllers/AdminController.php(58): app\controllers\admin\UsersController->run()
#4 /usr/local/submitty/site/public/index.php(240): app\controllers\AdminController->run()
Extra Details:
	query: DELETE FROM sections_rotating
	parameters:

### PR DESCRIPTION
**Pull request by CouleeApps**
Teams weren't being cleared of their rotating sections before redoing sections. This should clear them first, create new sections, and randomly assign teams to those sections. Also handles the function for assigning teams with NULL rotating sections to the smallest section.

Closes #2671

### CODE REVIEW

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -1119,11 +1119,11 @@ public function getGradeablesPastAndSection() {
      */
     public function getCountUsersRotatingSections() {
         $this->course_db->query("
-SELECT rotating_section, count(*) as count
-FROM users
-WHERE registration_section IS NOT NULL
-GROUP BY rotating_section
-ORDER BY rotating_section");
+            SELECT rotating_section, count(*) as count
```
Comment (bmcutler) [inline site/app/libraries/database/DatabaseQueries.php]: Why change this indenting?  
This is now different than on queries in this file.  I don't see functional changes on these lines.

Comment (bmcutler) [reply site/app/libraries/database/DatabaseQueries.php]: (And the others below as well)
