### PR TITLE
[Bugfix:Notifications] Fix Invalid Email Status Pagination

### LINKED ISSUE #11799: Email status page not changing
**Describe the bug**

In the email status page for instructors, we see the status of emails for each student under the course for announcements/grade notifications. However, clicking to a different page does not actually change the page listing for email statuses.

**Expected behavior**

We would expect the page to redirect to the correct email status listing.

**To Reproduce**
1. Go to Email Status as instructor.
2. Scroll to the bottom and click on a different page.
3. See error

**Configuration**
 - OS: Windows
 - Browser: Firefox

**Screenshots**

Image

Image

**Additional context**

### PR DESCRIPTION
**Pull request by jeffrey-cordero**
### Why is this Change Important & Necessary?

The email status page only displays the first page, regardless of the currently selected page. I believe this was never caught or documented, as most instructors or administrators would usually visit this page to verify recent, but not old, email details. Fixes #11799.

### What is the New Behavior?

The email status page now displays the correct page. The error stemmed from the invalid controller logic, where the page was determined by the POST request object, which was empty or undefined, as the pagination request is a GET request. Additionally, the repository code was refactored for clarity measures.

Old (all pages are the same)

image

New (expected last page)

image

### What steps should a reviewer take to reproduce or test the bug or new feature?

You can test the expected pages (10 emails or 5000 recipients per page) through the following commands, which are based on emails, not recipient limits. The following is also not tied to a specific course, which would require the `WHERE course='x' AND term='y'` clause to work, thus log in as the `superuser` to match the emails.

```bash
$ sudo su postgres
$ psql
$ \c submitty
$ SELECT
  ROW_NUMBER() OVER (ORDER BY e.created DESC) AS index,
  e.subject,
  e.created,
  COUNT(*) AS cnt
FROM emails e
GROUP BY e.subject, e.created
ORDER BY e.created DESC;
```

### Automated Testing & Documentation

There are no existing email status page tests, but I'll make an issue to ensure they're implemented as E2E tests to account for pagination, errors, and detail verification.

### Other information

N/A

### CODE REVIEW

File: site/app/repositories/email/EmailRepository.php [hunk 1]
```diff
@@ -35,18 +35,17 @@ public function getEmailsByPage(int $page, $semester = null, $course = null): ar
 
     public function getPageNum($semester = null, $course = null): int {
         if ($semester != null || $course != null) {
-            $dql = 'SELECT e.subject, e.created, COUNT(e) FROM app\entities\email\EmailEntity e WHERE e.term = \'' . $semester . '\' AND e.course = \'' . $course . '\' GROUP BY e.subject, e.created ORDER BY e.created DESC';
+            $dql = 'SELECT e.subject, e.created, COUNT(e) AS cnt FROM app\entities\email\EmailEntity e WHERE e.term = \'' . $semester . '\' AND e.course = \'' . $course . '\' GROUP BY e.subject, e.created ORDER BY e.created DESC';
         }
         else {
-            $dql = 'SELECT e.subject, e.created, COUNT(e) FROM app\entities\email\EmailEntity e GROUP BY e.subject, e.created ORDER BY e.created DESC';
+            $dql = 'SELECT e.subject, e.created, COUNT(e) AS cnt FROM app\entities\email\EmailEntity e GROUP BY e.subject, e.created ORDER BY e.created DESC';
```
Comment (Chriun) [inline site/app/repositories/email/EmailRepository.php]: We should probably change this to use the query builder like in getEmailsByPage to be consistent and also prevent any potential injection.

File: site/app/repositories/email/EmailRepository.php [hunk 2]
```diff
@@ -59,29 +58,34 @@ public function getPageNum($semester = null, $course = null): int {
 
     private function getPageSubjects($page, $semester = null, $course = null): array {
         if ($semester != null || $course != null) {
-            $dql = 'SELECT e.subject, e.created, COUNT(e) FROM app\entities\email\EmailEntity e WHERE e.term = \'' . $semester . '\' AND e.course = \'' . $course . '\' GROUP BY e.subject, e.created ORDER BY e.created DESC';
+            $dql = 'SELECT e.subject, e.created, COUNT(e) AS cnt FROM app\entities\email\EmailEntity e WHERE e.term = \'' . $semester . '\' AND e.course = \'' . $course . '\' GROUP BY e.subject, e.created ORDER BY e.created DESC';
         }
         else {
-            $dql = 'SELECT e.subject, e.created, COUNT(e) FROM app\entities\email\EmailEntity e GROUP BY e.subject, e.created ORDER BY e.created DESC';
+            $dql = 'SELECT e.subject, e.created, COUNT(e) AS cnt FROM app\entities\email\EmailEntity e GROUP BY e.subject, e.created ORDER BY e.created DESC';
```
Comment (Chriun) [inline site/app/repositories/email/EmailRepository.php]: Same here.

File: site/app/repositories/email/EmailRepository.php (hunk 1 above)
Comment (jeffrey-cordero) [reply site/app/repositories/email/EmailRepository.php]: Good call. I'll implement this, but this is an instructor/admin. endpoint, so the risk is pretty low.

**Review by Chriun — COMMENTED** [review]
image

image
There seems to be an extra page at the end with zero emails.

**Review by Chriun — APPROVED** [review]
Requested changes have been addressed and nothing seems to crash.
