### PR TITLE
Filename fix

### LINKED ISSUE #1596: Cannot handle a '+' in a pdf file name
Example "Assignment+5.pdf"
In TA grading, displays as a blank/empty pdf (both inline display & popout display).
When download is attempted, it says: "could not be opened because it is empty"

When this is debugged, please verify that we handle every(?) weird character that can be in a filename.

### PR DESCRIPTION
**Pull request by shailpatels**
Users can now submit filenames that include the '+' character (along with other reserved types e.g. '&'  '/ ' '%'...). 

When files are uploaded to Submitty, their names are now encoded using encodeURIComponent to make sure special characters are being read literally and not interpreted. Downloading and viewing PDF's have been modified to read encoded file names. The user will always see their normal file names.

Fixes #1596 
Closes #1596

### CODE REVIEW

File: site/public/js/drag-and-drop.js [hunk 1]
```diff
@@ -672,7 +672,8 @@ function handleSubmission(days_late, late_days_allowed, versions_used, versions_
                     alert("ERROR! You may not use angle brackets in your filename: " + file_array[i][j].name);
                     return;
                 }
-                formData.append('files' + (i + 1) + '[]', file_array[i][j]);
+                formData.append('files' + (i + 1) + '[]', file_array[i][j], encodeURIComponent(file_array[i][j].name)
```
Comment (bmcutler) [inline site/public/js/drag-and-drop.js]: Did you mean to leave the 3rd argument here?

Comment (shailpatels) [reply site/public/js/drag-and-drop.js]: Yes I did, the third argument was a bit long so I wrote it over 2 lines, but yea files should be encoded there.
```
formData.append('files' + (i + 1) + '[]', file_array[i][j], encodeURIComponent(file_array[i][j].name)
          .replace(/\!/g, "%21").replace(/\(/g, "%28").replace(/\)/g, "%29"));
```

Comment (shailpatels) [reply site/public/js/drag-and-drop.js]: Oh sorry I think I misread where that code is, so I think your right with the third argument, there should be a different method to encode bulk uploads since it looks like that is based on timestamps instead

Comment (shailpatels) [reply site/public/js/drag-and-drop.js]: Encoding methods for both handle submission and handle bulk submission are now updated and further tested.

File: site/app/controllers/MiscController.php [hunk 2]
```diff
@@ -179,19 +179,20 @@ private function displayFile() {
             return false;
         }
 
-        $mime_type = FileUtils::getMimeType($_REQUEST['path']);
+		$corrected_name = pathinfo($_REQUEST['path'], 1) . "/" . rawurlencode( basename($_REQUEST['path']));
```
Comment (MasterOdin) [inline site/app/controllers/MiscController.php]: Fix spacing to be consistent with rest of file. Use a PHP constant for the option flag instead of a magic 1.

File: site/app/controllers/MiscController.php [hunk 3]
```diff
@@ -215,7 +216,7 @@ private function downloadFile() {
         header('Content-Type: application/octet-stream');
         header("Content-Transfer-Encoding: Binary"); 
         header("Content-disposition: attachment; filename=\"{$_REQUEST['file']}\"");
-        readfile($_REQUEST['path']);
+		readfile(pathinfo($_REQUEST['path'], 1) . "/" . rawurlencode( basename($_REQUEST['path'])));
```
Comment (MasterOdin) [inline site/app/controllers/MiscController.php]: Fix spacing

**Comment by bmcutler** [comment]
@MasterOdin, are you ok with this PR now?

File: site/app/controllers/MiscController.php [hunk 4]
```diff
@@ -179,20 +179,21 @@ private function displayFile() {
             return false;
         }
 
-        $mime_type = FileUtils::getMimeType($_REQUEST['path']);
+		$corrected_name = pathinfo($_REQUEST['path'], PATHINFO_DIRNAME) . "/" . rawurlencode( basename($_REQUEST['path']));
```
Comment (MasterOdin) [inline site/app/controllers/MiscController.php]: fix spacing here

File: site/app/controllers/MiscController.php [hunk 5]
```diff
@@ -215,7 +216,7 @@ private function downloadFile() {
         header('Content-Type: application/octet-stream');
         header("Content-Transfer-Encoding: Binary"); 
         header("Content-disposition: attachment; filename=\"{$_REQUEST['file']}\"");
-        readfile($_REQUEST['path']);
+		readfile(pathinfo($_REQUEST['path'], PATHINFO_DIRNAME) . "/" . rawurlencode( basename($_REQUEST['path'])));
```
Comment (MasterOdin) [inline site/app/controllers/MiscController.php]: spacing

File: site/app/controllers/MiscController.php (hunk 4 above)
Comment (shailpatels) [reply site/app/controllers/MiscController.php]: capture

Fixed
