### PR TITLE
[Bugfix:InstructorUI] Fix Gradeable JSON Boolean Fields

### LINKED ISSUE #12151: Uploading Gradeable JSON defaults to peer grading even when it is set to false
**Describe the bug**
When uploaded a Gradeable JSON, the rubric components are automatically being defaulted to peer grading even when the value for `peer_component` is set to `false`.

**Expected behavior**
The rubric component should not have peer grading enabled.

**To Reproduce**
1. Upload gradeable with `peer_component` set to `false`
2. Head to Rubric tab
3. See error

**Configuration**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox

**Screenshots**
N/A

**Additional context**
JSON I have been using and seeing the issue on.

```json
{
    "title": "Status Update 11\/07\/2025",
    "type": "Electronic File",
    "id": "StatusUpdate7",
    "instructions_url": "",
    "syllabus_bucket": "lab",
    "autograding_config_path": "\/var\/local\/submitty\/courses\/f25\/csci1700\/config_upload\/StatusUpdate_v01",
    "bulk_upload": false,
    "ta_grading": true,
    "dates": {
        "ta_view_start_date": "2025-09-25 21:46:43",
        "grade_start_date": "2025-11-09 23:59:59",
        "grade_due_date": "2025-11-13 23:59:59",
        "grade_released_date": "9998-01-01 00:00:00",
        "team_lock_date": "2025-09-26 15:59:59",
        "submission_open_date": "2025-11-07 15:59:59",
        "submission_due_date": "2025-11-07 23:59:59",
        "grade_inquiry_start_date": "2025-10-11 23:59:59",
        "grade_inquiry_due_date": "2025-10-17 23:59:59",
        "has_due_date": true,
        "has_release_date": true,
        "late_submission_allowed": true,
        "late_days": 2
    },
    "rubric": [
        {
            "title": "Status Update Grade",
            "ta_comment": "",
            "student_comment": "",
            "lower_clamp": 0,
            "default": 0,
            "max_value": 10,
            "upper_clamp": 10,
            "text": true,
            "peer_component": false,
            "page": 0,
            "is_itempool_linked": true,
            "itempool": "",
            "marks": [
                {
                    "points": 0,
                    "title": "No Credit",
                    "publish": false
                },
                {
                    "points": 10,
                    "title": "Full credit.",
                    "publish": false
                },
                {
                    "points": 4,
                    "title": "Thorough \"This Week\" section. Good job.",
                    "publish": false
                },
                {
                    "points": 4,
                    "title": "Thorough \"Next Week\" section. Good job.",
                    "publish": false
                },
                {
                    "points": 1,
                    "title": "Complete \"Blockers\" section. This field must be filled out but may contain \"No blockers to report\" if there are no technical issues preventing you from making progress.",
                    "publish": false
                },
                {
                    "points": 1,
                    "title": "Complete \"Links\" section. This field must be filled out but may contain \"No links to submit\" if you have no open-source contributions to report. If links are reported, they must be to valid user generated open-source contributions",
                    "publish": false
                },
                {
                    "points": 2,
                    "title": "\"This Week\" requires greater detail.",
                    "publish": false
                },
                {
                    "points": 2,
                    "title": "\"Next Week\" requires greater detail.",
                    "publish": false
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by RyanStyron**
### Why is this Change Important & Necessary?

Fixes #12151.
As described in the issue, uploading a Gradeable JSON currently results in peer grading being enabled regardless of the assignment of the `peer_component` property. This bug is caused by the Gradeable construction logic not interpretting certain values in the JSON as boolean, which results in a string being parsed instead. This has now been fixed via invocation of the  `Utils::getBooleanValue` method.

### What steps should a reviewer take to reproduce or test the bug or new feature?
Download the Gradeable JSON of _Bulk Upload Scanned Exam_ in the _Sample_ course. Edit the JSON so that the `id` field is different (i.e. add `_1` to the existing `id`) and ensure that for one of the rubric sections, `peer_component` is set to `true` and that for another it is set to `false`. Create a new Gradeable in the _Sample_ course by uploading this JSON. Note how both of the rubric sections are highlighted purple (indicating peer grading).
Checkout this branch, repeat the same steps, and note how the peer grading sections are assigned properly.

### CODE REVIEW

**Review by Rkoester47 — APPROVED** [review]
I followed the steps outlined in the PR to reproduce the issue on main. As expected, all three sections of the rubric were highlighted purple for TA grading even though I had only set the first one to "True".

After repeating steps on this branch, the issue appears to be resolved. I uploaded another copy of the Bulk Exam JSON file, and now only the first section was purple as intended. Based on the description of the issue and expected outcome of this PR, the changes made seemed to have resolved the issue.

File: site/app/models/gradeable/Component.php [hunk 1]
```diff
@@ -95,11 +95,11 @@ public function __construct(Core $core, Gradeable $gradeable, $details) {
         $this->setTaComment($details['ta_comment']);
         $this->setStudentComment($details['student_comment']);
         $this->setPoints($details);
-        $this->setText($details['text']);
-        $this->setPeerComponent($details['peer_component'] ?? false);
+        $this->setText(Utils::getBooleanValue($details['text']));
+        $this->setPeerComponent(Utils::getBooleanValue($details['peer_component'] ?? false));
```
Comment (IDzyre) [inline site/app/models/gradeable/Component.php]: I believe that you don't need the ?? false part now, as the getBooleanValue handles null values and returns false for them.

Comment (RyanStyron) [reply site/app/models/gradeable/Component.php]: Good catch -- will update.
