### PR TITLE
[Bugfix:InstructorUI] Preferred Names in Grader Assignment Tab

### LINKED ISSUE #7029: Instructor UI, specify grader access
**Describe the bug**
From the "Grader Assignment" tab, when matching TAs to rotating sections, we are currently displaying the TAs legal name.  This should be the TAs preferred name.

### PR DESCRIPTION
**Pull request by listeph**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Closes #7029
Currently "Grader Assignment" tab, when matching TAs to rotating sections, currently displays instructors, graders, TA's legal names
- before

### What is the new behavior?

Displays instructors, graders, TA's preferred names
- after

### Additional Information
- checked that the only files that use the result of this `getGradersByUserType()` function are `AdminGradeableController.php` → `AdminGradeableGraders.twig`, so I won't be changing display names elsewhere

### CODE REVIEW

**Review by loadedskiffer — APPROVED** [review]

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -2309,7 +2309,17 @@ public function getRotatingSectionsByGrader($gradeable_id) {
 
     public function getGradersByUserType() {
         $this->course_db->query(
-            "SELECT user_firstname, user_lastname, user_id, user_group FROM users WHERE user_group < 4 ORDER BY user_group, user_id ASC"
+            "SELECT 
+                (CASE WHEN user_preferred_firstname IS NOT NULL THEN user_preferred_firstname ELSE user_firstname END) as user_firstname,
+                (CASE WHEN user_preferred_lastname IS NOT NULL THEN user_preferred_lastname ELSE user_lastname END) as user_lastname,
```
Comment (MasterOdin) [inline site/app/libraries/database/DatabaseQueries.php:2314]: We probably also want to handle the case where `user_preferred_firstname` can be empty string?

Can do this using [`NULLIF`](https://www.postgresql.org/docs/13/functions-conditional.html#FUNCTIONS-NULLIF) function, and then also simplify the `CASE` with [`COALESCE `](https://www.postgresql.org/docs/13/functions-conditional.html#FUNCTIONS-COALESCE):

```suggestion
                COALESCE(NULLIF(user_preferred_firstname, ''), user_firstname) AS user_firstname,
                COALESCE(NULLIF(user_preferred_lastname, ''), user_lastname) AS user_lastname,
```

**Review by MasterOdin — CHANGES_REQUESTED** [review]

File: site/app/libraries/database/DatabaseQueries.php (hunk 1 above)
Comment (listeph) [reply site/app/libraries/database/DatabaseQueries.php]: That's smart, thank you!

**Review by MasterOdin — APPROVED** [review]
