### PR TITLE
[Bugfix:TAGrading] Peer grading ta and student notes shown

### LINKED ISSUE #6366: Peer Grading - Solution/TA Notes & Grade Inquiry
**Describe the bug**
The Solution/TA Notes panel displays both peer and non peer components are displayed to peers.

The non peer components should only be displayed to instructors & full/limited graders.

ALSO...  the Grade Inquiry panel should never be displayed to peer graders

### PR DESCRIPTION
**Pull request by HenrikLam**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Fixes #6366
Currently when peer grading is enabled for a gradable and there are both student components and ta components, a peer grader is able to see both the student components and the ta components in the solution/ta notes panel. In addition, peer graders have access to the grading inquiry panel through the grading inquiry button at the top. In the rubric panel, the peer grader and ta also sees both comments to the students and ta's.

### What is the new behavior?
The peer graders no longer sees the grading inquiry button, comments in the grading rubric panel now shows to different user groups accordingly. The peer graders also no longer sees ta components in the  solution/ta notes panel.

In TA's point of view 
image
where TA only is a TA component

In the peer grader's point of view for the same gradeable
image

### Other information?

I tested by created a non peer component for the gradeable Closed Peer Team Homework and assigning the user student to grade a team for the assignment and checking to see what the student has access to on their page, and then I did the same for the user ta2.

### CODE REVIEW

**Review by cjreed121 — APPROVED** [review]

**Review by MasterOdin — CHANGES_REQUESTED** [review]
Could you please do `git revert 4a3066e` so that this PR does not contain the change from #6411?

**Comment by HenrikLam** [comment]
> git revert 4a3066e

Reverted! Sorry about that.

File: site/public/js/gradeable.js [hunk 1]
```diff
@@ -195,10 +195,16 @@ function renderPeerGradeable(grader_id, gradeable, graded_gradeable, grading_dis
  * @param {boolean} componentVersionConflict
  * @returns {Promise<string>} the html for the graded component
  */
-function renderGradingComponent(grader_id, component, graded_component, grading_disabled, canVerifyGraders, precision, editable, showMarkList, componentVersionConflict) {
+function renderGradingComponent(grader_id, component, graded_component, grading_disabled, canVerifyGraders, precision, editable, showMarkList, componentVersionConflict, is_student) {
```
Comment (wusatosi) [inline site/public/js/gradeable.js:198]: There are too many arguments for this single function, consider refactor this function?

File: site/public/js/gradeable.js [hunk 2]
```diff
@@ -195,10 +195,16 @@ function renderPeerGradeable(grader_id, gradeable, graded_gradeable, grading_dis
  * @param {boolean} componentVersionConflict
```
Comment (wusatosi) [inline site/public/js/gradeable.js:195]: Missing the `is_student` parameter documentation

File: site/public/js/gradeable.js (hunk 1 above)
Comment (wusatosi) [reply site/public/js/gradeable.js:198]: Granted, this is hard to refactor. Maybe an attempt could be made?

**Review by wusatosi — CHANGES_REQUESTED** [review]
- Add the missing documentation for the new is_student parameter. 
- Try to play around with refactoring the `renderGradingComponent` function, reducing its number of arguments if possible.

File: site/public/js/gradeable.js (hunk 1 above)
Comment (HenrikLam) [reply site/public/js/gradeable.js:198]: I can fit precision, editable, showMarkList, and is_student into an array instead, but this might cause slight confusions for future developers, what do you think?

**Review by wusatosi — APPROVED** [review]
There appears to be no simple way to resolve the code style currently, the rest of the code looks good, in-code documentation has been updated.
