### PR TITLE
[Bugfix:Submission] Limit Leaderboard access

### LINKED ISSUE #11100: Leaderboard page should not be accessible if the gradeable is not accessible
**Describe the bug**
If an instructor needs to remove access to a gradeable -- they can edit the dates of the gradeable to remove it from view.
If a student had the URL bookmarked, but tries to access the URL they get a message:

REDACTED is not a valid electronic submission gradeable. Contact your instructor if you think this is an error.

If the gradeable has a leaderboard, unfortunately the leaderboard IS still visible.
If the student has the leaderboard URL bookmarked it is not blocked even though access to the gradeable is blocked.

**Expected behavior**
A student or TA who does not have access to the gradeable page, should not have access to the leaderboard either.

**To Reproduce**

The development course has a gradeable with a leaderboard. 
Should be able to reproduce by editing the dates in 'Edit Gradeable' then attempting to access pages as student user.
http://localhost:1511/courses/f24/development/gradeable/leaderboard

### PR DESCRIPTION
**Pull request by amRohitKumar**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Fixes #11100 

### What is the new behavior?
If the gradeable is not visible, the leaderboard will also not be visible.

image

### CODE REVIEW

**Review by williamjallen — CHANGES_REQUESTED** [review]
@amRohitKumar These changes seem reasonable to me, but it looks like the CI failed.  Can you fix those errors?  It would also be great if you could add a Cypress test to verify that this fix works, and continues to work in the future.

File: site/app/controllers/student/LeaderboardController.php [hunk 1]
```diff
@@ -19,6 +20,18 @@ public function getLeaderboard(string $gradeable_id, string $leaderboard_tag = n
             return new RedirectResponse($this->core->buildCourseUrl([]));
         }
 
+        if (
+            !$this->core->getUser()->accessGrading()
+            && (
+                !$gradeable->isSubmissionOpen()
+                || !$gradeable->isStudentView()
+                || $gradeable->isStudentViewAfterGrades()
+                && !$gradeable->isTaGradeReleased()
```
Comment (jeffrey-cordero) [inline site/app/controllers/student/LeaderboardController.php:29]: Leaderboard should still be visible to students with no TA grades to mimic an actual competition. I would look into making `tryGetElectronicGradeable` from `SubmissionController` into a shared method within the extending class `AbstractController`.

**Review by jeffrey-cordero — CHANGES_REQUESTED** [review]
The changes do seem to block students/TA's from seeing the future leaderboard, but when the submissions are open, neither account can access the gradeable.

**Review by jeffrey-cordero — APPROVED** [review]
The changes look solid. Leaderboard access is now restricted for future leaderboard assignments.

**Review by williamjallen — APPROVED** [review]
