### PR TITLE
[Bugfix:Submission] Blocked bulk upload when no grade access

### LINKED ISSUE #8802: Bulk upload allowed even when grading is not
**Describe the bug**
A grader can upload files even when they are not assigned to grade the assignment.

**Expected behavior**
When a grader is not assigned to grade an assignment they should not be able to upload 

**To Reproduce**
1. Create a new bulk upload gradeable 
2. Make sure in grader assignment the lowest privileged user is instructor 
3. Open the gradable to ta
4. From the ta account they will now have access to upload even though they are not able to grade

### PR DESCRIPTION
**Pull request by jason490**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #8802 
When the instructor sets the highest grade access to instructor only, the tas are able to upload bulk gradeables.

### What is the new behavior?
When the highest grading access is set to instructor only, the tas are not able to upload bulk gradeables

### CODE REVIEW

File: site/app/views/NavigationView.php [hunk 1]
```diff
@@ -515,7 +515,7 @@ public static function getSubmitButton(Core $core, Gradeable $gradeable, $graded
             if (!$gradeable->hasDueDate()) {
                 $date_text = "";
             }
-            if (!$gradeable->isStudentSubmit() && $core->getUser()->accessFullGrading()) {
+            if (!$gradeable->isStudentSubmit() && $core->getUser()->accessFullGrading() && $core->getUser()->getGroup() <= $gradeable->getMinGradingGroup()) {
```
Comment (shailpatels) [inline site/app/views/NavigationView.php:518]: The second part of the condition could also be checked with 
```
$this->core->getAccess()->canI("grading.electronic.grade", ["gradeable" => $gradeable]);
```

which is kind of the centralized way of making sure the same check is applied everywhere and runs the same getMinGradingGroup.

**Review by shailpatels — APPROVED** [review]
Changes correctly fix the issue as described, can make the change I commented above, but if this needs to be merged earlier I think it should be good

File: site/app/views/NavigationView.php (hunk 1 above)
Comment (jason490) [reply site/app/views/NavigationView.php:518]: I tried implementing that code by replacing the condition with the condition you showed me, and it seems like it created a php exception.

Comment (shailpatels) [reply site/app/views/NavigationView.php:518]: Oh it was probably due to the function being static and using the `$this` keyword

I think if you remove that and just start with $core like how the other functions do it, it should work?

Otherwise could you post the exception message

Comment (jason490) [reply site/app/views/NavigationView.php]: Yep, that solved the issue

File: site/app/views/submission/HomeworkView.php [hunk 2]
```diff
@@ -476,6 +476,7 @@ private function renderSubmitBox(Gradeable $gradeable, $graded_gradeable, $versi
             'show_no_late_submission_warning' => !$gradeable->isLateSubmissionAllowed() && ($gradeable->isSubmissionClosed() && !$gradeable->isTaGradeReleased()),
             // This is only used as a placeholder, so the who loads this page is the 'user' unless the
             //  client overrides the user
+            'bulk_upload_access' => $this->core->getUser()->getGroup() <= $gradeable->getMinGradingGroup(),
```
Comment (shailpatels) [inline site/app/views/submission/HomeworkView.php:479]: Should this check also be updated to `$this->core->getAccess()->canI("grading.electronic.grade", ["gradeable" => $gradeable]);`

**Review by shailpatels — CHANGES_REQUESTED** [review]

**Review by shailpatels — APPROVED** [review]
Retested after changes and works correctly
