### PR TITLE
Course materials date picker timezone handling

### LINKED ISSUE #4065: Course material release time is not time zone sensitive
**Describe the bug**
When clicking "now" in the course material page, the time is set with regard to my time zone, which may be different from the time zone of the server.

**Expected behavior**
No matter where I am, when I, as an instructor, sets a course material to be release now, students should be able to see them immediately.

**To Reproduce**
1. Change the time zone of your computer while Submitty is running in NY.
2. Login as instructor, set one file to be released "now".
3. Login as student. Can't see the file.

**Configuration**
 - OS: Linux
 - Browser Chrome

**Screenshots**

Note 15:26:34 in China === 03:26:34 in NY, and after I set "now" in China, I can't see the course material released as a student.

Instructor Side:
Screenshot from 2019-07-12 15-28-03

Student Side:
Screenshot from 2019-07-12 15-28-29

### PR DESCRIPTION
**Pull request by Kevin-MM**
Closes #4065

Address issues outlined in #4065.

**To Test**
- Set your PC timezone to the same time zone as the server. *This is default behavior for vagrant users in New York*
- Navigate to ```Course Materials```
- Upload some files and observe the behavior of the date time picker when using it
- Change your PC timezone to some timezone outside of server timezone
- Refresh the page
- Observe the behavior of the date time picker

### CODE REVIEW

**Comment by bmcutler** [comment]
@Kevin-MM 
Can you please add a screenshot of the two cases?  (matching & not matching timezone).
For dev documentation purposes.
thanks!

**Comment by Kevin-MM** [comment]
**In server timezone**
in_time_zone
**Outside of server timezone**
out_of_time_zone

File: site/app/libraries/DateUtils.php [hunk 1]
```diff
@@ -142,4 +142,25 @@ public static function parseDateTimeLong(string $date_time, $default_time_zone =
...
+     * Gets a json which contains the current server time broken up into specific fields
+     * Formatting the data in this manner makes it easier to work with when instantiating javascript Date() objects
+     *
+     * @param $core Application core
+     * @return object
+     */
+    public static function getServerTimeJson($core) {
+        $time = new \DateTime('now', $core->getConfig()->getTimezone());
+
+        $json = (object)[];
```
Comment (zjxiaohan) [inline site/app/libraries/DateUtils.php]: I am not sure why we have to use `$time->format('x')`-like code for multiple times.

If, for PHP code, put `$time->format("Y-m-j G:i:s")` and return it via JSON, you'll get things like `2019-07-18 1:01:02`, and it's good for JavaScript to accept such a string via `new Date('2019-07-18 1:01:02')`.

File: site/app/templates/course/CourseMaterials.twig [hunk 2]
```diff
@@ -316,6 +350,44 @@
         });
     }
 
+    function handleTimeZones() {
+
+        var url = buildUrl({'component': 'misc', 'page': 'get_server_time'});
+
+        $.ajax({
+            type: "POST",
```
Comment (zjxiaohan) [inline site/app/templates/course/CourseMaterials.twig]: Note that, although it doesn't hurt to use `POST` in this case, `POST` is generally considered to be creating/updating a resource.

The following content is from https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.3

The GET method means retrieve whatever information (in the form of an entity) is identified by the Request-URI. If the Request-URI refers to a data-producing process, it is the produced data which shall be returned as the entity in the response and not the source text of the process, unless that text happens to be the output of the process.

The POST method is used to request that the origin server accept the entity enclosed in the request as a new subordinate of the resource identified by the Request-URI in the Request-Line. POST is designed to allow a uniform method to cover the following functions:

      - Annotation of existing resources;
      - Posting a message to a bulletin board, newsgroup, mailing list,
        or similar group of articles;
      - Providing a block of data, such as the result of submitting a
        form, to a data-handling process;
      - Extending a database through an append operation.

File: site/app/libraries/DateUtils.php (hunk 1 above)
Comment (Kevin-MM) [reply site/app/libraries/DateUtils.php]: I believe this is a matter of opinion, but I prefer it this way because the data is more modular.  Having to work between PHP date time formats and javascript date time formats is a nightmare.  Plus if we want to reuse this function in the future maybe we aren't interested in a complete timestamp.  Perhaps on the client side we are only interested in the day of the month and don't want to have to instantiate a javascript Date() object just to get the day back out again.

File: site/app/controllers/MiscController.php [hunk 3]
```diff
@@ -41,9 +42,25 @@ public function run() {
...
+    /**
+     * Get the current server time
+     *
+     * Returns a json string which contains the current server time broken up into year, month, day, hour, minute,
+     * second
+     */
+    private function getServerTime() {
+
+        $json = DateUtils::getServerTimeJson($this->core);
+        $this->core->getOutput()->renderJson($json);
```
[the remark this answers is not in the document]
Comment (Kevin-MM) [reply site/app/controllers/MiscController.php]: Noted, I will leave as is until your revisit.

File: site/app/libraries/DateUtils.php (hunk 1 above)
Comment (zjxiaohan) [reply site/app/libraries/DateUtils.php]: Yeah that makes sense. True that we shouldn't be relying too much on the format consistency between PHP and JavaScript. Thanks for your explanation.

File: site/app/templates/course/CourseMaterials.twig (hunk 2 above)
Comment (Kevin-MM) [reply site/app/templates/course/CourseMaterials.twig]: Noted

File: site/app/libraries/DateUtils.php (hunk 1 above)
Comment (MasterOdin) [reply site/app/libraries/DateUtils.php]: It's also important to note that depending on your browser `new Date("datetime string")` gets rendered in different ways with regards to timezones compared to `new Date(year, month, day)`.
