### PR TITLE
[UI/UX:TAGrading] Fix spacing issue between panels

### LINKED ISSUE #6398: Margin for Right Panel is Too Large
**Describe the bug**
The horizontal drag bar is not centered between the two panes on the grading interface.  See below:
before

**Expected behavior**
The drag bar should be centered horizontally between the two panes.

### PR DESCRIPTION
**Pull request by williamjallen**
### What is the current behavior?
An extra margin is added when the TA grading interface is split into two panes.
before

### What is the new behavior?
Fixes the gap around the edges of the grading interface when split into two panes.
after

### Other information:
Fixes #6398

### CODE REVIEW

File: site/public/js/ta-grading.js [hunk 1]
```diff
@@ -406,7 +406,7 @@ function adjustGradingPanelHeader () {
   }
   // From the complete content remove the height occupied by navigation-bar and panel-header element
   // 6 is used for adding some space in the bottom
```
Comment (sbelsk) [inline site/public/js/ta-grading.js:408]: Would this comment not need to be modified or removed?

Comment (williamjallen) [reply site/public/js/ta-grading.js:408]: You are correct.  I had the change on my branch and then it got deleted amongst some other Git issues.

**Review by sbelsk — APPROVED** [review]
I tested this on Windows/Chrome and Firefox, and through the instructor, TA, and student peer grading UI. I noticed that the extra margin added is only in layout modes with a taller left, which the PR fixes. The page now looks alright in all of the cases I tested.
Chrome:
image

Firefox:
image
