### PR TITLE
[Bugfix:Submission] added breadcrumb to team page

### LINKED ISSUE #4852: Add to breadcrumbs, navbar with Manage Team
**Describe the bug**
When you press the manage team button there is no way to go back from the
navbar without first going back to the course selection page

**Expected behavior**
When you press the manage team button something should be added to the
top navbar similar to when a gradable is pressed

**To Reproduce**
1. Open class with team gradables
2. Select manage team
3. See error

**Configuration**
Should appear on any config, first noticed on
 - OS: Ubuntu 18.05
 - Browser Chrome

### PR DESCRIPTION
**Pull request by jenaybarela**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
fixes #4852

### CODE REVIEW

File: site/app/views/submission/TeamView.php [hunk 1]
```diff
@@ -21,6 +21,7 @@ public function showTeamPage(Gradeable $gradeable, $team, $teams, $lock, $users_
         $seekers = [];
         $invites_received = [];
         $seeking_partner = false;
+        $this->core->getOutput()->addBreadcrumb("Manage Team for {$gradeable->getTitle()}");
```
Comment (elihschiff) [inline site/app/views/submission/TeamView.php]: This looks good the only thing I would say is that the text already on the page says something like `Manage Team For: Open Team Homework` however the breadcrumb looks like `Manage Team for Open Team Homework` I think it makes more sense to change the `for` in your breadcrumb to `For:`

image

Comment (jenaybarela) [reply site/app/views/submission/TeamView.php]: I changed it to `Manage Team For: `
image
