### PR TITLE
[Bugfix:Submission] Prevent Grade Inquiry Text Across Pages

### LINKED ISSUE #11230: Grade inquiry text in local storage shows up for another class
**Describe the bug**

I wrote a grade inquiry for class A, but I didn't submit. 
Then few weeks later, I was trying to write grade inquiry for class B, and I see the text that I wrote for class A. 

Class A
스크린샷 2024-12-03 오후 10 05 05
I wrote inquiry for Problem1a, 1c, 1e

Class B
스크린샷 2024-12-03 오후 10 04 15
Insight into data sources and issues arising from the data, including FAIR and CARE -> shows inquiry problem 1a.
Insight into how far the technology is from deployment and what are the barriers -> shows problem 1c. 
Ability to answer questions -> shows problem 1e.

See the screenshot, 

**Expected behavior**

Texts from different classes should not be visible. 

**To Reproduce**
1. 
2. 
3. 

**Configuration**
 - OS: [e.g. Windows, Linux, ...]
 - Browser [e.g. Chrome, Safari]
Chrome, MacOS, M3. 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by jeffrey-cordero**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

When a user types into the text area within the grade inquiry section, the key is based on a component with the ID tied to the current gradable, which doesn't exist. Thus, the key is the same for all pages.

image

### What is the new behavior?

All draft content keys related to grade inquiry text areas are tied to the specific course and are gradable. This local storage instance is also cleared now for successful submissions.

image

### Other information?

Testing requires a gradable to have an open grade inquiry window, and any unsaved changes should not propagate to other locations now.

Fixes #11230

### CODE REVIEW

**Review by JManion32 — APPROVED** [review]
I was able to replicate the bug on main, and found that it no longer persists with this PR. Unfinished grade inquiries are now saved per gradeable, per course rather than for all gradeables, in all courses at once.

File: site/public/js/grade-inquiry.js [hunk 1]
```diff
@@ -1,9 +1,15 @@
 /* global buildCourseUrl, WebSocketClient */
 /* exported loadDraft, initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
 
+function getDraftContentKeyPrefix() {
+    const gradeable_id = window.gradeable_id;
+    const course = window.location.pathname.split('/').slice(2, 4).join('-');
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:6]: Splitting the course name manually seems pretty sketchy.  Why not just use the full URL (or a hash of it) as part of the key?

**Review by williamjallen — COMMENTED** [review]
Note that this is a question--feel free to push back if you think it's fine as-is.

File: site/app/templates/submission/homework/SubmitBox.twig [hunk 2]
```diff
@@ -399,6 +399,7 @@
     // set for all but vcs as it has no box submission
     window.num_submission_boxes = {{ is_vcs ? 0 : part_names | length }};
     window.gradeable_id = "{{ gradeable_id }}";
+    window.course_id = "{{ course_path|split('/')|slice(5,6)|join('-') }}";
```
Comment (williamjallen) [inline site/app/templates/submission/homework/SubmitBox.twig:402]: Why split it here though?  Can't you just directly query the course ID?

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/templates/submission/homework/SubmitBox.twig (hunk 2 above)
Comment (jeffrey-cordero) [reply site/app/templates/submission/homework/SubmitBox.twig]: I forgot about the server-side course configuration methods...

File: site/app/views/submission/HomeworkView.php [hunk 3]
```diff
@@ -560,7 +560,7 @@ private function renderSubmitBox(LateDays $late_days, Gradeable $gradeable, $gra
         $recent_version_url = $graded_gradeable ? $this->core->buildCourseUrl(['gradeable', $gradeable->getId()]) . '/' . $graded_gradeable->getAutoGradedGradeable()->getHighestVersion() : null;
         $numberUtils = new NumberUtils();
         return $output . $this->core->getOutput()->renderTwigTemplate('submission/homework/SubmitBox.twig', [
-            'course_path' => $this->core->getConfig()->getCoursePath(),
+            'course' => $this->core->getConfig()->getTerm() . '-' . $this->core->getConfig()->getCourse(),
```
Comment (williamjallen) [inline site/app/views/submission/HomeworkView.php:563]: that's...definitely not confusing at all...    Why not just pass the course and term separately? So the variable "course" actually contains a course name?

File: site/public/js/grade-inquiry.js [hunk 4]
```diff
@@ -118,6 +124,7 @@ function onGradeInquirySubmitClicked(button) {
             }
             else {
                 text_area.val('');
+                localStorage.removeItem(draftContentKeyPrefix);
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:127]: I'm a bit confused here.  You have a variable called `...prefix`, which is set to the result of a function named `...prefix`, and then you use it as the entire key here, right?  Are you missing something after the prefix the identify the particular text area?

Loosely related idea: instead of a function which returns the prefix, would it be better to have the function accept information about the particular box being used and return the full local storage key?

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/public/js/grade-inquiry.js (hunk 4 above)
Comment (jeffrey-cordero) [reply site/public/js/grade-inquiry.js]: Good call. I've refactored to ensure consistency across all the relevant localStorage keys.

**Review by williamjallen — APPROVED** [review]
The code looks good to me, but I'd like someone to do a functionality review here too.  @jeffrey-cordero, feel free to move this directly to "ready to merge" after that's complete.

**Review by JManion32 — APPROVED** [review]
Functionality still looks good
