### PR TITLE
[Bugfix:TAGrading] fix alert on disabled button

### LINKED ISSUE #11098: Disabled team buttons displaying wrong text
**Describe the bug**
The team button is disabled when the user has not made a team yet. However, the text on the submit gradeable, which is the disabled navigation button right next to it, says that "you must complete .". This is unintended behavior from the PR #10950 

**Expected behavior**
Either have the pre req be the complete the team select first, or make a new case condition for this bug

**To Reproduce**
1. Find a locked gradeable
2. Clicked the grayed out submission box
3. See error

**Screenshots**
image

### PR DESCRIPTION
**Pull request by subCode321**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

The `prerequisite` is not as expected for disabled buttons which require a user to be on a team first. It's empty and the message displayed is `Please complete .`

### What is the new behavior?
Fixes #11098 

The `prerequisite` is now fixed and the message displayed on such buttons is `You must be on a team to submit to this gradeable.`

image

### CODE REVIEW

**Comment by subCode321** [comment]
hi @williamschen23 , can I please get a review on this PR? Thank you!

**Review by IDzyre — CHANGES_REQUESTED** [review]
I don't know what the text should be (if we stay with the same alert system), but I think it should be something different than 'making a team', as you can join a team, make a team, etc. I would be in favor of adding a different message entirely for this case, as something like `You must be on a team to submit to this gradeable` sounds better than `Please complete making/joining a team`

**Comment by subCode321** [comment]
> I don't know what the text should be (if we stay with the same alert system), but I think it should be something different than 'making a team', as you can join a team, make a team, etc. I would be in favor of adding a different message entirely for this case, as something like `You must be on a team to submit to this gradeable` sounds better than `Please complete making/joining a team`

Sure, I've changed it

**Comment by subCode321** [comment]
The cypress tests failing are not related I believe

**Comment by subCode321** [comment]
@IDzyre do the changes look good to you?

**Comment by IDzyre** [comment]
Can you add to the cypress tests to verify the functionality?

**Comment by subCode321** [comment]
> Can you add to the cypress tests to verify the functionality?

done

**Comment by IDzyre** [comment]
Please don't @ contributors, we review it when we have time, and if we have interacted with a PR we already get notifications.

**Comment by himanish-star** [comment]
> Please don't @ contributors, we review it when we have time, and if we have interacted with a PR we already get notifications.

Ok

**Comment by subCode321** [comment]
> Please don't @ contributors, we review it when we have time, and if we have interacted with a PR we already get notifications.

ok 👍

**Comment by subCode321** [comment]
Do the changes look good to you, Cameron?

**Review by IDzyre — APPROVED** [review]
Changes look reasonable to me, cypress test added. Could use some more opinions on wording.

File: site/app/views/NavigationView.php [hunk 1]
```diff
@@ -437,6 +437,8 @@ public static function getSubmitButton(Core $core, Gradeable $gradeable, $graded
             ]);
         }
 
+        $prerequisite = 'Please complete ';
```
Comment (williamjallen) [inline site/app/views/NavigationView.php:440]: Compiling the full message text here feels like the wrong solution to me.  What do you think about moving this kind of logic to the Twig file?

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js [hunk 2]
```diff
@@ -170,6 +170,18 @@ describe('tests navigation buttons for each level of access', () => {
         );
         checkButtons('grades_released_lab', null, null);
     });
+
+    it('should show the correct alert message for team homework', () => {
+        cy.login('instructor');
```
Comment (williamjallen) [inline site/cypress/e2e/Cypress-UI/navigation_page.spec.js:175]: What do you think about testing all role levels instead of just instructor level users?

**Review by williamjallen — CHANGES_REQUESTED** [review]
Feel free to propose alternative solutions or add a rationale if you disagree with the comments I left--they aren't necessarily requested changes.  It would be helpful if you could improve the PR description documentation by adding more detailed before/after screenshots or screen recordings.

File: site/app/views/NavigationView.php (hunk 1 above)
Comment (subCode321) [reply site/app/views/NavigationView.php:440]: I can't have `Please complete` as a prefix inside the twig since the message changes completely for a gradable that requires a user to be on a submit, which is `""You must be on a team to submit to this gradeable"`

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js (hunk 2 above)
Comment (subCode321) [reply site/cypress/e2e/Cypress-UI/navigation_page.spec.js:175]: I can add for all role levels

Comment (subCode321) [reply site/cypress/e2e/Cypress-UI/navigation_page.spec.js:175]: > What do you think about testing all role levels instead of just instructor level users?

done.
image

File: site/app/views/NavigationView.php (hunk 1 above)
Comment (williamjallen) [reply site/app/views/NavigationView.php:440]: Why couldn't you use Twig to check if the prerequisite is null, and conditionally display that message if so?

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js (hunk 2 above)
Comment (williamjallen) [reply site/cypress/e2e/Cypress-UI/navigation_page.spec.js:175]: You could wrap this `it()` in a foreach to reduce duplication.  See [here](https://github.com/Submitty/Submitty/blob/4e9f55a2f4a9586e09986d6cd49842ba92ab9f9d/site/cypress/e2e/Cypress-Feature/grade_inquiries.spec.js#L33) for example.

**Review by williamjallen — CHANGES_REQUESTED** [review]
See responses to previous comments.

File: site/app/views/NavigationView.php (hunk 1 above)
Comment (subCode321) [reply site/app/views/NavigationView.php]: did the changes

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js (hunk 2 above)
Comment (subCode321) [reply site/cypress/e2e/Cypress-UI/navigation_page.spec.js]: done

**Comment by subCode321** [comment]
> See responses to previous comments.

changed the code as advised.

**Review by 04vmatsibekker — APPROVED** [review]

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js [hunk 3]
```diff
@@ -269,7 +281,7 @@ describe('navigation page', () => {
         validate_navigation_page_sections(sections);
     });
 
-    it('should show full access grader content for ta', () => {
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-UI/navigation_page.spec.js:272]: This change isn't really relevant

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js [hunk 4]
```diff
@@ -170,6 +170,18 @@ describe('tests navigation buttons for each level of access', () => {
         );
         checkButtons('grades_released_lab', null, null);
     });
+
+    ['instructor', 'ta', 'student'].forEach((user) => {
+        it(`should show the correct alert message for team homework in case of ${user}`, () => {
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-UI/navigation_page.spec.js:175]: I think something like this would sound better
```suggestion
        it(`should show the correct alert message for team homework for ${user}`, () => {
```

**Review by IDzyre — CHANGES_REQUESTED** [review]
Just a couple of small nitpicks about wording, and relevant changes, but the test looks good otherwise.

File: site/cypress/e2e/Cypress-UI/navigation_page.spec.js [hunk 5]
```diff
@@ -170,6 +170,18 @@ describe('tests navigation buttons for each level of access', () => {
         );
         checkButtons('grades_released_lab', null, null);
     });
+
+    ['instructor', 'ta', 'student'].forEach((user) => {
```
Comment (williamjallen) [inline site/cypress/e2e/Cypress-UI/navigation_page.spec.js:174]: You could add `grader` to this list for good measure.

**Review by IDzyre — APPROVED** [review]
Changes look good, verified test locally.

**Comment by williamjallen** [comment]
@subCode321 It looks like the JS lint test failed.  I have no further review comments and I'll approve once the CI is green.

**Comment by subCode321** [comment]
> @subCode321 It looks like the JS lint test failed. I have no further review comments and I'll approve once the CI is green.

done.

**Comment by subCode321** [comment]
@williamjallen sorry for pinging again, just wanted to ask if the changes look good to you.  Thank you!

**Comment by subCode321** [comment]
is the PR good to go?

**Review by williamjallen — APPROVED** [review]
Code looks good to me.  Apologies for the delay in getting this reviewed!
