### PR TITLE
[Bugfix:TAGrading] peer grader pdf permissions fix

### LINKED ISSUE #5234: Peer graders cannot view upload.pdf
**Describe the bug**

When an assigned peer clicks on upload.pdf (a bulk pdf) or perhaps any pdf(?)
they get a permission error.

This happens either when viewing within the submission frame or when using the "popout" to a separate window.

**Other notes**

The peer grader is able to download the zip of the assignment and the upload.pdf file is included.

The peer grader is able to view the names of the files in the results folder, but gets a permission error on all of those files.  Did we make a decision about whether any of these files were important for grading.  I'm not sure.  I think perhaps we should just be hiding all files in the results folder and not including them in the downloaded zip.

### PR DESCRIPTION
**Pull request by jchulton**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
A peer grader cannot view a pdf submitted by a peer they are assigned to grade (get a permissions error)
### What is the new behavior?
The peer grader can view the pdf. Closes #5234

### CODE REVIEW

File: site/app/controllers/pdf/PDFController.php [hunk 1]
```diff
@@ -66,7 +66,6 @@ public function showStudentPDF($gradeable_id, $filename, $path) {
     /**
      * @param $gradeable_id
      * @Route("/{_semester}/{_course}/gradeable/{gradeable_id}/pdf/annotations", methods={"POST"})
-     * @AccessControl(role="LIMITED_ACCESS_GRADER")
```
Comment (emaicus) [inline site/app/controllers/pdf/PDFController.php:69]: Since we are removing this, a check should be added below to make sure that the student id acquired by ```$user_id = $annotation_info['user_id'];``` is in our peer grading set.

Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php:69]: Added a check for peer assignments annotated by students that the student grader is a valid grader for the gradeable and student

File: site/app/controllers/pdf/PDFController.php [hunk 2]
```diff
@@ -114,7 +122,6 @@ public function savePDFAnnotation($gradeable_id) {
     /**
      * @param $gradeable_id
      * @Route("/{_semester}/{_course}/gradeable/{gradeable_id}/grading/pdf", methods={"POST"})
-     * @AccessControl(role="LIMITED_ACCESS_GRADER")
      */
     public function showGraderPDFEmbedded($gradeable_id) {
```
Comment (emaicus) [inline site/app/controllers/pdf/PDFController.php:126]: I think we need a permissions check inside this function as well.

File: site/app/controllers/pdf/PDFController.php [hunk 3]
```diff
@@ -75,11 +74,20 @@ public function savePDFAnnotation($gradeable_id) {
...
         $course_path = $this->core->getConfig()->getCoursePath();
         $user_id = $annotation_info['user_id'];
+        
 
         $gradeable = $this->tryGetGradeable($gradeable_id);
         if ($gradeable === false) {
             return false;
         }
+        
+        if ($gradeable->isPeerGrading() && $this->core->getQueries()->getUserById($grader_id)->getGroup() == 4) {
```
Comment (emaicus) [inline site/app/controllers/pdf/PDFController.php:84]: ```->getGroup() === 4```

Comment (MasterOdin) [reply site/app/controllers/pdf/PDFController.php:84]: `->getGroup() === User::GROUP_STUDENT`
