### PR TITLE
Fixes error message on Excused Absence Page

### LINKED ISSUE #1506: no error message / response when an invalid user is specified for extension
On the "excused absense extension" page, if you type in a user that does not exist, it just hangs.

Also please edit the text on this page to say extension not late day (3 instances).  late days can be used on any assignment (that allows them).  extensions only affect this one deadline.

### PR DESCRIPTION
**Pull request by andrewaikens87**
Previously there was no error message when trying to input a student that doesn't exist on the excused absence page. This resolves #1506.

### CODE REVIEW

File: site/public/js/server.js [hunk 1]
```diff
@@ -825,7 +825,14 @@ function updateHomeworkExtensions(data) {
...
         success: function(data) {
-            var json = JSON.parse(data);
+            //Will be a syntax error exception thrown if the user can't be found (<anonymous>)
+            try { 
+                var json = JSON.parse(data);
+            } catch(err){
+                var message ='<div class="inner-message alert alert-error" style="position: fixed;top: 40px;left: 50%;width: 40%;margin-left: -20%;" id="theid"><a class="fa fa-times message-close" onClick="removeMessagePopup(\'theid\');"></a><i class="fa fa-times-circle"></i>Invalid Student ID</div>';
+                $('#messages').append(message);
+                return;
+            }
```
Comment (MasterOdin) [inline site/public/js/server.js]: An invalid JSON object being returned by the endpoint should be fixed so that one a valid one (with a proper error message) is returned. JSON failing to parse should really only because the system threw an exception or something unexpected which causes invalid JSON (or returns an html page).

Comment (andrewaikens87) [reply site/public/js/server.js]: You are right. I pushed two commits to reflect these changes.

File: site/app/controllers/admin/LateController.php [hunk 2]
```diff
@@ -78,7 +78,8 @@ public function update($type) {
                 $this->core->getOutput()->renderJson(array('error' => $error));
                 return;
             }
-            if (!isset($_POST['user_id']) || $_POST['user_id'] == "" || $this->core->getQueries()->getUserById($_POST['user_id'])->getId() !== $_POST['user_id']) {
+            $user = $this->core->getQueries()->getSubmittyUser($_POST['user_id']);
+            if (!isset($_POST['user_id']) || $_POST['user_id'] == "" || is_null($user) || $user->getId() !== $_POST['user_id']) {
```
Comment (MasterOdin) [inline site/app/controllers/admin/LateController.php]: Use [empty()](http://php.net/manual/en/function.empty.php)
