### PR TITLE
[Bugfix:TAGrading] TA Grading Unexpanded View Fix

### LINKED ISSUE #12083: Display of selected marks should preview student view
**Describe the bug**
The TA grading view does not match the student view in the display of unselected marks.

An ungraded & unexpanded component in the TA grading interface looks like this:
Image

A graded component that is expanded within the TA grading interface looks like this:
Image

NOTE:  Blue marks will be displayed to students whether they are selected or not.  This is helpful when a problem is graded "by count up" to make it clear to the student what was required to get full credit.  The white marks will only be displayed to the student if the mark was selected by the TA as applying to their work.

Here's the graded & unexpanded view in the TA grading interface:  
THIS IS BUGGY!  It should not display unselected, non-display-to-all marks.
Image

Here's the student view:  
Image

**Expected behavior**
The graded unexpanded view of the component should preview what the student sees.

### PR DESCRIPTION
**Pull request by Rkoester47**
### Why is this Change Important & Necessary?
Fixes #12083 
Currently the TA grading view does not match the student view in terms of displaying unselected marks. The "display to all marks" and given marks should be displayed on collapse, but instead unselected, non-display-to-all marks are displayed upon clicking save.

### What is the New Behavior?
Now, when a TA grades a problem in an assignment and hits save, the problem should collapse to the unexpanded view. It will only display marks given to the student by the TA, as well as marks highlighted as display to all students (regardless of whether the mark is given).

Previous:
495359821-11cbe156-b7d0-44a7-9ead-6bd6b319c09d

Now:
image

### What steps should a reviewer take to reproduce or test the bug or new feature?
1.Sign in as TA
2. Go to Sample > Open VCS Homework Grading (or presumably any open grading assignment)
3. Begin grading a problem. Make sure that you first click "Edit gradeable" on the top right of the rubric, and highlight a few marks from a few problems as "show mark to all students"
4.  Grade the problems with a mix of checking off those blue marks, checking off no marks, checking off non-blue marks etc
5. Hit save on each problem and see if only the blue "show to all" marks remain, along with any marks you (TA) selected.
### Other information
This is not a breaking change.

### CODE REVIEW

**Comment by RyanStyron** [comment]
> The cache busting appears to have corrected the issue. Is it intended that the unexpanded view does not show the show-all rubric points when a section is not graded? Currently, none of the rubric messages show unless one has been selected.

Appears as though this is as desired, so I have approved the PR.

File: site/public/js/gradeable.js [hunk 1]
```diff
@@ -9,6 +9,7 @@
  */
 const DECIMAL_PRECISION = 3;
 
+const TEMPLATE_VERSION = '20251024';
```
Comment (williamjallen) [inline site/public/js/gradeable.js]: Hard-coding an ID like this is almost certainly not the right way to solve this problem.  Can you please clarify why you believe this is the correct approach?  If your goal is simply to solve the problem of needing to force refresh after a code change involving Twig.js, that is a separate longstanding issue which should be addressed via a separate PR.

**Comment by williamjallen** [comment]
Please also add a Cypress test which fails on main and passes on this branch to ensure this error does not occur again in the future.

File: site/public/js/gradeable.js (hunk 1 above)
Comment (Rkoester47) [reply site/public/js/gradeable.js]: Thank you for giving me feedback on this. I agree that hard-coding to solve the cache clearing problem was not the right way to go, and I have reverted those changes. As far as I can tell my original changes on this PR do seem to have resolved the initial issue of TA un-expanded grading view not matching the student view. It seems it just sometimes requires the user testing these changes to clear their cookies for the fix to take effect.

With that in mind, do you recommend I leave this PR as it is now and work on the Twig files needing a refresh issue in another PR? Or do you believe this PR still needs more work to make sure my original fix works on every device regardless of if the user hard-refreshes or clears their cookies?

Comment (williamjallen) [reply site/public/js/gradeable.js]: @Rkoester47 Any attempts to address the Twig caching issue should be done in a separate PR.  This PR should be good to go once you add a Cypress test.

**Comment by bmcutler** [comment]
merging this now.  @Rkoester47 will open an issue to add a test in a future PR.
