### PR TITLE
[Bugfix:Forum] Sync forum toggle text

### LINKED ISSUE #12477: Fix Discussion Forum show/hide thread attachments toggle text
**Describe the bug**
There are two toggles for Discussion Forum attachments, the "Attachments" button and the "More" button > "Show Attachments" dropdown item. When using both together, content may not be toggled correctly based on the text shown to the user and the current state of the content.

This is a common bug in programs that have multiple toggles for the same content. This should be fixed so that it works as intended and accurate text is shown to the user.

**Expected behavior**
Dropdown item text, specifically where the text changes based on the content current state ("Show Attachments" or "Hide Attachments"), should be updated on content toggle to reflect the accurate state of the content. This issue should also be fixed for all applicable contexts throughout Submitty.

**To Reproduce**
1. Open Submitty
2. Navigate to course with Discussion Forum
3. Navigate to course Discussion Forum
4. Open an existing thread with at least one attachment
5. Click the "More" button > "Show Attachments" dropdown item
6. Click the "Attachments" button
7. Click the "More" button
8. See error

**Configuration**
 - N/A; any; all

**Screenshots**

Bug

Image

No bug 1

Image

No bug 2

Image

No bug 3

Image

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Ash092016**
### Why is this Change Important & Necessary?
Fixes #12477. 

Currently, the global "Show/Hide Attachments" toggle in the discussion forum functions independently of the individual post "Attachments" buttons. If a user manually opens or closes attachments on a per-post basis, the global menu text and browser cookie become inaccurate (e.g., the menu might show "Show Attachments" even if the user has already manually opened all of them). This PR ensures the UI remains consistent by synchronizing the global state with individual actions.

### What is the New Behavior?
Every time an individual post's attachment is toggled, the page is scanned to check if any attachments are currently visible. The global "More" -> "Show/Hide Attachments" button text and the `show_forum_attachments` cookie are then updated to reflect the actual state of the page. 

- If at least one attachment is visible, the global button will say **"Hide attachments"**.
- If all attachments are closed, the global button will say **"Show attachments"**.

### What steps should a reviewer take to reproduce or test the bug or new feature?
1. Open a forum thread that has multiple posts with attachments.
2. Click the **"More"** button and observe the state (default is usually "Show attachments").
3. Manually click the **"Attachments"** button on an individual post to show its images.
4. Open the **"More"** dropdown again; it should now automatically say **"Hide attachments"**.
5. Manually hide that post's attachments. The **"More"** dropdown should now revert to saying **"Show attachments"**.

### Automated Testing & Documentation
This is a client-side UI synchronization fix. It has been manually verified to ensure correctly functioning toggles and accurate cookie state updates. No changes to documentation or new automated tests were required for this specific UI patch.

### Other information
- **Breaking Change-** No.
- **Migrations-** No.
- **Security Concerns-** None.

### CODE REVIEW

**Comment by Ash092016** [comment]
Hi @roye2, I have updated the branch with the requested changes. A new review is required to verify the fixes and to check if the previous CI failures persist.

Regarding the failure in late_submission_warning_messages.spec.js (Cypress Gradeable tests), it appears to be unrelated to my forum changes, as it specifically involves late day calculations. Once the review is complete, we can confirm if this was an intermittent failure or a separate issue.

**Comment by Ash092016** [comment]
Hi @roye2 ,  I checked the logic and it looks like the backend is already sending the correct total through {{total_attachments }} in ForumBar.twig.

The issue is actually in forum.js. Inside showAttachmentsOnload(), there's a line that manually overwrites the badge text with $('.attachment-btn').length. Since that only counts what’s currently rendered, it messes up the global total.

If I just pull out this line, it should stay synced with the backend value:
$('#toggle-attachments-button').find('.attachment-badge').text($('.attachment-btn').length);

Should I go ahead and include that fix in this PR, or would you prefer it in a separate one?

**Comment by roye2** [comment]
@Ash092016 It is fine with me if you add that change to this PR as well, it seems like it is still sort of in the scope of the main issue. I will run the tests once you've done that. The cypress Gradeable test is flaky, there is a PR about a fix currently as far as I am aware :)

**Comment by Ash092016** [comment]
Hi @roye2 , I've just pushed the fix for the attachment badge count. It now relies on the backend value from the template and won't be overwritten by the JS count anymore.

**Comment by Ash092016** [comment]
Hi @roye2, thank you for the detailed feedback!
You're absolutely right—the current count is tied to the backend rendering process, which makes it "context-sensitive" (only counting what's on the page) rather than truly global. I agree that making this count globally accurate while respecting all permission checks is a more complex task than originally anticipated.
I'll look into addressing the global attachment count in a separate, dedicated PR so we can handle the database logic properly there. Looking forward to your approval on this one!

File: site/public/js/forum.js [hunk 1]
```diff
@@ -2125,7 +2125,14 @@ function showAttachmentsOnload() {
     else {
         $('#toggle-attachments-button').find('.status').text('Show attachments');
     }
-    $('#toggle-attachments-button').find('.attachment-badge').text($('.attachment-btn').length);
```
Comment (roye2) [inline site/public/js/forum.js:2128]: revert this change please.

**Comment by Ash092016** [comment]
Hi @roye2 , I have revert the changes and have added the same!

**Review by roye2 — APPROVED** [review]
