### PR TITLE
[Bugfix:Submission] Improve daylight savings warning banner

### LINKED ISSUE #10598: Improve Daylight Savings Tests
**What problem are you trying to solve with Submitty**

The cypress tests introduced by #10448 (Warning Message Daylight Savings Time) will only test the warning message plus-or-minus 7 days from the start or end of daylight savings. They should be updated to test the message year-round.

### LINKED ISSUE #10682: Daylight Saving Functionality
**Describe the bug**
Right now, the daylight savings banner appears during the entire week of daylight savings, even if the gradeable is not active during the daylight saving period. 

**Expected behavior**
Daylight savings banner should only appear on Gradeables that are impacted and when the due date is due. 

**To Reproduce**
1. Pretend its daylight savings {% set daylight = true %}
2. See the banner
3. See a gradeable that has already been graded and released. 

**Configuration**
 - OS: Mac
 - Browser Chrome

Was talked about in 7/9/24 meeting
#10448

### PR DESCRIPTION
**Pull request by williamschen23**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Closes #10682  and closes #10598. Currently the daylight savings banner is displayed way too much, 1 week before daylight savings and one week after daylight savings.

### What is the new behavior?
This PR addresses the display of the daylight savings banner, with it using late days to calculate when they should show the banner. It also aims to improve the current cypress checks for late days.

### Other information?
For the people reviewing:
There are a lot of conditions because of confusing late day numbers such as 150 and 250, where it could escape daylight savings and then walk back into daylight savings, making PHP say there is no daylight saving that occured. 
Because it is confusing to test 150 and 250, they are not included in the cypress tests.

Cypress:
I tested 2024-03-09 (daylight savings is 3-10) at 0:00, 1:59, and 2:01 manually and it worked exactly as intended. 1:59 should not display a banner for 1 late day because it is before the daylight change, same with 0:00. 2:01 should trigger the banner, which it does.

### CODE REVIEW

**Review by powe97 — APPROVED** [review]
Looks good. I think the current banner text
> WARNING: Daylight savings is THIS WEEK! Please note that a late day is 24 HOURS.
>
> This means that if an assignment is due at 10 pm a day BEFORE daylight savings in the spring, and you plan to use a late day, you must submit your assignment before 9 pm.
>
> As for when an assignment is due at 10 pm a day AFTER daylight savings ends in the fall, you must submit your assignment by 11 pm.

is a bit unnecessarily verbose, but since that was not added in this PR, I'll approve.

File: site/app/views/submission/HomeworkView.php [hunk 1]
```diff
@@ -197,14 +197,37 @@ public function renderLateDayMessage(LateDays $late_days, Gradeable $gradeable,
...
+        if ($today > $due_date_with_late_days) {
+            $daylight_message_required = false;
+        }
+        elseif ($late_days_allowed <= 365) {
+            $future_due_date = clone $due_date;
+            $daylight_message_required = false;
+            // check every interval of 100
+            for ($i = 0; $i < intdiv($late_days_allowed, 100) && !$daylight_message_required; $i += 1) {
+                $future_due_date->modify('+100 days');
+                $daylight_message_required = $future_due_date->format('I') !== $due_date->format('I');
```
Comment (ziesski) [inline site/app/views/submission/HomeworkView.php:218]: How about we leave some comment here?
```suggestion
                //  The format specifier 'I' is used to extract a single character representing the DST indicator for the date. This will be either a '0' (DST not in effect) or a '1' (DST in effect).
                $daylight_message_required = $future_due_date->format('I') !== $due_date->format('I');
```

**Review by ziesski — APPROVED** [review]
I reviewed the code, and logic seems reasonable. 
I cannot comment on the cypress code tho. 
Also some suggestions are made, but is optional.

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 2]
```diff
@@ -29,9 +29,20 @@ const getRandomGradeableName = () => {
     }
     return randomString;
 };
+const makeNonTeamGradeable = (gradeableName) => {
+    cy.login('instructor');
+    cy.visit(['sample', 'gradeable']);
+    // Enter gradeable info
+    cy.get('#g_title').type(gradeableName);
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:36]: Can you use testids for elements touched in this test?

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 3]
```diff
@@ -29,9 +29,20 @@ const getRandomGradeableName = () => {
...
+    cy.get('#g_id').type(gradeableName);
+    cy.get('#radio_ef_student_upload').check().click();
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:38]: This is counter intuitive, as .check acts the same as .click but is used for checkboxes.

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 4]
```diff
@@ -118,43 +129,82 @@ const SubmitAndCheckMessage = (gradeable_type, upload_file1, invalid_late_day, v
...
+        calculateAndCheckDaylightBanner(99);
+    });
+
+    it('Testing if Daylight savings banner should appear for 100 late day', () => {
+        calculateAndCheckDaylightBanner(100);
+    });
+
+    it('Testing if Daylight savings banner should appear for 101 late day', () => {
+        calculateAndCheckDaylightBanner(101);
+    });
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:202]: These could probably be combined into one test

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 5]
```diff
@@ -118,43 +129,82 @@ const SubmitAndCheckMessage = (gradeable_type, upload_file1, invalid_late_day, v
...
-    const currentDate = new Date();
-    const futureDate = new Date(currentDate);
-    futureDate.setDate(currentDate.getDate() + 7);
+const checkDaylightBanner = (late_days, existence) => {
+    cy.login('instructor');
+    cy.visit(['sample', 'gradeable', daylight_gradeable, 'update?nav_tab=5']);
+    cy.get('#late_days')
+        .clear()
+        .type(late_days)
+        .type('{enter}');
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:138]: This along with a lot of the chained .type and .clear commands will be linted in a one of Dorian's PRs, and it will fail. You should make this not chained to not add more work to that PR.

**Review by IDzyre — CHANGES_REQUESTED** [review]

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js (hunk 3 above)
Comment (williamschen23) [reply site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:38]: Only using .check or .click does not work for me. You need to use check with force:true in order to check to work. It is up to you to see which one is better.

File: site/app/templates/admin/users/MoreExtensions.twig [hunk 6]
```diff
@@ -17,5 +17,5 @@
 {% block close_button_text %}No{% endblock %}
 {% block buttons %}
     {{ block('close_button') }}
-    <a class="btn btn-primary" id="apply-to-all" href="javascript:confirmExtension(1)">Yes</a>
+    <a class="btn btn-primary" id="apply-to-all" data-testid='more-extension-apply-to-all' href="javascript:confirmExtension(1)">Yes</a>
```
Comment (IDzyre) [inline site/app/templates/admin/users/MoreExtensions.twig:20]:
```suggestion
    <a class="btn btn-primary" id="apply-to-all" data-testid="more-extension-apply-to-all" href="javascript:confirmExtension(1)">Yes</a>
```

I don't think that his matters in a syntax point of view, just a consistency point of view

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 7]
```diff
@@ -29,36 +29,47 @@ const getRandomGradeableName = () => {
     }
     return randomString;
 };
+const makeNonTeamGradeable = (gradeableName) => {
+    cy.login('instructor');
+    cy.visit(['sample', 'gradeable']);
+    // Enter gradeable info
+    cy.get('[data-testid=create-gradeable-title]').type(gradeableName);
+    cy.get('[data-testid=create-gradeable-id]').type(gradeableName);
+    cy.get('[data-testid=radio-student-upload]').check({ force: true });
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:38]: Is there a way to do this without force clicking?

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 8]
```diff
@@ -118,66 +129,89 @@ const SubmitAndCheckMessage = (gradeable_type, upload_file1, invalid_late_day, v
...
-it('Checks whether daylight savings warning message should be appearing at current date.', () => {
-    /*
-    First we set the date to a date close to the spring daylight savings time and then check that the message appears.
-    Then we change the date to a month later, and check that the "daylight" message doesn't appear.
-    */
-    const currentDate = new Date();
-    const futureDate = new Date(currentDate);
-    futureDate.setDate(currentDate.getDate() + 7);
+const checkDaylightBanner = (late_days, existence) => {
+    cy.login('instructor');
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:133]: I don't think that you should have to log out and log back in each time you run this, you could just login before all of them, and then let the global after each logout at the end

**Review by IDzyre — CHANGES_REQUESTED** [review]

File: site/app/templates/admin/users/MoreExtensions.twig (hunk 6 above)
Comment (williamschen23) [reply site/app/templates/admin/users/MoreExtensions.twig:20]: I noticed that there were a couple of places where we used example_test_id and some places where we used example-test-id

out of consistency which ones better?

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js (hunk 7 above)
Comment (williamschen23) [reply site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:38]: it says DOM element is not visible despite it being clearly visible

File: site/app/templates/admin/users/MoreExtensions.twig (hunk 6 above)
Comment (IDzyre) [reply site/app/templates/admin/users/MoreExtensions.twig:20]: Originally we just did whatever, but I am trying to encourage using example-test-id to be consistent.

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js (hunk 7 above)
Comment (IDzyre) [reply site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:38]: When testing locally it wouldn't check the button without force. Could you add a comment above it saying 'force is currently necessary to ensure the radio button is checked' or something similar, so when people come along later and try and remove force clicks, they know why this one is here?

Comment (williamschen23) [reply site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:38]: There are many situations in this file wherewe use .check() and then .click(), which works. Would you want all the test to refactor using a single check and then force?

Comment (IDzyre) [reply site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:39]: I think leaving them for now is fine, Ideally we wouldn't force click (most things), but I think leaving this one is fine, and maybe later on when someone tries to remove all force clicks, they'll change it to check then click.

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 9]
```diff
@@ -118,66 +130,95 @@ const SubmitAndCheckMessage = (gradeable_type, upload_file1, invalid_late_day, v
...
-    }
-    cy.logout();
+describe('Checks whether daylight savings warning message should be appearing given varying amounts of late days.', () => {
+    it('should create non-team gradeable for testing daylight savings', () => {
+        makeNonTeamGradeable(daylight_gradeable);
+
+        const date = new Date().toISOString();
+        // change all the due dates to today
+        changeAllDates(daylight_gradeable, date);
+    });
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:174]: This should be in a before block, not in a separate it block ideally.

File: site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js [hunk 10]
```diff
@@ -118,66 +130,95 @@ const SubmitAndCheckMessage = (gradeable_type, upload_file1, invalid_late_day, v
...
-        cy.get('#save_status', { timeout: 20000 }).should('have.text', 'All Changes Saved');
+        cy.get('[data-testid=ta-view-start-date]').clear();
+        cy.get('[data-testid=ta-view-start-date]').type('1992-06-15');
+        cy.get('[data-testid=ta-view-start-date]').type('{enter}');
+        cy.get('[data-testid=save-status]', { timeout: 20000 }).should('have.text', 'All Changes Saved');
+        cy.get('[data-testid=submission-open-date]').clear();
+        cy.get('[data-testid=submission-open-date]').type('2004-12-18');
+        cy.get('[data-testid=submission-open-date]').type('{enter}');
+        cy.get('[data-testid=save-status]', { timeout: 20000 }).should('have.text', 'All Changes Saved');
     });
```
Comment (IDzyre) [inline site/cypress/e2e/Cypress-Gradeable/late_submission_warning_messages.spec.js:212]: Same comment above about this could (and should) probably be in a before block, but since this part of the PR is just changing to testids and linting, this one could be done in a future PR

**Review by IDzyre — CHANGES_REQUESTED** [review]
One small comment about using a before block instead of an it block, but after that the testing additions and changes look good.

**Review by ziesski — APPROVED** [review]

**Review by IDzyre — APPROVED** [review]
Testing changes look good.
