### PR TITLE
[Bugfix:TAGrading] allow removal of empty text items

### LINKED ISSUE #11216: Unable to remove empty text items when editing lab
**Describe the bug**

When users created two text items, then write into one of them, they will not be able to remove the empty one with the warning shown in the video.

https://github.com/user-attachments/assets/a5d0540f-15bb-4132-bf5b-50a8f3b5848c

**Expected behavior**
Users should be able to remove empty text items.

### PR DESCRIPTION
**Pull request by Troy-bailan-King**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Closes #11216 

https://github.com/user-attachments/assets/17eabd7d-d527-475a-8c58-742399f59026

### What is the new behavior?

https://github.com/user-attachments/assets/901e129c-964d-4cce-8a6f-90ce57e5871f

### Other information?

### CODE REVIEW

File: site/app/controllers/grading/SimpleGraderController.php [hunk 1]
```diff
@@ -249,31 +249,30 @@ public function save($gradeable_id) {
 
             $component_grade = $ta_graded_gradeable->getOrCreateGradedComponent($component, $grader, true);
             $component_grade->setGrader($grader);
-
+            if ($data === '' || $data === "0") {
```
Comment (jeffrey-cordero) [inline site/app/controllers/grading/SimpleGraderController.php:252]: What if `$data` being zero is a valid option for a gradable? One edge case is if the component is text based. In the following, "0" is never saved, which is technically is valid value.

image

Comment (Troy-bailan-King) [reply site/app/controllers/grading/SimpleGraderController.php:252]: This happens because the score section is automatically initialized with a default value of “0” when a new gradable is created. The checks for points and notes are currently handled together. Perhaps I could modify the behavior so that no value is assigned to the score during creation?

File: site/app/libraries/database/DatabaseQueries.php [hunk 2]
```diff
@@ -9426,4 +9426,18 @@ public function removeDockerImageOwner(string $image, User $user): bool {
         }
         return $this->submitty_db->getRowCount() > 0;
     }
+
+    /**
+     * @param GradedComponent $graded_component The graded component to delete.
+     */
+    public function deleteGrade(GradedComponent $graded_component): void {
```
Comment (jeffrey-cordero) [inline site/app/libraries/database/DatabaseQueries.php:9433]: This is essentially a copy of `deleteGradedComponent()` within the same query file. You can simply call in the controller method it via `$ta_graded_gradeable->deleteGradedComponent($component);`

File: site/app/controllers/grading/SimpleGraderController.php [hunk 3]
```diff
@@ -249,31 +249,35 @@ public function save($gradeable_id) {
...
+                if ($data === '') {
+                    // If the component is empty, delete it
+                    $ta_graded_gradeable->deleteGradedComponent($component);
+                    continue;
+                }
                 $component_grade->setComment($data);
             }
             else {
+                if ($data === '' || $data === '0') {
+                    // If the component is empty, delete it
```
Comment (jeffrey-cordero) [inline site/app/controllers/grading/SimpleGraderController.php:262]: This can probably be moved into the same if statement (`$data === '' || !$component->isText() && $data === '0'`)

**Review by jeffrey-cordero — CHANGES_REQUESTED** [review]
This seems to fix the issue, as instructors can now reduce total components. I also suggested refactoring the component removal for simplicity. A future task could be asking instructors if they wish to remove all graded components directly for specific column(s).

**Review by ZheyuDeng — CHANGES_REQUESTED** [review]
Small thing when numerical value entered is bigger than upper clamp the warning stop showing. Instead it is just refreshed with default value. 

https://github.com/user-attachments/assets/2e86cf1b-4b03-4041-a8c6-7afc615a987e

**Review by zacharymnp — CHANGES_REQUESTED** [review]
Ideally, the PR should be renamed to describe the change rather than the issue, e.g. 'allow removal of empty text items'.

There are a few other very minor changes that I would recommend.

**Review by ZheyuDeng — APPROVED** [review]
Tested and it fixed the bug I mentioned earlier!

**Review by zacharymnp — APPROVED** [review]
Changes seem reasonable.
