### PR TITLE
[Bugfix:InstructorUI] Notify on Self Registration

### LINKED ISSUE #11434: Self-registration email notification sent to extra instructors
**Describe the bug**
I believe we have a logic bug when creating the list of instructor users who should be notified when a student self-registers for a course.

We should only be sending email to users who are in the instructor group for the course with matching course id and matching term.

However, I am receiving duplicate 'new student X self-registered for course Y' notification emails to both my primary email address (which is linked to my primary submitty account) and also to my secondary email address (that is linked to my secondary user.  My primary user is in the instructor group for course Y.  The secondary user is only in the student group for course Y.  The secondary user has been an instructor user for other courses.  And the secondary user has been in a course in a prior term that has the same course code as course Y.  So maybe this is a similar bug to a previous issue and we just need to add the term into the select query.

These duplicate notifications only started when I self-registered the secondary user to the course.  And I checked, and the secondary user is just a student user in the course.

### PR DESCRIPTION
**Pull request by IDzyre**
### What is the current behavior?
Currently all instructors in Submitty are receiving emails when a user self registers for a course. This is because the function used is just getting all of a certain type of user. 
Closes #11434 
### What is the new behavior?
This function has two more parameters added, allowing for the ability to specify if you want that group for a specific course and term. 

### Other information?
This changes the SelfRejoin function as well, as that is supposed to notify the instructors of that given course, not all instructors of Submitty.
The original use of this function remains unchanged, as `term` and `course` are optional parameters, and the query defaults to being the same query as before.

### CODE REVIEW

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -1168,11 +1168,13 @@ public function getActiveUserIds(bool $instructor, bool $fullAccess, bool $limit
...
             $extra_where = ' OR users.user_access_level <= 2';
         }
+        $terms = ($term === '' ? 'courses.term' : "'$term'");
+        $courses = ($course === '' ? 'courses.course' : "'$course'");
         $result_rows = [];
         $this->submitty_db->query(
             "SELECT DISTINCT courses_users.user_id as user_id
                 FROM courses_users INNER JOIN courses
-                ON courses_users.term = courses.term AND courses_users.course = courses.course
+                ON courses_users.term = " . $terms . " AND courses_users.course = " . $courses . "
```
Comment (williamjallen) [inline site/app/libraries/database/DatabaseQueries.php:1177]: This seems like a pretty clear opportunity for a SQL injection in the future.  It would be better to use a prepared statement for text which isn't static.

**Review by williamjallen — CHANGES_REQUESTED** [review]

**Comment by bmcutler** [comment]
I found a bug while testing this PR:
https://github.com/Submitty/Submitty/issues/11471

**Review by bmcutler — APPROVED** [review]
I tested this on a brand new course that I set to self-registration and confirmed the bug existed on main and is fixed in this branch.

However, in addition to the bug I found and reported in issue
https://github.com/Submitty/Submitty/issues/11471

I somehow 'broke' my 'testing' course, so that no one is able to self-register.  I don't know what happened and I'm not sure how to reproduce so I'll let that slide for now.  My new course seems ok.

**Comment by bmcutler** [comment]
@williamjallen please confirm that your requested changes are complete regarding the SQL injection

File: site/app/libraries/database/DatabaseQueries.php [hunk 2]
```diff
@@ -1168,13 +1168,16 @@ public function getActiveUserIds(bool $instructor, bool $fullAccess, bool $limit
...
+        $courses = ($course === '' ? 'courses.course' : $course);
         $result_rows = [];
         $this->submitty_db->query(
             "SELECT DISTINCT courses_users.user_id as user_id
                 FROM courses_users INNER JOIN courses
-                ON courses_users.term = courses.term AND courses_users.course = courses.course
+                ON courses_users.term = ? AND courses_users.course = ? 
                 " . $extra_join . "
-                WHERE courses.status = 1 AND user_group IN (" . implode(', ', $args) . ")" . $extra_where
+                WHERE courses.status = 1 AND user_group IN (" . implode(', ', $args) . ")" . $extra_where,
```
Comment (williamjallen) [inline site/app/libraries/database/DatabaseQueries.php:1179]: It would be better to use `createParameterList()` here to prevent potential SQL injections if the args ever become user controlled in the future.

File: site/app/libraries/database/DatabaseQueries.php [hunk 3]
```diff
@@ -1168,13 +1168,16 @@ public function getActiveUserIds(bool $instructor, bool $fullAccess, bool $limit
...
             $extra_where = ' OR users.user_access_level <= 2';
         }
+        $terms = ($term === '' ? 'courses.term' : $term);
+        $courses = ($course === '' ? 'courses.course' : $course);
         $result_rows = [];
         $this->submitty_db->query(
             "SELECT DISTINCT courses_users.user_id as user_id
                 FROM courses_users INNER JOIN courses
-                ON courses_users.term = courses.term AND courses_users.course = courses.course
+                ON courses_users.term = ? AND courses_users.course = ?
```
Comment (williamjallen) [inline site/app/libraries/database/DatabaseQueries.php:1177]: This doesn't seem right to me.  Right now, the prepared statement means that this will perform the comparison `courses_users.term = 'courses.term'` if there is no term, when you presumably mean `courses_users.term = courses.term` as originally written.  You could instead move the logic entirely into the SQL query, or conditionally insert `courses.term` or `?`, depending on whether the term was empty.

File: site/app/libraries/database/DatabaseQueries.php [hunk 4]
```diff
@@ -1147,7 +1147,7 @@ public function getGroupForUserInClass($semester, $course_name, $user_id) {
      * @param bool $faculty to include faculty level users or not
      * @return array - array of userids active in the specified semester
      */
-    public function getActiveUserIds(bool $instructor, bool $fullAccess, bool $limitedAccess, bool $student, bool $faculty): array {
+    public function getActiveUserIds(bool $instructor, bool $fullAccess, bool $limitedAccess, bool $student, bool $faculty, string $term = '', string $course = ''): array {
```
Comment (williamjallen) [inline site/app/libraries/database/DatabaseQueries.php:1150]: Would it be better to make these nullable, and default to null if not provided?

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/controllers/course/CourseRegistrationController.php [hunk 5]
```diff
@@ -48,7 +48,7 @@ public function registerCourseUser(string $term, string $course): void {
         $default_section = $this->core->getQueries()->getDefaultRegistrationSection($term, $course);
         $this->core->getUser()->setRegistrationSection($default_section);
         $this->core->getQueries()->insertCourseUser($this->core->getUser(), $term, $course);
-        $instructor_ids = $this->core->getQueries()->getActiveUserIds(true, false, false, false, false);
+        $instructor_ids = $this->core->getQueries()->getActiveUserIds(true, false, false, false, false, term: $term, course: $course);
```
Comment (williamjallen) [inline site/app/controllers/course/CourseRegistrationController.php:51]: I'm generally not a fan of named parameters in PHP.  Doing this means that future changes to the internal implementation details of `getActiveUserIds()` (i.e., the parameter names) will require developers to edit every callsite where this is used.  Instead, I think the variable names `$term` and `$course` are descriptive enough.  I'm open to other opinions on this though.  Thoughts?

File: site/app/controllers/SelfRejoinController.php [hunk 6]
```diff
@@ -215,7 +215,7 @@ private function sendRejoinedStudentEmail($joined_section): void {
             you may move the student to the Null section.
         EMAIL;
 
-        $instructor_ids = $this->core->getQueries()->getActiveUserIds(true, false, false, false, false);
+        $instructor_ids = $this->core->getQueries()->getActiveUserIds(true, false, false, false, false, term: $term, course: $course);
```
Comment (williamjallen) [inline site/app/controllers/SelfRejoinController.php:218]: Same here.

**Review by williamjallen — COMMENTED** [review]
One more stylistic comment, otherwise no more comments.  The real changes look good.

**Review by williamjallen — APPROVED** [review]
