### PR TITLE
[Bugfix:Notifications] Secondary email notification fix

### LINKED ISSUE #7959: Secondary email address notifications can be set on even if there is no secondary email
**Describe the bug**
"Send Email to Secondary Address" can be set to true in the user profile even if secondary email address is empty, this is something that UI prevents from happening but a crafted request can lead to this unexpected behavior. 

**Expected behavior**
Trying to set secondary email notifications on with an empty secondary email address should throw an error.

**To Reproduce**
1. Craft a request similar to this:
Submitty-bug

### PR DESCRIPTION
**Pull request by akshatbatra**
### What is the current behavior?
Fixes #7959 
"Send Email to Secondary Address" can be set to true in the user profile even if secondary email address is empty, this is something that UI prevents from happening but a crafted request can lead to this unexpected behavior.

### What is the new behavior?
Doing so now results in error "Secondary email can't be empty if secondary email notify is true".

### CODE REVIEW

File: site/app/controllers/UserProfileController.php [hunk 1]
```diff
@@ -176,8 +176,7 @@ public function changeSecondaryEmail(): JsonResponse {
         if (isset($_POST['secondary_email']) && isset($_POST['secondary_email_notify'])) {
             $secondaryEmail = trim($_POST['secondary_email']);
             $secondaryEmailNotify = trim($_POST['secondary_email_notify']) === "true";
-
-            if ((!$secondaryEmailNotify && $secondaryEmail == "") || $user->validateUserData('user_email_secondary', $secondaryEmail) === true) {
+            if (((!$secondaryEmailNotify && $secondaryEmail == "")) || (($user->validateUserData('user_email_secondary', $secondaryEmail) === true) && !($secondaryEmail == ""))) {
```
Comment (williamjallen) [inline site/app/controllers/UserProfileController.php:179]: This could be simplified a bit:
```suggestion
            if ((!$secondaryEmailNotify && $secondaryEmail === "") || ($secondaryEmail !== "" && $user->validateUserData('user_email_secondary', $secondaryEmail) === true)) {
```

**Review by williamjallen — CHANGES_REQUESTED** [review]

**Comment by akshatbatra** [comment]
Thanks @cjreed121 and @williamjallen for changes.

**Review by cjreed121 — APPROVED** [review]
