### PR TITLE
[Bugfix:Submission] Fix Team N+1 queries

### LINKED ISSUE #12505: [Server] Batch user lookups in TeamController
## Description

In `TeamController::showPage()`, the method `getUserById()` is called inside two separate `foreach` loops once per team member and once per user seeking a team. Each call executes an individual `SELECT` query against the database, resulting in an N+1 query pattern that scales linearly with the number of users.

## Current Code (N+1 Pattern)

```php
// Loop 1: One query per team member (lines 555-557)
foreach ($team->getMembers() as $teammate) {
    $members[] = $this->core->getQueries()->getUserById($teammate);
}

// Loop 2: One query per seeker (lines 571-573)
foreach ($users_seeking_team as $user_seeking_team) {
    $seekers[] = $this->core->getQueries()->getUserById($user_seeking_team);
}
```

For a team with 5 members and 20 students seeking teams, this executes **25 individual SELECT queries** instead of 1 batch query.

## Proposed Fix

Replace both loops with the existing `getUsersById()` batch method from [DatabaseQueries.php](cci:7://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:0:0-0:0) to fetch all users in a single query. This method is already used elsewhere in the codebase (e.g., `ElectronicGraderController::importTeams()`).

## Impact

- Reduces database queries from O(N) to O(1) for this page
- Improves page load time for courses with many students seeking teams
- No functional change same data returned, just fetched more efficiently

### PR DESCRIPTION
**Pull request by Ash092016**
### Why is this Change Important & Necessary?

Fixes #12505

In `TeamController::showPage()`, the method [getUserById()](cci:1://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:150:4-158:5) is called inside two separate `foreach` loops once per team member and once per user seeking a team. Each call executes an individual `SELECT` query against the database, resulting in an N+1 query pattern.

For a team with 5 members and 20 students seeking teams, this executes **25 individual queries** where **1 batch query** would suffice.

The batch method [getUsersById()](cci:1://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:6361:4-6395:5) already exists in [DatabaseQueries.php](cci:7://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:0:0-0:0) and is used elsewhere in the codebase (e.g., `ElectronicGraderController::importTeams()`), but was not utilized here.

### What is the New Behavior?

**Before:** Two loops each calling [getUserById()](cci:1://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:150:4-158:5) per user (N+1 pattern)

**After:** A single batch [getUsersById()](cci:1://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:6361:4-6395:5) call before the loops, then lookups from the pre-fetched map

No UI changes the page renders identically. The only difference is fewer database queries.

### What steps should a reviewer take to reproduce or test the bug or new feature?

1. Navigate to a team assignment's team management page: `/courses/{semester}/{course}/gradeable/{gradeable_id}/team`
2. Verify that team members are listed correctly
3. Verify that users seeking a team are listed correctly
4. Verify that team invitations still display properly

### Automated Testing & Documentation

- No new tests are required this is a refactor with no functional change
- Existing Cypress E2E tests for team management should continue to pass
- No documentation changes needed

### Other information

- **Not a breaking change** same data is returned in the same order, just fetched more efficiently
- **No migrations needed** uses the existing [getUsersById()](cci:1://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:6361:4-6395:5) method from [DatabaseQueries.php](cci:7://file:///c:/Users/BIT/Desktop/Submitty/site/app/libraries/database/DatabaseQueries.php:0:0-0:0)
- **No security concerns** no change in data access patterns or permissions

### CODE REVIEW

File: site/app/controllers/student/TeamController.php [hunk 1]
```diff
@@ -550,10 +550,23 @@ public function showPage($gradeable_id) {
         $invites_received = [];
         $users_seeking_team = $this->core->getQueries()->getUsersSeekingTeamByGradeableId($gradeable_id);
         $seeking_partner = false;
+
+        // Batch-fetch all needed users in a single query instead of
+        // calling getUserById() per user inside loops (N+1 pattern)
```
Comment (IDzyre) [inline site/app/controllers/student/TeamController.php]:
```suggestion
        // Batch-fetch all needed users in a single query
```

Comment (Ash092016) [reply site/app/controllers/student/TeamController.php]: Done @IDzyre  Sir!

File: site/app/controllers/student/TeamController.php [hunk 2]
```diff
@@ -550,10 +550,22 @@ public function showPage($gradeable_id) {
...
         $seeking_partner = false;
+
+        // Batch-fetch all needed users in a single query
+        $all_user_ids = array_merge(
+            $team !== null ? $team->getMembers() : [],
+            $users_seeking_team
+        );
+        $users_map = !empty($all_user_ids)
+            ? $this->core->getQueries()->getUsersById(array_unique($all_user_ids))
+            : [];
```
Comment (IDzyre) [inline site/app/controllers/student/TeamController.php]: getUsersById returns a blank array if it's empty, so no need for this here, it could just be `$this->core->getQueries()->getUsersById(array_unique($all_user_ids));`

**Comment by Ash092016** [comment]
Yes @IDzyre ! Since getUsersById() already returns an empty array for empty input, the ternary check is redundant here. I've simplified this to a direct call and pushed the update.

File: site/app/controllers/student/TeamController.php (hunk 2 above)
Comment (Ash092016) [reply site/app/controllers/student/TeamController.php]: Done and resolved the redundant empty input check

File: site/app/controllers/student/TeamController.php [hunk 3]
```diff
@@ -550,10 +550,20 @@ public function showPage($gradeable_id) {
         $invites_received = [];
         $users_seeking_team = $this->core->getQueries()->getUsersSeekingTeamByGradeableId($gradeable_id);
         $seeking_partner = false;
+
+        // Batch-fetch all needed users in a single query
+        $all_user_ids = array_merge(
+            $team !== null ? $team->getMembers() : [],
+            $users_seeking_team
+        );
```
Comment (IDzyre) [inline site/app/controllers/student/TeamController.php]: This can probably be condensed to `$all_user_ids = array_merge($team?->getMembers() ?? [], $users_seeking_team)` using the null safe operator, and chaining.

**Comment by Ash092016** [comment]
Hi @IDzyre ! I've refactored the code to use the nullsafe (?->) and null coalescing (??) operators. Thanks for the suggestion!
