### PR TITLE
Check if invalid dates and gradeable_ids fail

### LINKED ISSUE #924: Prevent creation of gradeable with space in the name
Make sure it's clear on the form what the expectations are (no spaces, no weird characters, --  only alpha numeric?)

Add a check when the "add gradeable" button is pushed.

Add a database rule too?

### PR DESCRIPTION
**Pull request by AndrewMRPI**
This checks if a date is invalid and if a gradeable_id is invalid. I did not check everything the form considers invalid. Please tell me if there are any errors or if I should add more checks.
closes  #924

### CODE REVIEW

File: TAGradingServer/account/admin-gradeable.php [hunk 1]
```diff
@@ -297,7 +297,7 @@ function selectBox($question, $grade = 0) {
 </div>
 
         <div class="modal-body" style="/*padding-bottom:80px;*/ overflow:visible;">
-            What is the unique id of this gradeable? (e.g., <kbd>hw01</kbd>, <kbd>lab_12</kbd>, or <kbd>midterm</kbd>): <input style='width: 200px' type='text' name='gradeable_id' class="required" value="{$gradeable_submission_id}" placeholder="(Required)"/>
+            What is the unique id of this gradeable? (e.g., <kbd>hw01</kbd>, <kbd>lab_12</kbd>, or <kbd>midterm</kbd>): <input style='width: 200px' type='text' name='gradeable_id' id="gradeable_id"class="required" value="{$gradeable_submission_id}" placeholder="(Required)"/>
```
Comment (wangj35) [inline TAGradingServer/account/admin-gradeable.php]: Add a space between these two: id="gradeable_id"class="required"

File: TAGradingServer/account/admin-gradeable.php [hunk 2]
```diff
@@ -1574,6 +1575,99 @@ function moveQuestionUp(question) {
         currentRow.children()[1].children[1].checked = newRow.children()[child].children[1].checked;
         newRow.children()[child].children[1].checked = temp;
     }
+
+    /*
+    function nowButton(id_of_time) {
+
+    	$(id_of_time).val(createCrossBrowserJSDate(new Date()));
+    }
+    */
```
Comment (wangj35) [inline TAGradingServer/account/admin-gradeable.php]: Are you using the function nowButton?

File: TAGradingServer/account/admin-gradeable.php [hunk 3]
```diff
@@ -1574,6 +1575,99 @@ function moveQuestionUp(question) {
...
+            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
+        }
+        xmlhttp.onreadystatechange = function() {
+            if (this.readyState == 4 && this.status == 200) {
+                unique_gradeable = this.responseText;
+            }
+        };
+        xmlhttp.open("GET","getuser.php?gradeID="+gradeable_id,true);
+        xmlhttp.send();
+        */
```
Comment (wangj35) [inline TAGradingServer/account/admin-gradeable.php]: Is the code within /* and */ being used?

File: TAGradingServer/account/admin-gradeable.php (hunk 2 above)
Comment (AndrewMRPI) [inline TAGradingServer/account/admin-gradeable.php]: No that was something from before, I can get rid of it.

File: TAGradingServer/account/admin-gradeable.php (hunk 3 above)
Comment (AndrewMRPI) [inline TAGradingServer/account/admin-gradeable.php]: No that was something from before, I can get rid of it.

File: TAGradingServer/account/admin-gradeable.php (hunk 1 above)
Comment (AndrewMRPI) [inline TAGradingServer/account/admin-gradeable.php]: Okay

File: TAGradingServer/account/admin-gradeable.php [hunk 4]
```diff
@@ -1574,6 +1575,75 @@ function moveQuestionUp(question) {
...
+        var test = /^[a-zA-Z0-9_]*$/.test(gradeable_id);
+        var unique_gradeable = false;
+        var check1 = document.getElementById('radio_electronic_file').checked;
+        var check2 = document.getElementById('radio_checkpoints').checked;
+        var check3 = document.getElementById('radio_numeric').checked;
+
+        if (!test || has_space || gradeable_id == "" || gradeable_id === null) {
+            alert("Gradeable id cannot be blank, null, have a space, contain special characters and must be unique");
+            return false;
+        }
```
Comment (MasterOdin) [inline TAGradingServer/account/admin-gradeable.php]: Change the alert to be "Gradeable ID must not be blank and only contain characters __a-z__ __A-Z__ __0-9__ __\___ __-__" (note emphasis).

@bmcutler do we want to accept periods as well?

File: TAGradingServer/account/admin-gradeable.php [hunk 5]
```diff
@@ -1574,6 +1575,75 @@ function moveQuestionUp(question) {
...
+
+    //checks the form to see if it is valid
+    function checkForm()
+    {
+        var gradeable_id = $('#gradeable_id').val();
+        var date_submit = $('#date_submit').val();
+        var date_due = $('#date_due').val();
+        var date_ta_view = $('#date_ta_view').val();
+        var date_grade = $('#date_grade').val();
+        var date_released = $('#date_released').val();
```
Comment (MasterOdin) [inline TAGradingServer/account/admin-gradeable.php]: Do `Date.parse()` on these dates here instead of repeatedly below.

Comment (MasterOdin) [inline TAGradingServer/account/admin-gradeable.php]: Do `Date.parse()` on these dates here instead of repeatedly below.

File: TAGradingServer/account/admin-gradeable.php [hunk 6]
```diff
@@ -1574,6 +1575,75 @@ function moveQuestionUp(question) {
...
+        var config_path = $('input[name=config_path]').val();
+        var has_space = gradeable_id.includes(" ");
+        var test = /^[a-zA-Z0-9_]*$/.test(gradeable_id);
```
Comment (MasterOdin) [inline TAGradingServer/account/admin-gradeable.php]: we should allow hyphens and periods maybe? @bmcutler

File: TAGradingServer/account/admin-gradeable.php (hunk 4 above)
Comment (MasterOdin) [inline TAGradingServer/account/admin-gradeable.php]: Change the alert to be "Gradeable ID must not be blank and only contain characters __a-z__ __A-Z__ __0-9__ __\___" (note emphasis).

Update sentence above to include __-__ and __.__ if they're allowed by @bmcutler

**Comment by MasterOdin** [comment]
So I think don't worry about the unique check for now on gradeable_id (I need to add some routes to do this to the code so it's possible to do it efficiently).

File: TAGradingServer/account/admin-gradeable.php (hunk 6 above)
Comment (bmcutler) [inline TAGradingServer/account/admin-gradeable.php]: yes to hyphens.
no to periods (but I could be convinced otherwise).

**Comment by bmcutler** [comment]
Please open a new issue for the unique check on gradeable id to be done later.

**Comment by MasterOdin** [comment]
Done, made #1036
