### PR TITLE
[Bugfix:HelpQueue] Empty Codes for office hours queue

### LINKED ISSUE #10895: Office Hours Queue -- cannot set queue access code to empty string or NULL
**Describe the bug**
An Office Hours Queue cannot be configured with an empty string or NULL value.
A queue code seems to be required now. 

**Expected behavior**
The queue access code should be optional.

UPDATE:  bug fix in PR #10901 - Issue will remain open until Cypress tests are added in future PR.

### PR DESCRIPTION
**Pull request by williamschen23**
### What is the current behavior?
PR #10394 changed all rows[0] into row(), which might change the functionality of the code and therefore broke the office hour queue.
progress on #10895 but still needs cypress tests

### What is the new behavior?
Revert the changes so now it behaves as expected

### Other information?
Cypress tests might be needed in the future so that this doesn't break again (please I've been doing cypress too much lately can someone else do it 😭 )

### CODE REVIEW

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -8075,7 +8075,7 @@ public function deleteQueue(string $queue_code) {
     public function getValidatedCode(string $queue_code, string $token = null) {
         //first check if the queue has an access code
         $this->course_db->query("SELECT * FROM queue_settings WHERE UPPER(TRIM(code)) = UPPER(TRIM(?)) AND open = true", [$queue_code]);
-        if ($this->course_db->getRowCount() > 0 && $this->course_db->row()['token'] == null) {
+        if ($this->course_db->getRowCount() > 0 && $this->course_db->rows()[0]['token'] == null) {
```
Comment (cjreed121) [inline site/app/libraries/database/DatabaseQueries.php:8078]: Rather than changing this back. Make a tmp variable above this if statement which stores the result of `row()` and then use it both this if statement and line 8079.

**Review by cjreed121 — CHANGES_REQUESTED** [review]

**Review by cjreed121 — APPROVED** [review]
