### PR TITLE
Fixed the alignment of the line_number elements in code outputs.

### LINKED ISSUE #1453: line numbers ruin alignment on autograding output display
see image:

line numbers

The line number should be padded with spaces or zeros to avoid this visual alignment problem (its not in the output file, only in the display when line numbers are added by Submitty)

### PR DESCRIPTION
**Pull request by LeonMontealegre**
Fixes #1453

### CODE REVIEW

File: TAGradingServer/toolbox/include/custom/js/diff-viewer.js [hunk 1]
```diff
@@ -28,4 +28,19 @@ $(document).ready(function() {
     };
 
     $('.highlight').hover(hoverOn, hoverOff);
+
+    // Check if document.getElementsByClassName is supported
+    if (!document.getElementsByClassName)
+        return;
```
Comment (MasterOdin) [inline TAGradingServer/toolbox/include/custom/js/diff-viewer.js]: whatever browser doesn't support getElementsByClassName is a browser we don't care about (according to caniuse.com, it's IE 9- and FF 2 that don't support this and who the hell is still using those at university?).

Comment (bmcutler) [reply TAGradingServer/toolbox/include/custom/js/diff-viewer.js]: @LeonMontealegre please remove these checks in your next commit.  I'm going to merge this PR now.
