### PR TITLE
[Bugfix:TAGrading] Prevent Grade Stealing

### LINKED ISSUE #12223: Visiting an already graded component results in "stealing credit" from the original grader.
**Describe the bug**
 Visiting a graded component can result in "stealing credit" from another grader. When a grading component has already been graded, say by a ta, and then it is visited by another grader, it can transfer credit to the second grader. 

This happens when a grading component that has already been graded is opened and closed twice. Even without changing any marks or saving, the credit will be given to the second grader after opening and closing the graded component two times.

This stolen credit is not reversed or removed upon refreshing the page.

**Expected behavior**
When a graded component is graded by one ta, the credit should not be transferred to another grader without the second grader actually changing the marks given. If the second grader, ta2, opens and closes a graded component already graded by another ta, the credit should not change.

However, if ta2 opens a component that is already graded by a ta, changing the marks given, and clicks save, then the credit should change to "graded by ta2". This is because the student's answer was actually re-evaluated by a new grader.

**To Reproduce**

1. Log in as ta and ta2 in two different browser
2. Navigate to a gradeable, edit it and make sure settings match the ones pictured below
3. As ta, grade a problem and note that "Graded by ta" on the side.
4. Switch to ta2 and click on the problem graded by ta, but do not change any marks or click save
5. Click to collapse the problem, open and collapse it. After a total of two (2) open and closes as ta2, notice that it says "graded by ta2" on the side now.

7. See error**Configuration** 
- OS: [Windows]
- Browser [Chrome, Firefox]

**Screenshots**

Gradeable settings:

Image

Image

Image

Image

Image

**Additional context**
When an ungraded component is open and closed twice, "graded by___" credit will be given to the grader. However, this is temporary and will be removed upon refreshing the page.

### PR DESCRIPTION
**Pull request by williamschen23**
### Why is this Change Important & Necessary?

fixes #12223 Fixes grade stealing on going to home page

### What is the New Behavior?

No grade stealing on going to home page. Added a new window element for a temporary fix while we convert this to vue

### What steps should a reviewer take to reproduce or test the bug or new feature?
I tested going to previous student, going to next student, and going to home page while not on instructor grading a component. With no changes, this keeps instructor as the sole grader. With changes, the text changes to the user on refresh.

### Automated Testing & Documentation

N/A. Convert to vue first before E2e Tests

### Other information

Thank you Justin for tracking the issue so clearly

### CODE REVIEW

File: site/ts/ta-grading-rubric.ts [hunk 1]
```diff
@@ -139,6 +128,19 @@ type GradedGradeable = {
     itempool_items: Record<number, string>;
 };
 
+/**
```
Comment (williamschen23) [inline site/ts/ta-grading-rubric.ts:131]: move all the variables under the type definitions

**Review by JManion32 — APPROVED** [review]
Yay! Great work with this. I tested on main and replicated the issue when clicking next/prev and home, and could no longer replicate on this branch.

Just make sure to properly tag the issue here so it automatically closes. I understand this may not be the most optimal solution, so maybe we should make a new, non-`URGENT/PRIORITY` issue that documents it (or add it to an existing TA grading refactor issue).
