### PR TITLE
[Bugfix:TAGrading] Progress bar show correct percentage

### LINKED ISSUE #10061: TA grading w/ Peer grading - incorrect % completed
**Describe the bug**

I have a gradeable with no autograding, with manual/TA grading and peer grading.
2 components of the rubric are peer grading, two components of the rubric are standard TA/instructor.

Grading has been completed.  All the students filled out their peer grades (every student submission has many peer grades).  All of the TA/instructor marks are completed.

But the TA grading status bar shows:
Screenshot 2023-12-12 at 11 22 07 PM

and the gradeables page shows:
Screenshot 2023-12-12 at 11 22 29 PM

the grading stats page correctly shows:
Screenshot 2023-12-12 at 11 23 11 PM

Note that if I ungrade one component for one student, my grading complete percent bar drops from 50% to 48%.  

If as instructor I add my own scores to peer grading components (this is not expected, but I have the option to add my own scores in for averaging -- for example if one student received too few responses from the peers), even then the grading progress bar is still stuck at 50% exactly.  Instructor scores in peer grading do not change the completion %.

**Expected behavior**
The grading status progress bar should be at 100% in the example described above.

And in general, the grading status progress bar should show how many of the components that are assigned to the current user are complete.  (As instructor/TA we are only expected to complete the non-peer components.

**Additional context**

NOTE:  We will eventually want a way to describe the % of peer grading completed.  That is, the instructor probably wants to hold off on releasing the grade results until a target percentage of the peer grading has been completed.  And the instructor will want to identify if any students have zero peer grades for one or more components -- because this will negatively impact and/or block them from receiving their grades.  Please consider how to address this -- perhaps by adding more data to the grading stats page.

### PR DESCRIPTION
**Pull request by wuj18**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Fixes #10061
When peer grading components are included in TA grading, the progress bar fails to display the correct completion percentage.

### What is the new behavior?
The TA grading status progress bar accurately shows the completion percentage of non-peer components assigned to the grader (instructor, TA, or limited access grader).

### Other information?

Test with an assignment that involves peer grading. Verify if the percentage displayed on the progress bar matches the expected percentage.

### CODE REVIEW

**Review by JWei17 — COMMENTED** [review]
Approve, the peer grading gradable display the correct percentage. The progress bar no longer dropped down when ungraded some students homework.

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -2270,7 +2270,7 @@ public function getTeamsByGradeableAndRotatingSections($g_id, $sections, $orderB
     }
 
     public function getTotalComponentCount($g_id) {
-        $this->course_db->query("SELECT count(*) AS cnt FROM gradeable_component WHERE g_id=?", [$g_id]);
+        $this->course_db->query("SELECT count(*) AS cnt FROM gradeable_component WHERE g_id=? AND gc_is_peer=?", [$g_id, $this->course_db->convertBoolean(false)]);
```
Comment (DarthNyan) [inline site/app/libraries/database/DatabaseQueries.php:2273]: It looks like this change makes it so that getTotalComponentCount only returns the non-peer components. Wouldn't a better fix be to include peer graded components in the %complete calculation?

**Review by DarthNyan — CHANGES_REQUESTED** [review]

File: site/app/libraries/database/DatabaseQueries.php (hunk 1 above)
Comment (wuj18) [reply site/app/libraries/database/DatabaseQueries.php:2273]: Not really, because the progress bar for the TA side should be calculated using the TA-completed components/TA-only components as stated in the expected behavior for the issue. The progress bar for the peer side should be calculated through peer-completed components/peer components, but Nia has another PR that addresses the peer progress bar, so this PR is specifically aimed at resolving the issues with the TA progress bar.

Comment (wuj18) [reply site/app/libraries/database/DatabaseQueries.php:2273]: Thanks for the feedback. I agree that the getTotalComponentCount() should only return all components. I created a new function named getTaComponentCount()

**Review by DarthNyan — COMMENTED** [review]
I like the renaming that you did I think it makes things clearer, and I may have a bit more for you. Is getGradedComponentsCountByGradingSections is ta-specific? If so I think it should be renamed as such. I also think getGradingProgress should be renamed for clarity if it's specifically ta grading progress.

**Review by DarthNyan — APPROVED** [review]
Looks good to me. I think it's a lot more clear now exactly what's going on in the progress bar calculation.

File: site/app/controllers/grading/ElectronicGraderController.php [hunk 2]
```diff
@@ -1811,12 +1811,7 @@ public function showGrading(
             $non_late_graded = $graded - array_sum($late_graded);
         }
         //multiplies users and the number of components a gradeable has together
-        if ($team) {
-            $total_submitted = ($total_submitted * count($gradeable->getComponents()));
-        }
-        else {
-            $total_submitted = ($total_submitted * count($gradeable->getComponents()));
-        }
+        $total_submitted = ($total_submitted * count($gradeable->getNonPeerComponents()));
```
Comment (williamjallen) [inline site/app/controllers/grading/ElectronicGraderController.php:1814]:
```suggestion
        $total_submitted = $total_submitted * count($gradeable->getNonPeerComponents());
```

File: site/app/libraries/database/DatabaseQueries.php [hunk 3]
```diff
@@ -2274,6 +2274,17 @@ public function getTotalComponentCount($g_id) {
         return intval($this->course_db->row()['cnt']);
     }
 
+    /**
+     * Get the number of ta components
+     *
+     * @param  string $g_id gradeable id we are looking up
+     * @return int the number of ta components
+     */
+    public function getTaComponentCount($g_id) {
```
Comment (williamjallen) [inline site/app/libraries/database/DatabaseQueries.php:2283]:
```suggestion
    public function getTaComponentCount(string $g_id): int {
```

**Review by williamjallen — CHANGES_REQUESTED** [review]
A couple brief stylistic comments:

**Review by williamjallen — APPROVED** [review]
My requested changes have been made.  I'm not very familiar with this part of the codebase, so it would be good for someone else to take a look as well.
