### PR TITLE
Fixes the css and additional changes

### LINKED ISSUE #1173: Limit use of the popout icon for submission output
Don't show the popout icon if the file doesn't exist (e.g. test failure).
Don't show the popout icon if the file is small.  (file size < ~ 100 characters?)

Also..  with my browser I seem to only have a single popout window.  The 2nd popout click opens that item in the window that previously displayed the 1st popout click.  (The limits the usability of comparing 2 files.

### LINKED ISSUE #1176: Remove reset.css from diff-viewer.css
Reset.css should be call before any other CSS file, not after some have been loaded as it means some amount of the previous CSS files are not loaded properly. By adding this to `diff-viewer.css`, that means that we've broken some amount of the display (like now the background shows up nowhere).

@AndrewMRPI You need to figure out what exactly you want out of server.css, and probably just move or duplicate it in diff-viewer.css, and not import all of server.css inside the popup box, not call reset in diff-viewer.css.

Commit that caused this: 119019032287af46fd54927689bcefe75d09b549

### PR DESCRIPTION
**Pull request by AndrewMRPI**
This fixes the css and changes other things in regards to the issues mentioned below.
Closes #1176
Closes #1173

### CODE REVIEW

File: site/app/views/submission/HomeworkView.php [hunk 1]
```diff
@@ -726,15 +726,25 @@ function submitStudentGradeable(student_id, highest_version) {
...
                                     $return .= <<<HTML
                             <div class='diff-element'>
 HTML;
                                     if ($diff_viewer->hasDisplayExpected()) {
                                         $title = "Student ";
                                     }
+                                    if ($diff_viewer->hasDisplayActual()) {
+                                        //I unfornately have no idea how the strlen is measured. It's not the number of characters in there
+                                        //an extra 250ish characters are added on for some reason.
+                                        if (strlen($diff_viewer->getDisplayActual()) < 350) {
```
Comment (MasterOdin) [inline site/app/views/submission/HomeworkView.php]: We need to investigate this further before accepting this PR as this is subject to change/break without anyone realizing it with this "magic number". Use var_dump to see what the content is? I'm guessing there's weird space characters in the text that are messing things up if using `len` in Python on the file contents also says 350 characters.

File: site/public/css/diff-viewer.css [hunk 2]
```diff
@@ -1,4 +1,3 @@
-@import url("reset.css");
```
Comment (MasterOdin) [inline site/public/css/diff-viewer.css]: just doing this then makes the popup look ugly though since you're still bringing sever.css into it which you most likely don't want to do (and why you added the reset.css in the first place.

Comment (AndrewMRPI) [inline site/public/css/diff-viewer.css]: I don't bring the server.css in. I bring every css except that one since I don't want the background to change blue.

Comment (MasterOdin) [inline site/public/css/diff-viewer.css]: Ah, my bad. I thought you had to get the right font, guess not.

File: site/app/views/submission/HomeworkView.php (hunk 1 above)
Comment (AndrewMRPI) [inline site/app/views/submission/HomeworkView.php]: The characters were a bunch of spaces, html tags and newlines. I made a commit to get rid of them when calculating the strlen.

File: site/app/views/submission/HomeworkView.php [hunk 3]
```diff
@@ -734,9 +734,16 @@ function submitStudentGradeable(student_id, highest_version) {
...
+                                        $tmp_array_string = explode("\n",trim(html_entity_decode(strip_tags($diff_viewer->getDisplayActual())), "\xC2\xA0\t")); 
+                                        $less_than_30 = true;
+                                        $arr_count = count($tmp_array_string);
+                                        for ($x = 0; $x < $arr_count; $x++) {
+                                            if(strlen($tmp_array_string[$x]) > 30) {
+                                                $less_than_30 = false;
+                                                $x = $arr_count;
+                                            }
+                                        }
+                                        if (substr_count($diff_viewer->getDisplayActual(), 'line_number') < 10 && $less_than_30) {
```
Comment (MasterOdin) [inline site/app/views/submission/HomeworkView.php]: instead of doing `substr_count`, why can't we just do `$arr_count < 10` here? (same for getDisplayExpected())

Comment (AndrewMRPI) [inline site/app/views/submission/HomeworkView.php]: Due to how striping the tags works and everything, the array actually has some extra line that are just empty strings. I don't think that's the most reliable way to check for height then.

Comment (MasterOdin) [inline site/app/views/submission/HomeworkView.php]: Fair enough.
