### PR TITLE
[Bugfix:Forum] Fixed unread highlight seen by poster for new post/thread.

### LINKED ISSUE #4431: Discussion forum posts that you just commented on are marked as having a new unread comment even though you posted that comment
**Describe the bug**
A discussion forum post will be highlighted indicating an unread comment after I post a comment. To remove this I have to click on a different post and back to the "unread" post

**Expected behavior**
If I was the one who just posted a comment on a post I think it should be assumed I have read it and therefore not be highlighted as if I have not seen the new comment I just made. 

**To Reproduce**
1. Comment on a post
2. Note how in the list of posts the thread you are on is highlighted as if there is a new unread comment.

**Configuration**
 - OS: Linux
 - Browser: Firefox 69

**Screenshots**
The yellow comment in this case is a comment just posted by me
image

**Additional context**
This is a very very minor issue but I thought I should post it anyway. There is obviously no rush to fix this.

### PR DESCRIPTION
**Pull request by dpham-p**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Fixes #4431 
When a poster creates a new post/thread, the new thread in the thread list or the new post will be highlighted as if the poster did not read their own post/thread.

### What is the new behavior?
The poster will not see their new post/thread highlighted but others will still be able to.
### Other information?

Tested by creating new posts/threads and viewing them between different users.

### CODE REVIEW

File: site/app/controllers/forum/ForumController.php [hunk 1]
```diff
@@ -291,6 +291,8 @@ public function publishThread(){
                 $thread_id = $result["thread_id"];
                 $post_id = $result["post_id"];
 
+                $this->core->getQueries()->visitThread($current_user_id, $thread_id);
```
Comment (sak6lab) [inline site/app/controllers/forum/ForumController.php]: Move this to createThread in DatabaseQueries
