### PR TITLE
[Bugfix:Forum] Fix OP badge on anonymous toggle

### LINKED ISSUE #11755: Toggle Anonymous Mode slightly incorrect colors
**Describe the bug**

https://github.com/user-attachments/assets/a2a358f7-81b0-48be-a50d-498111bffa43
Anonymous color changes to black. 
OP disappears after clicking the toggle
In Discussion forum for InstructorUI, we allow for deanonymouizing the student. When we try to do this, this changes the color to black and the OP that is suppose to be blue is also black for some reason.

**Expected behavior**

Same as the non-anonymous mode.
OP should not disappear

**To Reproduce**
1. Make a forum post as a student
2. Look at forum post as an instructor
3. Toggle Anonymous mode (eyes)

**Configuration**
 - OS: [e.g. Windows, Linux, ...]
 - Browser [e.g. Chrome, Safari]

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Akarshkushwaha**
### Why is this Change Important & Necessary?
Fixes #11755

This change is necessary because toggling the anonymity of a student in the Instructor Discussion Forum (using the "eye" icon) causes the Original Poster (OP) badge to disappear from the DOM. Additionally, toggling back to "Anonymous" hardcodes the text color to black when the site is set to Dark Mode. 

### What is the New Behavior?
- The Original Poster (OP) badge is preserved and accurately displayed when revealing or hiding a student's real name.
- Toggling back to "Anonymous" on Dark Mode correctly inherits the default white text color instead of switching to pure black.
- [site/app/templates/forum/CreatePost.twig] now wraps `visible_username` inside a targeted `.author-name` span so JavaScript does not overwrite sibling elements (like the OP badge).
- [site/public/js/server.js] [changeName()] function now cleanly targets `.author-name` and removes the `color` property instead of overriding it, keeping CSS inheritance intact for dark mode.

Before:-
image

After:-
image
image

### What steps should a reviewer take to reproduce or test the bug or new feature?
1. Open up the Submitty instance as an instructor.
2. Ensure you have the site set to Dark Mode.
3. Locate an anonymous post/thread on the Discussion Forum where the anonymous user is the Original Poster.
4. Click the 'eye' icon to deanonymize the student.
5. Verify the "OP" badge remains visible next to the student's real name.
6. Click the 'eye' icon again to return the status to "Anonymous".
7. Verify that the word "Anonymous" returns to the standard white color, instead of changing to black text.

### Automated Testing & Documentation
N/A - This is a CSS and DOM structure change that requires manual UI verification in the browser to confirm dark/light mode behavior.

### Other information
This is not a breaking change.
No migrations are required.
No security concerns.

### CODE REVIEW

**Comment by Akarshkushwaha** [comment]
Hi @bmcutler @williamjallen, I've implemented a fix for issue #11755
The OP badge is now preserved when deanonymizing a student, and the "Anonymous" text color incorrectly switching to black in Dark Mode has been resolved. The PR is ready for review whenever you have a moment. Let me know if you need any adjustments or further changes

File: site/public/js/server.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ function changeDiffView(div_name, gradeable_id, who_id, version, index, autochec
     }
     // Insert actual and expected one at a time
     let url = `${buildCourseUrl(['gradeable', gradeable_id, 'grading', 'student_output', 'remove'])
-    }?who_id=${who_id}&version=${version}&index=${index}&autocheck_cnt=${autocheck_cnt}&option=${option}&which=expected`;
+        }?who_id=${who_id}&version=${version}&index=${index}&autocheck_cnt=${autocheck_cnt}&option=${option}&which=expected`;
```
Comment (williamjallen) [inline site/public/js/server.js]: Please revert all of the changes which aren't strictly necessary for this PR.  Such whitespace changes cause conflicts with other work and make it less clear what your PR does.

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/public/js/server.js (hunk 1 above)
Comment (Akarshkushwaha) [reply site/public/js/server.js]: Thanks for the review! I completely agree. I have reverted the unnecessary whitespace formatting changes in server.js and pushed a new commit to isolate just the changeName bug fix for the OP Badge."

Comment (williamjallen) [reply site/public/js/server.js]: @Akarshkushwaha See prior comment.  You should revert all unnecessary changes to all files.

**Review by williamjallen — CHANGES_REQUESTED** [review]
