### PR TITLE
[Bugfix:InstructorUI] Change of constraints in team name

### LINKED ISSUE #10074: Team Gradeables - team name length
**Describe the bug**
Students can optionally specify a team name for their gradeable.
Currently we don't seem to have a limit on the length of the team name or on the characters that can be used for a team name.
If the team name is excessively lengthy, this impacts the rendering of the TA grading index page and makes it difficult for graders to do their work.  Also, if there are weird or un-renderable characters in the team name, the display is confusing.

NOTE: instructors can edit a team name from the grading index page.  So lengthy team names can be manually replaced one-at-at-time.  But this is temporary, students can re-edit the team name.

**How to fix it**

NOTE: At this time, let's not write a migration to change any existing team names.  

* Let's truncate long team names already in the database before displaying the TA grading index page.  About 30 characters should be sufficient.  If the name is longer than 30 characters let's add "..." (ellipses) to make clear its been truncated.

* On the page where the students specify their team name or edit their team name, let's add some text:
"Team names are limited to 30 characters"
And if a student tries to make a longer team name, they should get an error message and the new name should not save.
Let's make sure this applies to new teams, new team names, and editing names of existing teams.

* On the page where instructors can edit the name of a team, let's also cap the length of edits to team names to 30 characters.

* Let's also decide on a reasonable set of characters that can be used in team names:  letters, numbers, spaces, dash, underscore for sure.  Would be nice to include characters with accents also.  But is it necessary to have emojis?  This is unnecessary and outside the original purpose of team names - to help instructors in large classes where it is helpful to label big groups and facilitate efficient course management.

### PR DESCRIPTION
**Pull request by GO-viper7**
### Please check if the PR fulfills these requirements:

* [✅] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Fixes #10074

Presently, there is no restriction on the length or allowed characters for team names. However, extensive team names can disrupt the layout of the TA grading index page, posing challenges for graders in carrying out their tasks. Additionally, the presence of unusual or unrenderable characters in team names can lead to a confusing display.

### What is the new behavior?

Truncating the Team name with greater than 30 characters and adding "..." (ellipses)
Text to indicate team name cannot have more than 30 characters

Displaying error response for the below after user clicks on submit:

1. If team name contains emojis
2. If team name contains special characters (['-', '_' ] are omitted and the array in code can be expandable upon further requests)
3. If team name has more than 30 characters.

TeamElipses
TeamLimit

### CODE REVIEW

**Comment by GO-viper7** [comment]
hey @shailpatels 

I have created a branch named "team-constraint-origin" from the branch "team-constraint" which you have created
and merged with main

Hope this resolved all of the issues regarding the same
You may go through, Thank you.

**Comment by williamjallen** [comment]
For future reference, this PR supersedes #10095.

**Review by shailpatels — APPROVED** [review]
Thanks for the PR! And sorry again for destroying the original one, forks on github  are still weirdly confusing :sweat_smile: 

Changes look good and works as described

**Comment by GO-viper7** [comment]
> Thanks for the PR! And sorry again for destroying the original one, forks on github are still weirdly confusing 😅
> 
> Changes look good and works as described

welcome and no worries 😊, you made me understand forks much better
Thank you.

File: site/app/controllers/student/TeamController.php [hunk 1]
```diff
@@ -6,9 +6,21 @@
...
+use app\models\Team;
 use Symfony\Component\Routing\Annotation\Route;
 
 class TeamController extends AbstractController {
+    /**
+     * Check if a string has special characters.
+     * @param string $str
+     * @return bool
+     */
+    public static function hasSpecialCharacters($str) {
```
Comment (williamjallen) [inline site/app/controllers/student/TeamController.php:18]:
```suggestion
    /**
     * Check if a string has special characters.
     */
    public static function hasSpecialCharacters(string $str): bool {
```

File: site/app/controllers/student/TeamController.php [hunk 2]
```diff
@@ -496,6 +508,22 @@ public function setTeamName($gradeable_id): RedirectResponse {
         if ($_POST['team_name'] == '') {
             $_POST['team_name'] = null;
         }
+        else {
+            if (strlen($_POST['team_name']) > Team::MAX_TEAM_NAME_LENGTH) {
+                $this->core->addErrorMessage("Number of characters in team name must be less than " . Team::MAX_TEAM_NAME_LENGTH);
+                return new RedirectResponse($return_url);
+            }
+
+            if (preg_match('/[\x{1F600}-\x{1F64F}\x{1F300}-\x{1F5FF}\x{1F680}-\x{1F6FF}\x{1F700}-\x{1F77F}\x{1F780}-\x{1F7FF}\x{1F800}-\x{1F8FF}\x{1F900}-\x{1F9FF}\x{1FA00}-\x{1FA6F}\x{1FA70}-\x{1FAFF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}\x{2300}-\x{23FF}]/u', $_POST['team_name'])) {
```
Comment (williamjallen) [inline site/app/controllers/student/TeamController.php:517]: Are these all of the possible special character values?  This should at least have a comment describing the purpose of this line.  Otherwise, is there a better way to go about doing this?  Instead of prohibiting characters, would it instead make more sense to create a regex which matches allowable characters?

File: site/app/templates/submission/EditTeamName.twig [hunk 3]
```diff
@@ -4,16 +4,21 @@
 {% block body %}
     <p class="std-margin">
         Please fill in an appropriate name for your team if you would like.
+        <br>
+        Team names are limited to {{ team_name_length }} characters
```
Comment (williamjallen) [inline site/app/templates/submission/EditTeamName.twig:8]: Most people aren't going to create team names which are excessively long.  As a result, I think adding help text like this to proactively prevent people from entering excessively long names is unnecessary.  Most people will understand the behavior of their browser when the max length attribute is enforced.

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/controllers/student/TeamController.php (hunk 2 above)
Comment (GO-viper7) [reply site/app/controllers/student/TeamController.php:517]: The above mentioned long regular expression checks for emojis in the team name.
It covers significant portion of the emoji characters.

I suppose this kind of blacklisting characters is well optimized than whitelisting allowable characters.

File: site/app/templates/submission/EditTeamName.twig (hunk 3 above)
Comment (GO-viper7) [reply site/app/templates/submission/EditTeamName.twig:8]: Yes, agree with you
will just remove the line.

**Comment by GO-viper7** [comment]
sorry for multiple commits.
and you may go through above @williamjallen

**Comment by williamjallen** [comment]
> 1. hasSpecialCharacters function will not check for emoji characters
> 2. The long regular expression checks for significant amount of emojis out there.

Instead of prohibiting characters, you can instead use a regular expression which only allows alphanumeric characters, dashes, underscores, and spaces.

**Comment by GO-viper7** [comment]
> > 1. hasSpecialCharacters function will not check for emoji characters
> > 2. The long regular expression checks for significant amount of emojis out there.
> 
> Instead of prohibiting characters, you can instead use a regular expression which only allows alphanumeric characters, dashes, underscores, and spaces.

I see, u mean whitelisting in this way
got it!

File: site/app/controllers/student/TeamController.php (hunk 1 above)
Comment (williamjallen) [reply site/app/controllers/student/TeamController.php:18]: This comment still needs to be addressed.  It is better to use native PHP type annotations whenever possible since they are enforced by the language, rather than PHPDoc comments which are not.

File: site/app/controllers/student/TeamController.php [hunk 4]
```diff
@@ -6,9 +6,21 @@
...
 
 class TeamController extends AbstractController {
+    /**
+     * Check if a string has special characters.
+     * @param string $str
+     * @return bool
+     */
+    public static function hasSpecialCharacters($str) {
+        $allowedCharacters = ['a-z', 'A-Z', '0-9', '-', '_', ' ']; // This list can be expandable upon further requests
+        $pattern = '/[^' . implode('', $allowedCharacters) . ']/';
```
Comment (williamjallen) [inline site/app/controllers/student/TeamController.php:20]: Why do you need an array of allowed characters here?

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/controllers/student/TeamController.php (hunk 4 above)
Comment (GO-viper7) [reply site/app/controllers/student/TeamController.php:20]: @MasterOdin suggested to maintain a list of allowed characters 
such that it would be easy to update it in the future rather than changing the regex itself.

Comment (MasterOdin) [reply site/app/controllers/student/TeamController.php:15]: Sorry, when I said "list" I meant it more abstractly, rather than specifically that you should use a list/array to have the characters. I think it's fine to just have this singular regex, as editing the range is easy enough.

```suggestion
        $pattern = '/[^a-zA-Z0-9-_ ]/';
```

Comment (GO-viper7) [reply site/app/controllers/student/TeamController.php]: > Sorry, when I said "list" I meant it more abstractly, rather than specifically that you should use a list/array to have the characters. I think it's fine to just have this singular regex, as editing the range is easy enough.

got it
pushed the changes
and you may review it

**Review by chenjohnny-cs — APPROVED** [review]
I have tested and reviewed the code on my local machine, and I was able to replicate the error, after merging in the changes, the changes and comments listed in the PR seem to have been tackled.

So far, I have found no bugs within the code and everything seems to be working accordingly. There is a clear enhancement in the UI compared to before, and it seems good to merge.

File: site/app/templates/submission/EditTeamName.twig [hunk 5]
```diff
@@ -5,15 +5,18 @@
...
             <input type="text"
-                   name="team_name"
-                   value="{{ team_name }}"
-                   id="team-name-change"
-                   data-current-name="{{ team_name }}"/>
+                name="team_name"
+                value="{{ team_name }}"
+                id="team-name-change"
+                data-current-name="{{ team_name }}"
+                maxlength="{{ team_name_length }}"
```
Comment (IDzyre) [inline site/app/templates/submission/EditTeamName.twig:18]:
```suggestion
                max-length="{{ team_name_length }}"
```

To keep the variables consistent with others, there should be a hyphen.

**Review by IDzyre — CHANGES_REQUESTED** [review]

File: site/app/templates/submission/EditTeamName.twig (hunk 5 above)
Comment (GO-viper7) [reply site/app/templates/submission/EditTeamName.twig]: got it!

Comment (GO-viper7) [reply site/app/templates/submission/EditTeamName.twig]: @IDzyre , i just observed that maxlength is a pre defined html attribute at client side
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength 
So, its ok to revert it back from max-length right ?

Comment (IDzyre) [reply site/app/templates/submission/EditTeamName.twig]: Yes

Comment (GO-viper7) [reply site/app/templates/submission/EditTeamName.twig:18]: Hey @IDzyre, reverted to maxlength and fixed those lint errors
You may run the tests, thanks.

**Comment by GO-viper7** [comment]
Hey @chenjohnny-cs, can you please run the tests
Just want to make sure, there are no lint errors/ cypress test fails.
Thank you.

**Comment by chenjohnny-cs** [comment]
> Hey @chenjohnny-cs, can you please run the tests Just want to make sure, there are no lint errors/ cypress test fails. Thank you.

Sure, should be going through now

**Comment by GO-viper7** [comment]
> > Hey @chenjohnny-cs, can you please run the tests Just want to make sure, there are no lint errors/ cypress test fails. Thank you.
> 
> Sure, should be going through now

Hey, just realized after seeing the error
So, added datatype for the argument also commented purpose of the function
You may run it now, thanks.

**Review by shailpatels — APPROVED** [review]
Approving again after retesting for the requested changes, thanks for the PR!

**Comment by GO-viper7** [comment]
> Approving again after retesting for the requested changes, thanks for the PR!

thanks for the approval!
So @shailpatels , could you please merge this PR as the issue's been resolved successfully

**Comment by shailpatels** [comment]
> > Approving again after retesting for the requested changes, thanks for the PR!
> 
> thanks for the approval! So @shailpatels , could you please merge this PR as the issue's been resolved successfully

Sorry for the delay but I don't have permission to merge PRs but we'll try and process it as soon as we can, just a lot of PRs from existing and new developers right now and the majority of reviewers are volunteering their time to test + review!

**Comment by GO-viper7** [comment]
> > > Approving again after retesting for the requested changes, thanks for the PR!
> > 
> > 
> > thanks for the approval! So @shailpatels , could you please merge this PR as the issue's been resolved successfully
> 
> Sorry for the delay but I don't have permission to merge PRs but we'll try and process it as soon as we can, just a lot of PRs from existing and new developers right now and the majority of reviewers are volunteering their time to test + review!

Alright!, no worries at all. Thanks again!

File: site/app/templates/grading/electronic/Details.twig [hunk 6]
```diff
@@ -595,9 +595,15 @@
...
 
 {# Team Name #}
-{% macro render_column_team_name(context, section, graded_gradeable, index, info, column) %}
+{% macro render_column_team_name(context, section, graded_gradeable, index, info, column, max_team_name_length) %}
     <td>
-        {{ graded_gradeable.getSubmitter().getTeam().getTeamName() }}
+        {# existing teams names over max length get truncated down on display #}
+        {% if graded_gradeable.getSubmitter().getTeam().getTeamName()|length > max_team_name_length %}
+          {% set truncatedString = graded_gradeable.getSubmitter().getTeam().getTeamName()|slice(0, max_team_name_length) ~ '...' %}
+          {{ truncatedString }}
```
Comment (MasterOdin) [inline site/app/templates/grading/electronic/Details.twig:603]: Do we need to do a `set` here, or could this be simply:

```suggestion
          {{ graded_gradeable.getSubmitter().getTeam().getTeamName()|slice(0, max_team_name_length) ~ '...' }}
```

File: site/app/controllers/student/TeamController.php [hunk 7]
```diff
@@ -6,9 +6,18 @@
...
 use app\libraries\FileUtils;
 use app\libraries\response\RedirectResponse;
+use app\models\Team;
 use Symfony\Component\Routing\Annotation\Route;
 
 class TeamController extends AbstractController {
+    /**
+     * Check if a string has special characters.
+     */
+    public static function hasSpecialCharacters(string $str): bool {
```
Comment (MasterOdin) [inline site/app/controllers/student/TeamController.php:16]: Could you add two tests for this function to https://github.com/Submitty/Submitty/blob/main/site/tests/app/controllers/student/TeamControllerTester.php, one for a team name that has no special characters and one that does to validate behavior?

File: site/app/templates/grading/electronic/Details.twig (hunk 6 above)
Comment (GO-viper7) [reply site/app/templates/grading/electronic/Details.twig]: sure, why not!
Just thought of breaking it into 2 lines, but never mind.

File: site/app/controllers/student/TeamController.php (hunk 7 above)
Comment (GO-viper7) [reply site/app/controllers/student/TeamController.php:16]: sure
So, there's already a test named `testSetTeamName` to set team name which implicitly checks for the special characters as of now
Thus, I wrote only a single test `testSetTeamNameWithSpecialCharacters` to validate the behavior
You may review the code.

**Review by MasterOdin — APPROVED** [review]

**Comment by GO-viper7** [comment]
Thanks! for the review and approval @MasterOdin 
So, can I merge latest changes from main to this branch, for this PR to get merged ?
