### PR TITLE
[Bugfix:Submission] Bulk upload encode query params

### LINKED ISSUE #11185: bulk upload pdf exam filenames may not have spaces
**Describe the bug**
Reported by a user on Zulip.
I also verified that it is still a bug.

The instructor's interface for bulk upload of exams by scanned pdf does not accept scanned pdf filenames with spaces.
The error message is unhelpful:

Screenshot 2024-11-28 at 2 15 24 PM

**Expected behavior**
- [ ] Figure out what requirements we currently have for these filenames.  Besides space, are there any other disallowed characters for filenames?
- [ ] Let's put a sentence of documentation on this page with the filename requirements.
- [ ] Let's improve the error message if the user violates the filename requirements.

**To Reproduce**
1. make a pdf with a space in the filename, e.g., ```with space.pdf```
2. upload it to a scanned exam / bulk upload gradeable, e.g., http://localhost:1511/courses/f24/sample/gradeable/bulk_upload_test (specify split page count  = '1')

### PR DESCRIPTION
**Pull request by MjStar24**
Fixes #11185 
If a file uploaded by TA/instructor to a bulk upload pdf file gradeable contains a space in the filename, the error is unhelpful.

----------------------

In addition to space, we currently have the following disallowed characters, and I have included space as well:

Screenshot 2024-12-04 042041

Added documentation for filename requirements :

Screenshot 2024-12-04 034250

Error message is also fixed : 

Screenshot 2024-12-04 042821

### CODE REVIEW

**Review by cjreed121 — CHANGES_REQUESTED** [review]
Thanks for the contribution. This is not the intended fix. I believe spaces are allowed in other locations in submitty already and we should determine what the issue actually is here. I have a feeling it has to due with https://github.com/Submitty/Submitty/blob/60e990b061455d9af00567391c6ad09c36c11258/site/app/controllers/student/SubmissionController.php#L495 as it will try to inject a space directly into a url string without encoding it which is problematic. Could you try fixing that and see if it resolves this.

**Comment by MjStar24** [comment]
@cjreed121 Thanks for pointing out.
The issue has been resolved. I updated the code to properly encode the URL parameters using urlencode(), which prevents any invalid characters like spaces from being injected into the URL.
Screenshot 2024-12-30 111855


code changes: 
Screenshot 2024-12-30 111951

File: site/app/controllers/student/SubmissionController.php [hunk 1]
```diff
@@ -491,13 +491,17 @@ public function ajaxBulkUpload($gradeable_id) {
                 // exec() and similar functions are disabled by security policy,
                 // so we are using a python script via CGI to validate whether file is divisible by num_page or not.
                 $pdf_full_path = FileUtils::joinPaths($pdf_path, $job_data["timestamp"], $job_data["filename"]);
+                $num_pages_encoded = urlencode($num_pages);
+                $file_name_encoded = urlencode($job_data['filename']);
+                $pdf_full_path_encoded = urlencode($pdf_full_path);
                 $ch = curl_init();
-                curl_setopt($ch, CURLOPT_URL, $this->core->getConfig()->getCgiUrl() . "pdf_page_check.cgi?pdf_path={$pdf_full_path}&num_page={$num_pages}&file_name={$job_data['filename']}");
+                curl_setopt($ch, CURLOPT_URL, $this->core->getConfig()->getCgiUrl() . "pdf_page_check.cgi?pdf_path={$pdf_full_path_encoded}&num_page={$num_pages_encoded}&file_name={$file_name_encoded}");
```
Comment (cjreed121) [inline site/app/controllers/student/SubmissionController.php:498]: Sorry to make you change it again but could you actually swap this to use `http_build_query()`. It'll make this much cleaner and more maintainable. A good existing example of this would be: https://github.com/Submitty/Submitty/blob/de454f23ee1a2828f62c89f717c4043be969696d/site/app/controllers/HomePageController.php#L194-L201

**Review by cjreed121 — CHANGES_REQUESTED** [review]

File: site/app/controllers/student/SubmissionController.php (hunk 1 above)
Comment (cjreed121) [reply site/app/controllers/student/SubmissionController.php:498]: Don't change the `curl_setopt` to `curlRequest` just use the example for how to use `http_build_query`

Comment (MjStar24) [reply site/app/controllers/student/SubmissionController.php]: @cjreed121 I have implemented the suggested changes. Please let me know if any further adjustments are needed

Comment (cjreed121) [reply site/app/controllers/student/SubmissionController.php]: Please address the failing lint test. Run it locally to verify it is fixed and let us know once that is done.

Comment (MjStar24) [reply site/app/controllers/student/SubmissionController.php]: I have fixed the lints

File: site/app/controllers/student/SubmissionController.php [hunk 2]
```diff
@@ -492,12 +492,19 @@ public function ajaxBulkUpload($gradeable_id) {
                 // so we are using a python script via CGI to validate whether file is divisible by num_page or not.
                 $pdf_full_path = FileUtils::joinPaths($pdf_path, $job_data["timestamp"], $job_data["filename"]);
                 $ch = curl_init();
-                curl_setopt($ch, CURLOPT_URL, $this->core->getConfig()->getCgiUrl() . "pdf_page_check.cgi?pdf_path={$pdf_full_path}&num_page={$num_pages}&file_name={$job_data['filename']}");
+                curl_setopt($ch, CURLOPT_URL, $this->core->getConfig()->getCgiUrl() . "pdf_page_check.cgi" . "?" . http_build_query(
```
Comment (cjreed121) [inline site/app/controllers/student/SubmissionController.php:495]:
```suggestion
                curl_setopt($ch, CURLOPT_URL, $this->core->getConfig()->getCgiUrl() . "pdf_page_check.cgi?" . http_build_query(
```

File: site/app/controllers/student/SubmissionController.php [hunk 3]
```diff
@@ -492,12 +492,19 @@ public function ajaxBulkUpload($gradeable_id) {
...
+                        'num_page' => $num_pages,
+                        'file_name' => $job_data['filename']
+                    ]
+                ));
                 curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                 $output = curl_exec($ch);
                 curl_close($ch);
                 $response = json_decode($output);
 
+
```
Comment (cjreed121) [inline site/app/controllers/student/SubmissionController.php:507]: Please revert this unnecessary newline change

**Review by cjreed121 — CHANGES_REQUESTED** [review]

File: site/app/controllers/student/SubmissionController.php (hunk 3 above)
Comment (MjStar24) [reply site/app/controllers/student/SubmissionController.php]: done

**Comment by cjreed121** [comment]
@MjStar24 Code looks good. Please update the description the reflect the new changes. Additionally, make sure it follows the expected format for all PRs. This is set by default which you have removed. You can see other MRs to check what it looks like or see https://raw.githubusercontent.com/Submitty/Submitty/refs/heads/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by williamjallen** [comment]
@cjreed121 What is the status of this PR?  Does this just need a functionality review before it can be merged?

**Comment by cjreed121** [comment]
> @cjreed121 What is the status of this PR? Does this just need a functionality review before it can be merged?

Code looks good to me. Was waiting for description to be updated. A functionality review would be good to do though as I only have been looking at the code.

**Review by grt812 — APPROVED** [review]
Functionality works as expected

**Comment by hinyan17** [comment]
Couldn't get the functionality to work. Uploading a file with a space in the name doesn't show the original "Unknown error occurred" but now shows a window alert saying "Error parsing response from server. Please copy...". Could you update the PR description to be more clear?

**Comment by hinyan17** [comment]
Sorry, it was a git issue. Functionality works after I confirmed that git pulled from the forked repo properly

**Review by hinyan17 — APPROVED** [review]
