### PR TITLE
[Bugfix:InstructorUI] Exc thrown when no students in Rot Sec

### LINKED ISSUE #8900: Exception thrown when managing rotating sections by removing unregistered students when all students are removed from rotating sections
**Describe the bug**
There appears to be an exception thrown if the user selects " Remove all students from rotating sections " followed by a "Remove unregistered students (registration section=NULL) from rotating sections and put newly registered students into rotating section with fewest members "

image

**Expected behavior**
No exception should be thrown, if the user is trying to do something invalid or wrong an error message should be shown instead

**To Reproduce**
1.  Go to the manage sections page in a course
2. Scroll down to the Manage Rotating Sections part of the page
3. Select the radio button " Remove all students from rotating sections " and hit submit 
4. Then select the radio button "Remove unregistered students (registration section=NULL) from rotating sections and put newly registered students into rotating section with fewest members " and hit submit

**Additional context**
The operation does appear to do something, the sections are distributed back after the first removal so not sure if this is completely failing or what the expected behavior is 

This appears to only happen when there's more than 2 rotating sections

### PR DESCRIPTION
**Pull request by jason490**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #8900 
If there is no one in the rotating section and the second option of radio button is selected and submitted, it throws an exception

### What is the new behavior?
No longer throws the exception, when there is no one in the rotating section and the second option is selected to fill all the students into the rotating section

### CODE REVIEW

File: site/app/controllers/admin/UsersController.php [hunk 1]
```diff
@@ -636,7 +636,12 @@ public function updateRotatingSections() {
             }
             $curr_section_sizes = $this->core->getQueries()->getUsersCountByRotatingSections();
             $section_assignment_counts = array_map(function ($expected_size, $curr_size) {
-                return $expected_size - $curr_size['count'];
+                if ($curr_size === null) {
+                    return $expected_size;
+                }
+                else {
+                    return $expected_size - $curr_size['count'];
+                }
```
Comment (williamjallen) [inline site/app/controllers/admin/UsersController.php:644]: This could be replaced with a ternary expression.
```suggestion
                return $curr_size === null ? $expected_size : $expected_size - $curr_size['count'];
```

**Review by williamjallen — DISMISSED** [review]

**Comment by hansongu123** [comment]
Functionality wise it works good! Although, on this branch it doesn't give the second radio button a dropdown window, which made by your last PR - maybe because that PR was just merged. Try to make this branch up-to-date and then test it out again. But it should work anyways.

**Comment by hansongu123** [comment]
Done.

**Review by hansongu123 — APPROVED** [review]
