### PR TITLE
Removed ineffective code from ForumThreadView.php

### LINKED ISSUE #3549: Ineffective code in ForumThreadView.php
**Describe the bug**
Some code lines in ForumThreadView.php are ineffective and contribute nothing to the program, as investigated. 

```
$activeThreadAnnouncement = false;
$activeThreadTitle = "";
$function_date = 'date_format'; //INEFFECTIVE
$activeThread = array();
$return .= $this->displayThreadList($threadsHead, false, $activeThreadAnnouncement, $activeThreadTitle, $activeThread, $currentThread, $currentCategoriesIds);
if(count($activeThread) == 0) {
    $activeThread = $this->core->getQueries()->getThread($currentThread)[0];
    $activeThreadTitle = $activeThread['title'];
}
$activeThreadTitle = htmlentities(html_entity_decode($activeThreadTitle, ENT_QUOTES | ENT_HTML5, 'UTF-8'), ENT_QUOTES | ENT_HTML5, 'UTF-8'); //INEFFECTIVE

$thread_id = -1; //INEFFECTIVE
$userAccessToAnon = ($this->core->getUser()->getGroup() < 4) ? true : false; //INEFFECTIVE
$title_html = ''; //INEFFECTIVE
```

**Expected behavior**
These lines should be removed. 

**To Reproduce**
1. Open app/views/forum/ForumThreadView.php

### PR DESCRIPTION
**Pull request by xprilion**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?
Closes #3549

### What is the new behavior?
Ineffective code has been removed without any changes in the working observed. Also ran all e2e tests to check for errors, none reported.

Documentation update for installation of ChromeDriver on Linux in _docs/developer/end_to_end_tests.md

### Other information?
Is this a breaking change? - No.
How did you test - all E2E tests in /usr/local/submitty/tests/

### CODE REVIEW

File: site/app/views/forum/ForumThreadView.php [hunk 1]
```diff
@@ -608,7 +600,6 @@ public function displayThreadList($threads, $filtering, &$activeThreadAnnounceme
 
 						//fix legacy code
 						$titleDisplay = html_entity_decode($thread['title'], ENT_QUOTES | ENT_HTML5, 'UTF-8');
-						$first_post_content = html_entity_decode($first_post['content'], ENT_QUOTES | ENT_HTML5, 'UTF-8');
```
Comment (andrewaikens87) [inline site/app/views/forum/ForumThreadView.php]: This should be left in. Discussion can be had if there is a need to support the initial version.

Comment (MasterOdin) [reply site/app/views/forum/ForumThreadView.php]: If we're leaving in dead code, it should probably be commented out and with a comment as to why it was left there. Right now, this line is immediately overwritten by the next one (as the next one uses `$first_post['content']` and not `$first_post_content`).

**Comment by MasterOdin** [comment]
Thanks for cleaning up the codebase.
