### PR TITLE
[Bugfix:Submission] Fix viewing/using older notebook versions

### LINKED ISSUE #5288: Rollback on notebook gradeable buggy
**Describe the bug**
If you select a prior version of a gradeable from the dropdown, it displays the autograding results from the prior version correctly, but it still shows the data (e.g., multiple choice selections) from the most recent submission.

### LINKED ISSUE #6080: notebook rendering of version rollback is wrong and/or confusing
**Describe the bug**
If a student submits to a notebook gradeable multiple times, 
and rolls back to a previous version the display of the "currently active" 
answers is confusing.

This may be tied into attempts of the browser page to locally store/display 
recent unsaved/unsubmitted edits to the page.

Student opens multiple tabs / different browsers / different machines.
Could have conflicting locally stored edits on multiple machines.

for each box we could be displaying:
default initial value (might be empty or nonempty depending on config)
Most recent submitted-to-server value
active submitted value (active might not be most recent)
selected submitted value (current selected might not be active nor most recent)
what is in the local browser storage for this assignment on this machine.

also...  pulling from the local storage is buggy if we have logged out & log 
back in as a different user.  It is remember answers or edits done as the other user.

NOTE: I've assigned a bunch of people.  We need to discuss the UI, the code needs to be
very carefully reviewed, and we need to test on every os/browser we can think of that might
have different behavior.  And also write automated tests.

### LINKED ISSUE #6306: Odd behavior on returned exams where version chosen to be graded is not the final version
Not a Submitty contributor, but wanted to point out some strange behavior I noticed when I recently got back an exam using it.
**Describe the bug**
When taking an exam on Submitty, if you make some changes to your answers and choose submit, but then switch to a previous version and select the "grade this version" option, when the graded exam is returned it will be shown strangely.

At the bottom of the page in the "Select Submission Version" box, the last submission will be shown as selected, with the "GRADE THIS VERSION", even though it was not the one actually selected. The answers in any textboxes or multiple choice questions will also show the answers given in that final submission. Switching to a different submission version and then back to this one will change the answers in the boxes back to the actual answers submitted, but the wrong version number will still be marked as "GRADE THIS VERSION".

I'm not quite sure what the expected behavior is here (the existence of the "Use Most Recent Version" buttons confuses me), but as a blank slate user what I would expect to happen would be this: The actual submitted version would be shown in the submission version box as "GRADE THIS VERSION" (even if it is not the last one submitted), and all text boxes/multiple choice questions show the answers given in the version graded by the instructors (*not* the last answers given but the ones chosen to be graded). I wouldn't expect to see a "use most recent version" button at all, but I could imagine maybe a button that allows you to look at your last submission's answer.

**Configuration**
 - OS: Windows 10
 - Browser Chrome

P.S. the text formatting on grade inquiries is broken too

### PR DESCRIPTION
**Pull request by loadedskiffer**
### What is the current behavior?

Currently if a Student is working on a Notebook gradeable and they choose to view an older submission, their most recent answers are displayed instead of the ones that they used for the version they chose to view. 

When a student gets a test back, if they specified an older version as "GRADE THIS VERSION"  the answers they gave for the most recent  submission will be displayed instead of the ones from the selected version. At the bottom of the page in the "Select Submission Version" box, the most recent submission will be shown as selected, with the "GRADE THIS VERSION" .

### What is the new behavior?
closes #6080 
closes #5288
closes #6306

The answers a student gave for a specific submission version will be correctly displayed when choosing between viewing different versions.
 All buttons (clear, reset, recent versions ) and inputs (radio, multiple select, short answer, codebox) are disabled when a student is viewing an older version. 
pr11_1

If there is any provided code for a short answer/codebox the "clear" button now says "reset" to eliminate confusion.
pr11_2

When a student gets a test back, if they specified an older version as "GRADE THIS VERSION"  the answers they gave for that submission will be displayed correctly. At the bottom of the page in the "Select Submission Version" box, the correct submission will be shown as selected, with the "GRADE THIS VERSION" .

The "submit" button now says "Switch To Most Recent Version To Make New Submission" when viewing an older submission.
### Other information?
Testing is easiest with "Notebook basic" in the development course because it has every type of question.

### CODE REVIEW

File: site/app/models/notebook/Notebook.php [hunk 1]
```diff
@@ -155,28 +155,37 @@ private function getMarkdownData($cell) {
...
                     }
                     else {
                         // Else there has been a previous submission try to get it
                         try {
                             // Try to get the most recent submission
                             $recentSubmission = $this->getRecentSubmissionContents($notebookVal['filename'], $version, $student_id);
+                            //get answer for the selected display version
+                            $question_name = $notebookVal['filename'];
+                            $file = fopen("/var/local/submitty/courses/" . $semester . "/" . $course . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name, "r");
+                            $version_answer = fread($file, filesize("/var/local/submitty/courses/" . $semester . "/" . $course . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name));
```
Comment (williamjallen) [inline site/app/models/notebook/Notebook.php:175]: It would be better to use `$this->core->getConfig()->getCoursePath()` here instead of hardcoded paths.  That would also mean that you wouldn't need the `$semester` and `$course` parameters I believe.

File: site/app/models/notebook/Notebook.php [hunk 2]
```diff
@@ -187,9 +196,15 @@ public function getMostRecentNotebookSubmissions(int $version, array $new_notebo
                         try {
                             // Try to get the most recent submission
                             $recentSubmission = $this->getRecentSubmissionContents($notebookVal['filename'], $version, $student_id);
-
+                            //get answer for the selected display version
+                            $question_name = $notebookVal['filename'];
+                            $file = fopen("/var/local/submitty/courses/" . $semester . "/" . $course . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name, "r");
+                            $version_answer = fread($file, filesize("/var/local/submitty/courses/" . $semester . "/" . $course . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name));
```
Comment (williamjallen) [inline site/app/models/notebook/Notebook.php:202]: Same thing here regarding the paths

File: site/app/views/grading/ElectronicGraderView.php [hunk 3]
```diff
@@ -973,7 +973,11 @@ public function hwGradingPage(Gradeable $gradeable, GradedGradeable $graded_grad
             $notebook_data = $notebook_model->getMostRecentNotebookSubmissions(
                 $display_version,
                 $notebook,
-                $graded_gradeable->getSubmitter()->getId()
+                $graded_gradeable->getSubmitter()->getId(),
+                $display_version,
+                $graded_gradeable->getGradeableId(),
+                $this->core->getConfig()->getSemester(),
+                $this->core->getConfig()->getCourse()
```
Comment (williamjallen) [inline site/app/views/grading/ElectronicGraderView.php:980]: These would be able to be removed if the paths were changed.

**Review by williamjallen — CHANGES_REQUESTED** [review]

**Review by eddiekrystowski — CHANGES_REQUESTED** [review]
Mostly tried to break the UI on my review. I was able to break it by following these steps to get around the disabled inputs:
1. Open console
2. change the value of any input using Javascript/JQuery/editing the HTML. For example, I chose a different option on a multiple choice input with `$('#multiple_choice_0_1').prop('checked', 'true');`
3. set `empty_inputs = false;`
4. Manually trigger form submission with `$('#submit').trigger('click')`
5. The page now reloads to the newly made version with some php errors, and some of the inputs (in my case radio/checkbox inputs) have been emptied.

I'm not sure what the intended behavior is here, but perhaps there is a way to just disallow any submission going through on the backend if they are on an inactive version. This also doesn't break the gradeable, they can still scroll past the php errors and resubmit again and the gradeable will be fine.

File: site/app/models/notebook/Notebook.php [hunk 4]
```diff
@@ -171,8 +173,10 @@ public function getMostRecentNotebookSubmissions(int $version, array $new_notebo
                             $recentSubmission = $this->getRecentSubmissionContents($notebookVal['filename'], $version, $student_id);
                             //get answer for the selected display version
                             $question_name = $notebookVal['filename'];
-                            $file = fopen("/var/local/submitty/courses/" . $semester . "/" . $course . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name, "r");
-                            $version_answer = fread($file, filesize("/var/local/submitty/courses/" . $semester . "/" . $course . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name));
+                            $file_path = $this->core->getConfig()->getCoursePath();
+                            $file_path = $file_path . "/submissions/" . $gradeable_id . "/" . $student_id . "/" . $display_version . "/" . $question_name;
```
Comment (williamjallen) [inline site/app/models/notebook/Notebook.php:177]: I overlooked this in my last review but you could also use `FileUtils::joinPaths()` for these paths instead of manually concatenating it.

File: site/app/models/notebook/Notebook.php [hunk 5]
```diff
@@ -198,8 +202,10 @@ public function getMostRecentNotebookSubmissions(int $version, array $new_notebo
...
```
Comment (williamjallen) [inline site/app/models/notebook/Notebook.php:206]: same here

**Review by williamjallen — CHANGES_REQUESTED** [review]

**Review by williamjallen — APPROVED** [review]

**Review by eddiekrystowski — APPROVED** [review]
Works well, I can't break it with the same method as before.

File: site/app/models/notebook/Notebook.php [hunk 6]
```diff
@@ -154,29 +154,42 @@ private function getMarkdownData($cell) {
     * @param array $new_notebook a notebook config to parse
     * @param int $version which version to get notebook submission values from
     * @param string $student_id which student's notebook to pull data from
+    * @param int $display_version selected version (may not be active version)
+    * @param string $gradeable_id
     */
-    public function getMostRecentNotebookSubmissions(int $version, array $new_notebook, string $student_id): array {
+    public function getMostRecentNotebookSubmissions(int $version, array $new_notebook, string $student_id, int $display_version, string $gradeable_id): array {
```
Comment (MasterOdin) [inline site/app/models/notebook/Notebook.php:160]: You've typed this as `int` here but pass in `null` below? If `null` is a valid value, you need to add a `?` before the type, like `?int`.

File: site/app/views/submission/HomeworkView.php [hunk 7]
```diff
@@ -315,13 +315,29 @@ private function renderSubmitBox(Gradeable $gradeable, $graded_gradeable, $versi
...
-                    $notebook,
-                    $this->core->getUser()->getId()
-                );
+            if ($version_instance) {
+                if ($graded_gradeable !== null) {
+                    $notebook_data = $notebook_model->getMostRecentNotebookSubmissions(
+                        $graded_gradeable->getAutoGradedGradeable()->getHighestVersion(),
+                        $notebook,
+                        $this->core->getUser()->getId(),
+                        $version_instance->getVersion() ?? null,
```
Comment (MasterOdin) [inline site/app/views/submission/HomeworkView.php:324]: Can `getVersion()` return something other than `?int` that we need the null coaelescing operator here?

File: site/app/views/submission/HomeworkView.php [hunk 8]
```diff
@@ -417,6 +432,11 @@ private function renderSubmitBox(Gradeable $gradeable, $graded_gradeable, $versi
 
         $highest_version = $graded_gradeable !== null ? $graded_gradeable->getAutoGradedGradeable()->getHighestVersion() : 0;
 
+        $viewing_inactive_version = false;
+        if ($highest_version !== $display_version) {
+            $viewing_inactive_version = true;
+        }
```
Comment (MasterOdin) [inline site/app/views/submission/HomeworkView.php:438]:
```suggestion
        $viewing_inactive_version = $highest_version !== $display_version;
```

File: site/public/js/gradeable-notebook.js [hunk 9]
```diff
@@ -194,15 +190,26 @@ $(document).ready(() => {
...
         }
         else {
-            $(clear_button_id).attr('disabled', false);
+            const value = $(clear_button_id).attr('data-older_version');
+            if (value) {
+                $(clear_button_id).attr('disabled', true);
+            }
+            else {
+                $(clear_button_id).attr('disabled', false);
+            }
```
Comment (MasterOdin) [inline site/public/js/gradeable-notebook.js:199]: Can condense by coercing `value` to a boolean using `!!` notation:
```suggestion
            $(clear_button_id).attr('disabled', !!$(clear_button_id).attr('data-older_version'));
```

File: site/public/js/gradeable-notebook.js [hunk 10]
```diff
@@ -194,15 +190,26 @@ $(document).ready(() => {
...
         else {
-            $(recent_button_id).attr('disabled', false);
-            $('#submit').attr('disabled', false);
+            const value = $(recent_button_id).attr('data-older_version');
+            if (value) {
+                $(recent_button_id).attr('disabled', true);
+            }
+            else {
+                $(recent_button_id).attr('disabled', false);
+            }
```
Comment (MasterOdin) [inline site/public/js/gradeable-notebook.js:212]: same here

File: site/app/templates/submission/homework/SubmitBox.twig [hunk 11]
```diff
@@ -341,8 +342,11 @@
                 "content" : upload_message
             } only %}
         </div>
-
-        <button type="button" id="submit" class="btn btn-success">Submit</button>
+        {% if viewing_inactive_version %}
+            <button type="button" id="submit" class="btn btn-success">Switch To Most Recent Version To Make New Submission</button>
+        {% else %}
+            <button type="button" id="submit" class="btn btn-success">Submit</button>
+        {% endif %}
```
Comment (MasterOdin) [inline site/app/templates/submission/homework/SubmitBox.twig:349]: can condense

File: site/app/templates/notebook/Notebook.twig [hunk 12]
```diff
@@ -230,11 +277,18 @@
...
+                        sa-clear-reset" onclick="deleteFiles({{num_file_submissions}});"
+                        disabled = "disabled">
+                        Clear
+                    </button>
+                {% else %}
+                    <button type="button" class="btn btn-primary
+                        sa-clear-reset" onclick="deleteFiles({{num_file_submissions}});">
+                        Clear
+                    </button>
+                {% endif %}
```
Comment (MasterOdin) [inline site/app/templates/notebook/Notebook.twig:291]: can condense

File: site/app/templates/notebook/Notebook.twig [hunk 13]
```diff
@@ -177,22 +214,32 @@
...
                     {% else %}
-                        $("#mc_{{ num_multiple_choice }}_clear_button").attr("disabled", false);
-                        $("#mc_{{ num_multiple_choice }}_recent_button").attr("disabled", true);
+                        {% if viewing_inactive_version %}
+                            $("#mc_{{ num_multiple_choice }}_clear_button").attr("disabled", true);
+                            $("#mc_{{ num_multiple_choice }}_recent_button").attr("disabled", true);
+                        {% else %}
+                            $("#mc_{{ num_multiple_choice }}_clear_button").attr("disabled", false);
+                            $("#mc_{{ num_multiple_choice }}_recent_button").attr("disabled", true);
+                        {% endif %}
```
Comment (MasterOdin) [inline site/app/templates/notebook/Notebook.twig:242]: condense

File: site/app/templates/notebook/Notebook.twig [hunk 14]
```diff
@@ -177,22 +214,32 @@
...
-                <button type="button" id="mc_{{ num_multiple_choice }}_clear_button" class="btn btn-primary mc-clear">Clear</button>
-                <button type="button" id="mc_{{ num_multiple_choice }}_recent_button" class="btn btn-primary mc-recent">Use Most Recent Submission</button>
-
+                {% if viewing_inactive_version %}
+                    <button type="button" id="mc_{{ num_multiple_choice }}_clear_button" class="btn btn-primary mc-clear" disabled="disabled">Clear</button>
+                    <button type="button" id="mc_{{ num_multiple_choice }}_recent_button" class="btn btn-primary mc-recent" disabled="disabled">Use Most Recent Submission</button>
+                {% else %}
+                    <button type="button" id="mc_{{ num_multiple_choice }}_clear_button" class="btn btn-primary mc-clear">Clear</button>
+                    <button type="button" id="mc_{{ num_multiple_choice }}_recent_button" class="btn btn-primary mc-recent">Use Most Recent Submission</button>
+                {% endif %}
```
Comment (MasterOdin) [inline site/app/templates/notebook/Notebook.twig:223]: condense

File: site/app/templates/notebook/Notebook.twig [hunk 15]
```diff
@@ -134,17 +164,24 @@
...
+                                           disabled = "disabled"
+                                    />
+                                {% else %}
+                                    <input type="checkbox" class="key_to_click" tabindex="0"
+                                           name="multiple_choice_{{ num_multiple_choice }}"
+                                           id="multiple_choice_{{ num_multiple_choice }}_{{ loop.index0 }}"
+                                           value="{{ cell.choices[idx].value }}"
+                                           onclick="handle_input_keypress({{ viewing_inactive_version }});"
+                                    />
+                                {% endif %}
```
Comment (MasterOdin) [inline site/app/templates/notebook/Notebook.twig:183]: condense

**Review by MasterOdin — CHANGES_REQUESTED** [review]

**Comment by MasterOdin** [comment]
@loadedskiffer looks like there's still a number of unaddressed comments above. Looks like they're hidden by default and you'll need to hit the "show more" action to view them.

File: site/app/views/submission/HomeworkView.php (hunk 7 above)
Comment (MasterOdin) [reply site/app/views/submission/HomeworkView.php:324]: Ignoring the comment above, why have the null coalescing operator here? What is it doing?

**Comment by loadedskiffer** [comment]
> @loadedskiffer looks like there's still a number of unaddressed comments above. Looks like they're hidden by default and you'll need to hit the "show more" action to view them.

sorry about that, I didn't see them before.

File: site/app/views/submission/HomeworkView.php (hunk 7 above)
Comment (loadedskiffer) [reply site/app/views/submission/HomeworkView.php]: looks like it's doing nothing, I didn't write that line so I didn't look into it before.

**Review by MasterOdin — APPROVED** [review]
