### PR TITLE
[Bugfix:InstructorUI] Edit user/student bug

### LINKED ISSUE #5232: Edit User/Student bug
**Describe the bug**
When an instructor clicks the first time on the pencil icon next to an existing student on the manage students page, the data loads ok.  But if they press "cancel" (even without editing anything) they get a popup error "warning changes will be lost".  

The second (and future times) they click on the pencil icon next to a student from this page the data does not load correctly, some is missing / incorrect.

This might be related to PR #4996 ?  Or PR #5152 ?  Or something else?

### PR DESCRIPTION
**Pull request by mukul-kmr-jha**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Bug in manage users page. 

### What is the new behavior?
Closes #5232 and adds an alert popup for data loss while editing any student or grader from the pencil icon next to his row ( extends #4996 )

### Other information?
This bug is a result of #4996

### CODE REVIEW

File: site/public/js/userform.js [hunk 1]
```diff
@@ -300,6 +300,13 @@ function clearValidityWarnings() {
 }
 
 function closeButton() {
+  let form = document.querySelectorAll('form')[0];
+  // edit from manage page
+  if($('[name="edit_user"]', form).val() === "true"){
+    clearUserFormInformation();
+    $('#edit-user-form').css('display', 'none');
+    return;
```
Comment (shwehtom89) [inline site/public/js/userform.js:308]: Adding this snippet here prevents the 'Changes to form will be lost' popup from showing up. To recreate, open up the edit user form and make any edit and hit cancel.

Comment (mukul-kmr-jha) [reply site/public/js/userform.js:308]: Hii @shwehtom89 you are right,  no alert is shown for the popup opened from the inline pencil icon. In the PR #4996 changes were asked for the new grader/student popup only.  
However I think as per your suggestions we can expand alert message to this popup (pencil) also. 
Thanks.
