### PR TITLE
[Bugfix:InstructorUI] check uploaded files near size limits

### LINKED ISSUE #11380: course material upload error
**Describe the bug**

We see errors in the logs when instructors upload materials and do not completely fill out the form:

```
14:05:40 01/30/2025 - FATAL ERROR
ValueError (Code: 0) thrown in /usr/local/submitty/site/app/libraries/FileUtils.php (Line 574) by:
           $type = mime_content_type($tmp_name);

Message:
mime_content_type(): Argument #1 ($filename) cannot be empty

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/FileUtils.php(574): mime_content_type()
#1 /usr/local/submitty/site/app/libraries/FileUtils.php(645): app\libraries\FileUtils::app\libraries\{closure}()
#2 /usr/local/submitty/site/app/controllers/course/CourseMaterialsController.php(685): app\libraries\FileUtils::validateUploadedFiles()
#3 unknown file(unknown line): app\controllers\course\CourseMaterialsController->ajaxUploadCourseMaterialsFiles()
#4 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(268): call_user_func_array()
#5 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(246): app\libraries\routers\WebRouter->run()
#6 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()

USER: REDACTED
URL: https://submitty.cs.rpi.edu//courses/s25/REDACTED/course_materials/upload

```

**Expected behavior**

I haven't attempted to reproduce, but instead of this site error message (frog robot -- that may also lose data for any fields/files that have specified on the form) it would be better to have a softer error 'on page' that something is missing.

### PR DESCRIPTION
**Pull request by shailpatels**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

Fixes #11380
### What is the current behavior?
When a file is uploaded to php with a size >= `upload_max_filesize`, the `$_FILES` array still exists, however most of the data is junk. As a result the `$_FILES[file_index]['tmp_name']` which normally points to the tmp area the uploaded file lives in is not guaranteed to exist, which caused the file mine check to fail because it was empty.

see steps to reproduce: https://github.com/Submitty/Submitty/issues/11380#issuecomment-2641893026

### What is the new behavior?
The validation logic will now check if the error flag is set and exit immediately if it is

### CODE REVIEW

**Review by lavalleeale — APPROVED** [review]
Tested and code looks reasonable

File: site/app/libraries/FileUtils.php [hunk 1]
```diff
@@ -569,14 +569,24 @@ public static function validateUploadedFiles(array $files): array {
         $validator = function ($file) {
             $max_size = Utils::returnBytes(ini_get('upload_max_filesize'));
             $name = $file['name'];
+
+            //if the error flag is set for this file, no guarantee tmp_name points to a valid file, exit early
+            if ($file['error'] !== UPLOAD_ERR_OK) {
+                return [
+                    'name' => $name,
+                    'type' => 'Unknown',
```
Comment (williamjallen) [inline site/app/libraries/FileUtils.php:577]: Instead of a magic string value which isn't a valid MIME type, what do you think about using null for the error case instead?

**Review by williamjallen — COMMENTED** [review]
The code looks good overall and I wouldn't be strongly opposed to merging this ASAP if doing so is needed.  I'd like to get clarification on the inline comment I left if there's time though.

File: site/app/libraries/FileUtils.php (hunk 1 above)
Comment (shailpatels) [reply site/app/libraries/FileUtils.php:577]: My expectation is when the UPLLOAD_ERR_OK flag is false, basically the caller will never use the result and just propogate the error forwards.

Looking through the existing uses (just eyeballing) that seems like the case, I'd personally avoid using null just in the off chance someone does try to access the value and doesn't perform a null check because the expectation from the happy path case is this value is always a string.

But thats just my opinion i don't like using null in php due to the weak php type checking so i have no idea if a null is ever actually supposed to be null or its something weird happened.

Not a strong opinion however, happy to change to a null if you'd like to standardize how handle error handling :)

Comment (shailpatels) [reply site/app/libraries/FileUtils.php:577]: Do agree that using an unofficial mime type might cause problems, I could see us using "application/octet-stream" to preserve using a string type, this apparently means just a stream of bytes according to https://stackoverflow.com/questions/1176022/unknown-file-type-mime

Comment (shailpatels) [reply site/app/libraries/FileUtils.php]: Decided to go with null because operating on an unknown mime type would probably have the same effects of null anyways even if the type is same

**Review by williamjallen — APPROVED** [review]
Requested changes addressed.
