### PR TITLE
[Bugfix:SubminiPolls] Add Correct Response Requirement

### LINKED ISSUE #6177: Rainbow Grades fail to build due to Submini polls errors
**Describe the bug**
Rainbow Grades build process results in a core dump

**Expected behavior**
Build finishes successfully, no errors are reported to stdout/stderr.

**To Reproduce**
1.  make pull
2.  make
3. See error

**Configuration**
 - OS: Ubuntu 20.04.2 LTS
 - Browser N/A

**Screenshots**
Build fails with the following errors:
```
/media/sf_sharp/psoft-s21/RainbowGrades/RainbowGrades-main/submini_polls.cpp:75:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<Student*>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   75 |   for (int i = 0; i < students.size(); i++) {
      |                   ~~^~~~~~~~~~~~~~~~~
./process_grades.out by_overall
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
print it   Programming language                     2021-01-25      6 0   234   0
print it ERROR WITH Favorite IDE
process_grades.out: /media/sf_sharp/psoft-s21/RainbowGrades/RainbowGrades-main/submini_polls.cpp:33: std::ostream& operator<<(std::ostream&, const Poll&): Assertion `p.correct_options.size() > 0' failed.
make: *** [/media/sf_sharp/psoft-s21/RainbowGrades/RainbowGrades-main/MakefileHelper:107: overall] Aborted (core dumped)

```

**Additional context**
I just ran Rainbow Grades on another one of my courses with no issues. That course has Submini polls enabled but we did not have any actual polls created or run. For this course (the one I'm having trouble with), we have run Submini polls this semester already.

### PR DESCRIPTION
**Pull request by BenKelly99**
### What is the current behavior?
Closes #6177
Currently, polls are able to be submitted if there are no correct responses.

### What is the new behavior?
Now, each poll is required to have at least 1 correct response.

### CODE REVIEW

**Comment by MasterOdin** [comment]
I was able to hit an error state where on editing a poll, if I de-selected a correct answer, it would then block me from submitting until I added a new question and then marked it as correct. If I got rid of the new question, I would then be blocked again. See https://www.loom.com/share/7685992435fe410f91d5167f55eac9f4 as an example of it.

**Review by MasterOdin — CHANGES_REQUESTED** [review]
I was able to hit an error state where on editing a poll, if I de-selected a correct answer, it would then block me from submitting until I added a new question and then marked it as correct. If I got rid of the new question, I would then be blocked again. See https://www.loom.com/share/7685992435fe410f91d5167f55eac9f4 as an example of it.

**Comment by BenKelly99** [comment]
@MasterOdin the problem with editing should be fixed now.

File: site/app/controllers/PollController.php [hunk 1]
```diff
@@ -152,6 +152,12 @@ public function addNewPoll() {
                 $answers[] = $_POST["option_id_" . $i];
             }
         }
+        if (count($answers) == 0) {
+            $this->core->addErrorMessage("Polls must have at least one correct response");
+            return MultiResponse::RedirectOnlyResponse(
```
Comment (shailpatels) [inline site/app/controllers/PollController.php:157]: If you are returning only 1 response type you can just do
```php
return new RedirectResponse($this->core->buildCourseUrl(['polls'])) 
```

File: site/app/controllers/PollController.php [hunk 2]
```diff
@@ -346,6 +352,12 @@ public function submitEdits() {
...
+                new RedirectResponse($this->core->buildCourseUrl(['polls']))
```
Comment (shailpatels) [inline site/app/controllers/PollController.php:358]: same as above comment

File: site/app/templates/polls/NewPollPage.twig [hunk 3]
```diff
@@ -84,7 +85,7 @@
                     <div id="response_{{response}}_wrapper">
                         <input type="hidden" class="order order-{{index}}" name="order_{{response}}" value="{{index}}"/>
                         <input type="hidden" class="option_id" name="option_id_{{response}}" value="{{response}}"/>
-                        <input aria-label="Is correct" type=checkbox name="is_correct_{{response}}" {{ poll.isCorrect(response) ? "checked": "" }}>
+                        <input aria-label="Is correct" class="correct_box" type=checkbox name="is_correct_{{response}}" {{ poll.isCorrect(response) ? "checked": "" }}>
```
Comment (shailpatels) [inline site/app/templates/polls/NewPollPage.twig:88]: CSS classes and Id's should use dashes instead of underscores:
https://submitty.org/developer/coding_style_guide/css

File: site/app/templates/polls/NewPollPage.twig [hunk 4]
```diff
@@ -224,6 +226,10 @@
             $("#poll-form-submit").prop("disabled", true);
             $(".polls-submit-error").hide();
             $("#response-count-error").show();
+        } else if ($(".correct_box:checked").length == 0) {
```
Comment (shailpatels) [inline site/app/templates/polls/NewPollPage.twig:229]: For JS you should use `===` in order to prevent accidentally implicit type conversions

**Review by shailpatels — CHANGES_REQUESTED** [review]

**Review by MasterOdin — APPROVED** [review]
As indicated in #6177, an update to the website docs would not be amiss to indicate that at least one correct response should be made, and that for polls without any definitive right answer (e.g. asking preferred OS), all answers should be marked as correct.
