### PR TITLE
Fixes statistics and grading complete bar from counting students in the NULL section and unsubmitted assignments

### LINKED ISSUE #1450: grading complete percentage includes unsubmitted assignments
Currently a TA cannot get 100% complete when there are students who didn't submit in their assigned sections.

If the student did not submit, or if they cancelled their submission, the button on the details should be white and labeled "VIEW".  (if the TA needs to change verison or uncancel, they can do that.   If the student didn't submit at all, the TA can still view the extensions / late days table for that student)

The button should be blue only if its ungraded or incomplete grading but there is a submission to grade.

% complete should be out of uncancelled submissions.

### LINKED ISSUE #1489: debug & test TA grading statistics
Make sure the average/stddev only includes students who submitted, and have been graded.

### PR DESCRIPTION
**Pull request by LeonMontealegre**
Also, removes the 'you are one out of 1 being graded' message and adds cancelled submission/version conflict buttons.

Will Fix #1489 and Fix #1450

### CODE REVIEW

File: site/app/libraries/database/DatabaseQueriesPostgresql.php [hunk 1]
```diff
@@ -677,6 +677,39 @@ public function getTotalUserCountByGradingSections($sections, $section_key) {
...
+        $return = array();
+        $params = array();
+        $where = "";
+        if (count($sections) > 0) {
+            // Expand out where clause
+            $sections_keys = array_keys($sections);
+            $where = "WHERE {$section_key} IN (";
+            foreach($sections_keys as $section)
+                $where .= ($section+1) . ($section != $sections_keys[count($sections_keys)-1] ? "," : "");
+            $where .= ")";
```
Comment (MasterOdin) [inline site/app/libraries/database/DatabaseQueriesPostgresql.php]: You should be putting "?" for parameters in your query that get filled in by PDO. This helps for escaping variables and ensuring no potential accidental SQL injections happen. The way this would work is that for every variable in an array, you put a "?" in the query where you want it to be inserted, pass the array to query() and it happens for you (you can see a similar usage of this pattern elsewhere in this file where I used array_fill and implode to get the right number of ? for a IN where clause.
