### PR TITLE
[Bugfix:TAGrading] Fix crashing due to large PDFs

### LINKED ISSUE #11382: Large PDF fails to display in TA grading interface
**Describe the bug**
If a student has uploaded a large pdf file as part of their homework submission, it may be too big for display in the TA grading interface.

Attempting to view a pdf file that was 90.8MB and 12 pages in length crashed with this error:

```
13:51:59 01/30/2025 - FATAL ERROR
app\exceptions\BaseException (Code: 0) thrown in /usr/local/submitty/site/public/index.php (Line 65) by:
      exception_handler(new BaseException("Fatal Error: " . $error['message'] . " in file


Message:
Fatal Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 121638912 bytes) in file
      /usr/local/submitty/site/app/libraries/Output.php on line 265

Stack Trace:
#0 unknown file(unknown line): error_handler()

USER: REDACTED
URL: https://submitty.cs.rpi.edu//courses/s25/REDACTED/gradeable/hw1/encode_pdf
```

NOTE: I believe the pdf is ok (not corrupt), when I clicked on the download link instead i could open the pdf locally with my standard pdf viewer.

**Expected behavior**

We may have a limit for the filesize that can be opened with our pdf annotator or maybe an apache/php memory size limit.  Since we can open reasonably sized files the goal is not necessarily to increase this server configuration limit.  But instead, we should disable the pdfannotator / pdf viewer for large pdfs and only allow the TA user to download these files for local viewing.

### PR DESCRIPTION
**Pull request by raghavg332**
### Please check if the PR fulfils these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behaviour?

Fixes #11382

Currently, if a student uploads a large PDF file, attempting to view it in the TA grading interface causes a fatal error. This results in the grading interface crashing and an "Allowed memory size exhausted" error.

### What is the new behaviour?

- Implemented a file size limit for PDF annotation using ini_get('memory_limit') / 5.
- If the file exceeds this limit, the system will prevent it from loading in the PDF viewer and display a message prompting the user to download it instead.
- Updated the frontend to handle the failure response and alert the user accordingly.

Screenshot 2025-02-08 at 8 20 32 PM

### Other information?

This is not a breaking change.

As a student, upload large PDFs. As an instructor, try to view these PDFs in the TA grading interface. See the PDF, or the error message.

### CODE REVIEW

**Review by lavalleeale — CHANGES_REQUESTED** [review]
I think this code looks good, but the UX of having an alert pop up is pretty annoying for the user, showing the user in a less obtrusive way seems like a better options

**Comment by raghavg332** [comment]
> I think this code looks good, but the UX of having an alert pop up is pretty annoying for the user, showing the user in a less obtrusive way seems like a better options

Resolved it, changed to an on-page display.
Screenshot 2025-02-08 at 6 00 00 PM

**Review by JManion32 — DISMISSED** [review]
I was able to replicate the issue on main with a PDF of size 100mb.
something went wrong

This is the new behavior with the changes:
fixed changes

**Comment by JManion32** [comment]
Tests should clear once you change line 240 from

$("#pdf-error-message").text(pdfData.message).show();

to

$('#pdf-error-message').text(pdfData.message).show();

File: site/public/js/pdf/PDFAnnotateEmbedded.js [hunk 1]
```diff
@@ -234,8 +234,13 @@ function render(gradeable_id, user_id, grader_id, file_name, file_path, page_num
 
                 let pdfData;
                 try {
-                    pdfData = JSON.parse(data)['data'];
-                    pdfData = atob(pdfData);
+                    pdfData = JSON.parse(data);
+                    // Checking if the response is a failure due to large file size
+                    if (pdfData.status === 'fail') {
+                        $("#pdf-error-message").text(pdfData.message).show();
```
Comment (JManion32) [inline site/public/js/pdf/PDFAnnotateEmbedded.js:240]: This should clear the tests:
```suggestion
                        $('#pdf-error-message').text(pdfData.message).show();
```

**Comment by bmcutler** [comment]
@lavalleeale please re-review changes 
thanks

**Review by lavalleeale — COMMENTED** [review]
The client side now looks good to me, I tested with multiple pdfs and the error goes away when viewing smaller pdfs on the same page and comes back when expected.

I'm not sure I want to approve this until @bmcutler weighs in because a hardcoded 20M seems not only potentially over restrictive, but also depending on sysadmin preference might still allow crashes to happen.

If this crash is happening frequently then it probably makes sense to merge this first before finding a permanent solution, of which it looks like there are two options:
1. Use a combination of `memory_get_usage` and `ini_get('memory_limit')` to find the limit at runtime
2. try/catch the global json rendering at https://github.com/Submitty/Submitty/blob/2521492c5132b68003a7f93a543fc90be4e4b685/site/app/libraries/Output.php#L264-L268 and return a slightly more generic error message there

Along with these 2, this function could be optimized to allow pdfs to be about 2.5x larger without using more memory because a quick code search seems to indicate that base64 and json encoding the pdf are only done to immediately decode them client-side.

**Review by JManion32 — APPROVED** [review]
After thorough testing, we now use the system limit for memory usage instead of hardcoding it. This was achieved by taking the memory limit and dividing by 5, which seems to allow PDFs to be encoded up to 25mB, and then displays the error message suggesting that the user download it after.

**Review by lavalleeale — APPROVED** [review]
Tested and reviewed code and looks good to me, though if someone is interested this does show that this function is very inefficient and could handle much larger PDFs if they were not in memory multiple times.
