### PR TITLE
[Bugfix:Submission] Notebook Copy In Multiple Choice

### LINKED ISSUE #8345: Markdown multiple choice duplicates
**Describe the bug**
If a notebook/markdown gradeable has duplicate values, the gradeable will build fine and produce unexpected behavior to the student submitting. If 2 options had the same value, the website may pick the incorrect value to set when loading the page.

**Expected behavior**
The gradeable should just not build successfully because not all values were unique.

**To Reproduce**
1. Create a notebook/markdown gradeable config with a multiple choice but have duplicate values.
2. Build the gradeable on Submitty
3. Pick the higher order option and submit
4. See that after the refresh, the option changed to the lower one

See comments for a full example

### PR DESCRIPTION
**Pull request by 04vmatsibekker**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #8345. If there is a multiple choice where two of the values are the same, the notebook gradeable will be built.

### What is the new behavior?
The Notebook will not be built and will display an error message.

### CODE REVIEW

File: grading/load_config_json.cpp [hunk 1]
```diff
@@ -1813,6 +1813,16 @@ nlohmann::json ValidateANotebook(const nlohmann::json& notebook, const nlohmann:
               assert(value != "");
               assert(description != "");
 
+              auto it_next = it;
+              for (++it_next; it_next != choices.end(); ++it_next){
```
Comment (williamjallen) [inline grading/load_config_json.cpp:1814]: I believe this variable declaration can be moved into the for-loop declaration

File: grading/load_config_json.cpp [hunk 2]
```diff
@@ -1813,6 +1813,16 @@ nlohmann::json ValidateANotebook(const nlohmann::json& notebook, const nlohmann:
...
+
+                nlohmann::json choice_next = it_next.value();
+                std::string value_next = choice_next.value("value", "");
+                if (value == value_next)
+                  std::cout  << "ERROR: " << it.value() << " == " << it_next.value() << std::endl;
```
Comment (williamjallen) [inline grading/load_config_json.cpp:1819]:
```suggestion
                if (value == value_next) {
                  std::cout  << "ERROR: " << it.value() << " == " << it_next.value() << std::endl;
                }
```

Comment (williamjallen) [inline grading/load_config_json.cpp:1819]: This error message isn't very descriptive.  It would be better to indicate both the problem and a suggested resolution.

**Review by williamjallen — CHANGES_REQUESTED** [review]

**Comment by 04vmatsibekker** [comment]
@williamjallen
Does the new text that is outputted as the error message look better?

**Comment by williamjallen** [comment]
The code changes seem reasonable to me.  I'll leave the feature/functionality review to someone more knowledgeable about this part of the codebase.

**Review by Eceptonsu — APPROVED** [review]
Tested on my machine, works well.
