### PR TITLE
[Bugfix:TAGrading] Underscore annotations bug

### LINKED ISSUE #4779: Bugs with current loading implementation of annotation files
**Describe the bug**
The current system uses just the filename + _ + user_id for the name of the annotation files. This fails to work if we have underscores in the user_id (as it assumes the last split will always be full user_id) and also if we have the same filename at multiple points in a folder hierarchy (through git). If you have say `filename` in `folder1/` and `folder2/` and make annotations in one PDF, then when you open the other PDF, it will attempt to load the annotations for it.

**Expected behavior**
Annotation file should load properly and with the right annotations.

**Proposed Solution**

 I'd rather us just create a md5 hash of the filepath + grader_id and use that to store the annotations. The filepath and grader_id should be stored within the PDF for convenience when looking at the file by a human. For example, assume the following directory tree and annotations being done by `user_1`:

```
filename.pdf
filename2.pdf
folder/
  filename.pdf
```

I would expect the annotation folder to have:

```
md5("filename.pdf" + "user_1")
md5("filename2.pdf" + "user_1")
md5("folder/filename.pdf" + "user_1")
```

all of these are probably going to be unique. There's a chance of collisions, but it's probably not significant enough to worry about in the real world usage.

### PR DESCRIPTION
**Pull request by jchulton**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Fixes #4779
If a user with a underscore in their user_id makes pdf annotations, the annotations cannot be properly loaded. This is annotation files are saved in the format filename_graderid.json. The filename and graderid are found from the annotation file name by exploiding on the '_' and filename and graderid are needed to load the annotations.

### What is the new behavior?
Annotation files are saved using the directory structure filename/grader_id.json, instead of filename_graderid.json. This will allow annotations made by users with underscores in their user_ids to be loaded properly

### CODE REVIEW

**Comment by MasterOdin** [comment]
I've updated the linked issue to describe another bug with the current implementation, and my proposed solution for it. Given that this particular bug is not something that affects RPI, I think we should aim to fix both at the same time, if just to make the migrations a bit simpler.

**Comment by jchulton** [comment]
I have implemented the fix described in the issue, but this does not fully fix the issue. It looks like the pdf annotation does not try to load from a new annotation file when switching to annotate another pdf with the same name. I plan to address this in a future PR

File: site/app/controllers/pdf/PDFController.php [hunk 1]
```diff
@@ -113,13 +101,20 @@ public function savePDFAnnotation($gradeable_id) {
...
-        if (strpos($annotation_info['file_name'], '..') !== false) {
-            return false;
-        }
-
-        $new_file_name = preg_replace('/\\.[^.\\s]{3,4}$/', '', $annotation_info['file_name']) . "_" . $grader_id . '.json';
-        file_put_contents(FileUtils::joinPaths($annotation_version_path, $new_file_name), $annotation_layer);
+        
+        $partial_path = substr_replace($annotation_info["file_path"], "", 0, strlen($annotation_version_path) + 1);
+        
+        $annotation_layer_decoded = json_decode($_POST['annotation_layer'], true);
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:107]: what does this JSON object look like with two annotations?

Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php:107]: Only the first annotation is labeled with the grader_id and partial_path. I've updated to label each annotation with the partial path and grader_id.

Comment (MasterOdin) [reply site/app/controllers/pdf/PDFController.php:107]: can you post a sample JSON object here of two annotations?

Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php:107]: Each of the annotations are labeled with the grader_id and file_path

Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php:107]: Github can't process the file for some reason, here are the contents [{"type":"drawing","width":5.5,"color":"#FF0000","lines":[["100.14","61.15"],["104.14","63.44"],["109.86","65.15"],["115.57","66.87"],["124.14","69.72"],["131.57","72.58"],["144.14","78.29"],["160.71","86.87"],["179.00","97.15"],["193.29","104.01"],["207.57","112.01"],["220.71","119.44"],["233.86","128.01"],["243.00","133.72"],["250.43","138.29"],["255.57","141.72"],["260.14","146.29"],["264.14","149.72"],["267.57","152.01"],["269.86","152.58"],["273.29","154.29"],["276.14","154.87"],["279.00","155.44"],["282.43","155.44"],["286.43","154.29"],["292.14","151.44"],["297.29","147.44"],["304.71","139.44"],["312.14","127.44"],["318.43","112.58"],["320.71","98.87"],["322.43","91.44"],["322.43","86.87"],["322.43","84.58"],["319.57","82.87"],["312.14","80.01"],["300.71","78.87"],["284.14","80.58"],["260.14","87.44"],["225.86","95.44"],["164.14","108.01"],["144.71","113.15"],["135.00","116.01"],["132.14","116.58"]],"class":"Annotation","uuid":"241c4a9b-646e-43d6-9a26-32255eeace4e","page":1,"userId":"instructor","file_path":"summary 21 1 page.pdf","grader_id":"instructor"},{"type":"drawing","width":5.5,"color":"#FF0000","lines":[["327.90","47.89"],["329.44","48.66"],["331.75","49.43"],["334.83","50.97"],["337.14","51.74"],["340.22","53.28"],["343.30","55.59"],["346.38","57.13"],["351.77","59.45"],["356.39","63.30"],["361.78","67.15"],["367.17","69.46"],["372.56","73.31"],["379.49","77.16"],["384.88","81.01"],["391.81","84.86"],["398.74","88.71"],["404.13","93.33"],["411.06","96.41"],["416.46","101.03"],["423.39","104.11"],["428.78","107.96"],["432.63","110.27"],["440.33","114.12"],["444.18","116.43"],["449.57","119.51"],["454.19","121.05"],["457.27","122.59"],["459.58","123.36"],["463.43","125.67"],["467.28","126.44"],["469.59","126.44"],["471.13","127.21"],["473.44","127.98"],["474.21","128.75"],["474.98","128.75"],["475.75","128.75"],["477.29","128.75"],["478.83","128.75"],["481.14","128.75"],["482.68","127.98"],["484.99","125.67"],["488.84","124.13"],["491.15","121.82"],["494.23","119.51"],["497.31","116.43"],["498.85","114.12"],["501.93","110.27"],["504.24","106.42"],["505.78","103.34"],["506.55","99.49"],["507.32","97.18"],["508.09","94.10"],["508.09","91.79"],["508.09","88.71"],["505.78","85.63"],["503.47","82.55"],["500.39","77.93"],["496.54","73.31"],["491.92","70.23"],["488.07","66.38"],["483.45","62.53"],["478.06","59.45"],["473.44","57.13"],["469.59","55.59"],["466.51","54.82"],["464.20","54.82"],["461.89","54.82"],["460.35","54.82"],["458.81","54.82"],["457.27","56.36"],["456.50","58.68"],["454.19","63.30"],["452.65","68.69"],["451.11","71.77"],["448.80","80.24"],["445.72","87.17"],["442.64","92.56"],["440.33","97.95"],["438.02","103.34"],["435.71","107.96"],["434.17","113.35"],["431.86","116.43"],["429.55","121.82"],["428.78","125.67"],["428.01","132.60"],["428.01","139.53"],["428.01","145.69"],["428.01","151.85"],["428.01","158.79"],["428.01","162.64"],["428.78","167.26"],["428.78","169.57"],["429.55","171.88"],["429.55","173.42"],["430.32","174.19"],["431.09","174.19"],["431.86","174.19"],["433.40","174.19"],["435.71","174.19"],["438.79","173.42"],["444.18","172.65"],["448.03","170.34"],["454.96","168.80"],["461.12","165.72"],["468.05","161.87"],["474.98","158.79"],["481.14","154.93"],["486.53","153.39"],["495.00","149.54"],["500.39","146.46"],["505.78","144.15"],["510.40","141.07"],["515.03","138.76"],["518.11","136.45"],["520.42","134.91"],["521.96","133.37"],["523.50","131.83"],["524.27","130.29"],["524.27","128.75"],["525.04","127.98"],["525.04","124.90"],["525.04","122.59"],["524.27","119.51"],["521.96","116.43"],["518.88","111.04"],["516.57","105.65"],["511.94","100.26"],["508.09","94.87"],["501.16","85.63"],["495.00","78.70"],["488.07","71.77"],["481.14","64.84"],["474.21","57.91"],["467.28","52.51"],["461.89","47.89"],["456.50","45.58"],["450.34","41.73"],["446.49","40.19"],["441.87","39.42"],["438.79","38.65"],["435.71","37.88"],["431.86","37.88"],["426.47","37.88"],["421.08","37.88"],["415.69","39.42"],["409.52","42.50"],["403.36","47.12"],["398.74","52.51"],["393.35","59.45"],["387.96","66.38"],["384.11","72.54"],["381.03","78.70"],["377.18","82.55"],["374.87","85.63"],["371.79","89.48"],["370.25","91.79"],["367.94","94.10"],["367.17","95.64"],["365.63","97.95"],["365.63","99.49"],["364.86","101.03"],["364.86","102.57"],["364.86","105.65"],["364.86","108.73"],["364.86","112.58"],["364.86","117.20"],["365.63","121.05"],["366.40","125.67"],["368.71","129.52"],["369.48","134.14"],["371.02","136.45"],["372.56","139.53"],["374.10","141.84"],["374.87","144.15"],["376.41","146.46"],["377.95","148.00"],["378.72","148.77"],["379.49","149.54"],["380.26","151.08"],["381.03","152.62"],["382.57","154.16"],["384.11","155.70"],["386.42","158.02"],["388.73","159.56"],["391.04","161.10"],["391.81","162.64"],["394.12","164.18"],["394.89","164.95"],["396.43","164.95"],["396.43","165.72"],["397.97","165.72"],["398.74","165.72"],["399.51","165.72"],["400.28","166.49"],["401.82","166.49"],["402.59","166.49"],["403.36","166.49"]],"class":"Annotation","uuid":"738f1083-2f89-4bbd-b4c1-00f2d715ef5e","page":1,"userId":"instructor","file_path":"summary 21 1 page.pdf","grader_id":"instructor"},{"type":"drawing","width":5.5,"color":"#FF0000","lines":[["200.06","25.56"],["201.60","25.56"],["203.14","26.33"],["205.45","26.33"],["208.53","27.10"],["211.61","27.87"],["216.24","28.64"],["221.63","29.41"],["225.48","29.41"],["231.64","31.72"],["237.80","32.49"],["244.73","34.03"],["252.43","34.80"],["260.90","36.34"],["268.60","37.88"],["277.07","40.19"],["284.77","40.96"],["292.47","42.50"],["300.17","44.04"],["307.87","44.81"],["314.04","45.58"],["319.43","46.35"],["324.82","48.66"],["329.44","48.66"],["331.75","49.43"],["334.06","50.20"],["336.37","50.20"],["337.14","50.97"]],"class":"Annotation","uuid":"7a2d1ea2-58a6-4f03-9868-31353a1ddb05","page":1,"userId":"instructor","file_path":"summary 21 1 page.pdf","grader_id":"instructor"}]

**Comment by MasterOdin** [comment]
I messed up on understanding the problem in my original description. By encoding the entire name in md5 hash, it makes it impossible to do an efficient look-up of specific files. We should be only doing a md5 hash of the file path and can leave the grader_id alone and just have `md5_hash(file_path) . "_" . grader_id . ".json"` as the filename. We do want to have to read every possible annotation file to find the ones related to a specific file / gradeable as while it'll probably work fine for most cases, it does not scale particular well, especially if we apply this to peer grading on something with a bunch of PDFs.

**Comment by jchulton** [comment]
The new filepath of annotations is now md5_hash(file_path) . "_" . grader_id . ".json

File: site/app/controllers/pdf/PDFController.php [hunk 2]
```diff
@@ -30,24 +30,13 @@ public function showStudentPDF($gradeable_id, $filename, $path) {
...
-                        if ($pdf_id . '.pdf' === $filename) {
-                            $annotation_jsons[$grader_id] = file_get_contents($fileinfo->getPathname());
-                        }
-                    }
-                }
+        if (is_dir($annotation_dir)) {
+            foreach (scandir($annotation_dir) as $annotation_file) {
+                $annotation_decoded = json_decode($annotation_file);
+                $grader_id = $annotation_decoded["userId"];
+                $annotation_jsons[$grader_id] = file_get_contents(FileUtils::joinPaths($annotation_dir, $annotation_file));
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:39]: For this, and other loops over the annotation directory, we need to limit to grabbing only annotations for the set filename. The reason for doing a md5 hash of just the file path is then within this loop (and others like it), we can do a compare of `explode('_', $annotation_file)[0] === md5($filename)` or something.

File: site/app/controllers/pdf/PDFController.php (hunk 1 above)
Comment (MasterOdin) [reply site/app/controllers/pdf/PDFController.php:107]: Can we restructure this to be:
```
{
  "grader_id": "instructor",
  "file_path": "summary 21 1 page.pdf",
  "annotations: [ ... ]
}
```
We should not be modifying the annotation objects so that it's a lossless round-tripping between Submitty and pdf-annotate.js.

File: site/app/controllers/pdf/PDFController.php [hunk 3]
```diff
@@ -157,24 +151,14 @@ public function showGraderPDFEmbedded($gradeable_id) {
             }
         }
         $active_version = $graded_gradeable->getAutoGradedGradeable()->getActiveVersion();
-        $annotation_path = FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), 'annotations', $gradeable_id, $id, $active_version);
+        $annotation_dir = preg_replace('/\\.[^.\\s]{3,4}$/', '', FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), 'annotations', $gradeable_id, $id, $active_version));
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:154]: what is this regex doing?

Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php:154]: The problem with the restructure is trying to render the annotations with that format leads to the following error. It looks to mean like its somewhere in the annotate.js library
image

File: site/app/controllers/pdf/PDFController.php (hunk 2 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: This has been added in the latest commit

File: site/app/controllers/pdf/PDFController.php (hunk 3 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: I'm unsure what the regex does. It was in master, but seems unneeded. I've removed it.

File: site/app/controllers/pdf/PDFController.php (hunk 1 above)
Comment (MasterOdin) [reply site/app/controllers/pdf/PDFController.php:110]: I assume you meant to reply here with that error, and not in the thread about the regex.

Yes, you would need to also edit where we're loading the file into localStorage: https://github.com/Submitty/Submitty/blob/e004c21305c42251ebc147c128843ff130096a1b/site/app/templates/grading/electronic/PDFAnnotationEmbedded.twig#L20-L25

I would recommend looking over the [`LocalUserStoreAdapter`](https://github.com/Submitty/pdf-annotate.js/blob/master/src/adapter/LocalUserStoreAdapter.js) of the pdf-annotate.js library if you have not yet already.

File: site/app/controllers/pdf/PDFController.php (hunk 3 above)
Comment (MasterOdin) [reply site/app/controllers/pdf/PDFController.php]: It's to remove the extension. The regex is roughly literal period + 3-4 non-whitespace characters.

Anyway, this regex is in a couple of other places and I think you can remove it in each place since the path is never going to have an extension we want to remove.

**Comment by bmcutler** [comment]
@MasterOdin 
Please rereview and approve or request changes ASAP.

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+                    for name in files:
+                        if "_" in name:
+                            file_name = name.split('_', 1)[0]
+                            grader_id = name.split('_', 1)[1]
+                            #Hash folder + file_name + grader_id where folder is the directory structure after the version directory
+                            md5_file_name = hashlib.md5((dirPath + file_name).encode())
+                            file_path = Path(annotations_dir, dir, dirSecond, dirThrid)
+                            copyfile(Path(dirPath,name), Path(dirPath, md5_file_name.hexdigest() + "_" + grader_id + '.json'))
+                            os.remove(Path(dirPath,name))
+                            os.system("chown -R "+php_user+":"+course_group+ " "+ str(dirPath))
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:35]:
```suggestion
                            shutil.chown(dirPath, php_user, course_group)
```

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+                            os.system("chmod -R u+rwx "+str(dirPath))
+                            os.system("chmod -R g+rxs "+str(dirPath))
+                            os.system("chmod -R o-rwx "+str(dirPath))
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:38]: Can we use [`os.chmod`](https://docs.python.org/3/library/os.html#os.chmod) here?

File: site/app/controllers/pdf/PDFController.php [hunk 6]
```diff
@@ -30,31 +30,24 @@ public function showStudentPDF($gradeable_id, $filename, $path) {
         $submitter = $this->core->getQueries()->getSubmitterById($id);
         $graded_gradeable = $this->core->getQueries()->getGradedGradeableForSubmitter($gradeable, $submitter);
         $active_version = $graded_gradeable->getAutoGradedGradeable()->getActiveVersion();
-        $annotation_path = FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), 'annotations', $gradeable_id, $id, $active_version);
+        $annotation_dir = preg_replace('/\\.[^.\\s]{3,4}$/', '', FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), 'annotations', $gradeable_id, $id, $active_version));
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:33]: you can remove this regex here

File: site/app/controllers/pdf/PDFController.php [hunk 7]
```diff
@@ -30,31 +30,24 @@ public function showStudentPDF($gradeable_id, $filename, $path) {
...
-                        $pdf_id = implode('_', array_slice($pdf_info, 0, -1));
-                        $grader_id = $pdf_info[count($pdf_info) - 1];
-                        if ($pdf_id . '.pdf' === $filename) {
-                            $annotation_jsons[$grader_id] = file_get_contents($fileinfo->getPathname());
-                        }
-                    }
+        if (is_dir($annotation_dir)) {
+            foreach (scandir($annotation_dir) as $annotation_file) {
+                if (explode('_', $annotation_file)[0] === md5($decoded_path)) {
+                    $annotation_decoded = json_decode($annotation_file);
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:40]: this does not work. Need to read in the file contents first.

File: site/app/controllers/pdf/PDFController.php [hunk 8]
```diff
@@ -174,12 +167,19 @@ public function savePDFAnnotation($gradeable_id, $target_dir) {
...
-            return false;
+        
+        $partial_path = substr_replace($annotation_info["file_path"], "", 0, strlen($annotation_version_path) + 1);
+        
+        $annotation_layer_decoded = json_decode($_POST['annotation_layer'], true);
+        
+        for ($i = 0; $i < count($annotation_layer_decoded); $i++) {
+            $annotation_layer_decoded[$i]["file_path"] = $partial_path;
+            $annotation_layer_decoded[$i]["grader_id"] = $grader_id;
         }
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:178]: as I've said before, remove this. The file_path and grader_id information should be stored at the top level of the json file with annotations then stored underneath an `annotations` key. We should not be modifying the annotations directly so as to not worry about interop issues with pdf-annotate.js.

File: site/app/controllers/pdf/PDFController.php [hunk 9]
```diff
@@ -222,23 +222,16 @@ public function showGraderPDFEmbedded($gradeable_id) {
...
-                            $annotation_jsons[$grader_id] = file_get_contents($fileinfo->getPathname());
-                        }
+        $file_path = $_POST['file_path'];
+        if (is_dir($annotation_dir)) {
+            foreach (scandir($annotation_dir) as $annotation_file) {
+                if (explode('_', $annotation_file)[0] === md5($file_path)) {
+                    $annotation_decoded = json_decode(file_get_contents(FileUtils::joinPaths($annotation_dir, $annotation_file)), true);
+                    if ($annotation_decoded != null) {
+                        $grader_id = $annotation_decoded[0]["userId"];
+                        $annotation_jsons[$grader_id] = file_get_contents(FileUtils::joinPaths($annotation_dir, $annotation_file));
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:234]: let's restructure this so we only read in the file once

File: site/app/views/AutoGradingView.php [hunk 10]
```diff
@@ -399,14 +401,14 @@ public function showTAResults(TaGradedGradeable $ta_graded_gradeable, bool $regr
...
             $first_file = scandir($annotation_path)[2];
             $annotation_path = FileUtils::joinPaths($annotation_path, $first_file);
-            if (is_file($annotation_path)) {
-                $dir_iter = new \DirectoryIterator(dirname($annotation_path . '/'));
-                foreach ($dir_iter as $fileinfo) {
-                    if (!$fileinfo->isDot()) {
-                        $no_extension = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fileinfo->getFilename());
+            if (is_dir($annotation_path)) {
+                $dir_iter = new \DirectoryIterator($annotation_path);
+                foreach ($dir_iter as $fileInfo) {
```
Comment (MasterOdin) [inline site/app/views/AutoGradingView.php:406]: snake_case variables: `$file_info`

File: site/app/views/AutoGradingView.php [hunk 11]
```diff
@@ -608,17 +609,14 @@ public function showPeerResults(TaGradedGradeable $ta_graded_gradeable, bool $re
...
+            if (is_dir($annotation_path)) {
                 $dir_iter = new \DirectoryIterator(dirname($annotation_path . '/'));
-                foreach ($dir_iter as $fileinfo) {
-                    if (!$fileinfo->isDot()) {
-                        $no_extension = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fileinfo->getFilename());
-                        $pdf_info = explode('_', $no_extension);
-                        $pdf_id = implode("_", array_slice($pdf_info, 0, -1));
-                        if (file_get_contents($fileinfo->getPathname()) != "") {
-                            $pdf_id = $pdf_id . '.pdf';
+                foreach ($dir_iter as $dirInfo) {
```
Comment (MasterOdin) [inline site/app/views/AutoGradingView.php:616]: snake_case variables: `$dir_info`

File: site/app/views/AutoGradingView.php [hunk 12]
```diff
@@ -608,17 +609,14 @@ public function showPeerResults(TaGradedGradeable $ta_graded_gradeable, bool $re
...
+                    if ($dirInfo->isDir() && !$dirInfo->isDot() && count(scandir($dirInfo->getPathname()))) {
+                        if (file_get_contents($dirInfo->getPathname()) != "") {
```
Comment (MasterOdin) [inline site/app/views/AutoGradingView.php:618]: use `!==`

File: site/app/views/AutoGradingView.php [hunk 13]
```diff
@@ -608,17 +609,14 @@ public function showPeerResults(TaGradedGradeable $ta_graded_gradeable, bool $re
         $annotation_path = FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), 'annotations', $gradeable->getId(), $id, $active_version);
         $annotated_file_names = [];
         if (is_dir($annotation_path) && count(scandir($annotation_path)) > 2) {
-            $first_file = scandir($annotation_path)[2];
-            $annotation_path = FileUtils::joinPaths($annotation_path, $first_file);
-            if (is_file($annotation_path)) {
+            //$first_file = scandir($annotation_path)[2];
+            //$annotation_path = FileUtils::joinPaths($annotation_path, $first_file);
+            if (is_dir($annotation_path)) {
                 $dir_iter = new \DirectoryIterator(dirname($annotation_path . '/'));
```
Comment (MasterOdin) [inline site/app/views/AutoGradingView.php:615]: Use a [`FilesystemIterator`](https://www.php.net/manual/en/class.filesystemiterator.php) which will skip dots for you.

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 14]
```diff
@@ -0,0 +1,43 @@
...
+    # get course group
+    stat_info = os.stat(str(course_dir))
+    course_group_id = stat_info.st_gid
+    course_group = grp.getgrgid(course_group_id)[0]
+    
+    #Go down to version directory.
+    for dir in os.listdir(annotations_dir):
+        for dirSecond in os.listdir(Path(annotations_dir, dir)):
+            for dirThrid in os.listdir(Path(annotations_dir, dir, dirSecond)):
+                for dirPath, dirName, files in os.walk(Path(annotations_dir, dir, dirSecond, dirThrid)):
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:25]: Is there sub-directories as part of this walk?

File: site/app/controllers/pdf/PDFController.php (hunk 8 above)
Comment (MasterOdin) [reply site/app/controllers/pdf/PDFController.php:178]: Namely, this structure:
```
{
  "grader_id": "instructor",
  "file_path": "summary 21 1 page.pdf",
  "annotations: [ ... ]
}
```

You'll have to modify where the annotation layers are being read into memory for display either in the PHP or JS to avoid the error you posted above in an unrelated comment.

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 15]
```diff
@@ -0,0 +1,51 @@
...
+                            [file_name, grader_id] = name.split('_', 1)
+                            submissions_full_path = annotation_full_path.replace("annotations", "submissions");
+                            md5_file_name = hashlib.md5((submissions_full_path + '/' + file_name + '.pdf').encode())
+                            #Hash folder + file_name + grader_id where folder is the directory structure after the version directory
+                            json_data = {};
+                            for submission_root, submission_dirs, submission_files in os.walk(submissions_full_path):
+                                for submission_file in submission_files:
+                                    if(submission_file[:-4] == file_name):
+                                        md5_file_name = hashlib.md5((os.path.abspath(os.path.join(submission_root, submission_file))).encode())
+                            with open(Path(annotation_full_path,name)) as initial_file:
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:35]: `Path(annotation_full_path, name).open()`

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 16]
```diff
@@ -0,0 +1,51 @@
...
+                                json_data['annotations'] = json.dumps(json.load(initial_file))
+                            json_data['grader_id'] = grader_id[:-5]
+                            json_data['file_name'] = file_name
+                            file_path = Path(annotations_dir, gradeable_level_dir, user_level_dir, version_level_dir)
+                            new_json_file = open(Path(annotation_full_path, md5_file_name.hexdigest() + "_" + grader_id), 'x')
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:40]: why mode `x` here?

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 17]
```diff
@@ -0,0 +1,51 @@
...
+                            json.dump(json_data, new_json_file)
+                            new_json_file.close()
+                            os.remove(Path(annotation_full_path,name))
+                            os.system("chown -R "+php_user+":"+course_group+ " "+ str(annotation_full_path))
+                            os.system("chmod -R u+rwx "+str(annotation_full_path))
+                            os.system("chmod -R g+rxs "+str(annotation_full_path))
+                            os.system("chmod -R o-rwx "+str(annotation_full_path))
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:47]: Can we use the builtin `os.chown` and `os.chmod` with a loop over files of `annotation_full_path` (using `os.scandir` or `Path(annotation_full_path).iterdir()`).

We want to avoid `os.system` as if it fails, it will do so silently, and the migration will be marked as having passed, which it has not, causing a potential break in functionality, or us having bad permissions on things.

File: site/app/controllers/pdf/PDFController.php [hunk 18]
```diff
@@ -87,21 +84,20 @@ public function downloadStudentPDF($gradeable_id, $filename, $path) {
...
-            if (is_file($annotation_path)) {
-                $dir_iter = new \DirectoryIterator(dirname($annotation_path . '/'));
-                foreach ($dir_iter as $fileinfo) {
-                    if (!$fileinfo->isDot()) {
-                        $no_extension = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fileinfo->getFilename());
-                        $pdf_info = explode('_', $no_extension);
-                        $pdf_id = implode('_', array_slice($pdf_info, 0, -1));
-                        $grader_id = $pdf_info[count($pdf_info) - 1];
+        if (is_dir($annotation_path)) {
+            $dir_iter = new \DirectoryIterator($annotation_path);
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:88]: Use [`FileSystemIterator`](https://www.php.net/manual/en/class.filesystemiterator.php) and we can avoid the `isDot` check below.

File: site/app/controllers/pdf/PDFController.php [hunk 19]
```diff
@@ -87,21 +84,20 @@ public function downloadStudentPDF($gradeable_id, $filename, $path) {
...
+            foreach ($dir_iter as $file_info) {
+                if ($file_info->isFile() && !$file_info->isDot()) {
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:90]: When would `$annotation_path` contain anything but files?

File: site/app/controllers/pdf/PDFController.php [hunk 20]
```diff
@@ -87,21 +84,20 @@ public function downloadStudentPDF($gradeable_id, $filename, $path) {
...
+                    $no_extension = preg_replace('/\\.[^.\\s]{3,4}$/', '', $file_info->getFilename());
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:91]: can delete this, unused

File: site/app/controllers/pdf/PDFController.php [hunk 21]
```diff
@@ -225,23 +227,17 @@ public function showGraderPDFEmbedded($gradeable_id) {
...
-                        if ($pdf_id . '.pdf' === $filename) {
-                            $annotation_jsons[$grader_id] = file_get_contents($fileinfo->getPathname());
-                        }
+        $file_path = $_POST['file_path'];
+        if (is_dir($annotation_dir)) {
+            foreach (scandir($annotation_dir) as $annotation_file) {
+                if (explode('_', $annotation_file)[0] === md5($file_path)) {
+                    $file_contents = file_get_contents(FileUtils::joinPaths($annotation_dir, $annotation_file));
+                    $annotation_decoded = json_decode($file_contents, true);
+                    if ($annotation_decoded != null) {
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:238]: use `!==`

File: site/app/views/AutoGradingView.php [hunk 22]
```diff
@@ -627,17 +625,12 @@ public function showPeerResults(TaGradedGradeable $ta_graded_gradeable, bool $re
...
-                        $no_extension = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fileinfo->getFilename());
-                        $pdf_info = explode('_', $no_extension);
-                        $pdf_id = implode("_", array_slice($pdf_info, 0, -1));
-                        if (file_get_contents($fileinfo->getPathname()) != "") {
-                            $pdf_id = $pdf_id . '.pdf';
+            if (is_dir($annotation_path)) {
+                $dir_iter = new \FilesystemIterator(dirname($annotation_path));
+                foreach ($dir_iter as $dir_info) {
+                    if ($dir_info->isDir() && count(scandir($dir_info->getPathname()))) {
+                        if (file_get_contents($dir_info->getPathname()) !== "") {
```
Comment (MasterOdin) [inline site/app/views/AutoGradingView.php:632]: This makes no sense to me. Why are you checking for empty directories and then attempting to do a `file_get_contents` on said empty directory (which would error with `Is a directory`)?

File: site/app/controllers/pdf/PDFController.php [hunk 23]
```diff
@@ -57,7 +54,7 @@ public function showStudentPDF($gradeable_id, $filename, $path, $grader = null)
             "gradeable_id" => $gradeable_id,
             "id" => $id,
             "file_name" => $filename,
-            "file_path" => urldecode($path),
+            "file_path" => urldecode($decoded_path),
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:57]: why are we double `urldecode` on this path? Not sure if there's an actual harm in this, but also should avoid if we do not have to.

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py (hunk 16 above)
Comment (jchulton) [reply migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:40]: We need to create a new json file, since the json file should include the file_path and grader_id, hence the x mode

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py (hunk 17 above)
Comment (jchulton) [reply migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:47]: Barb and I discussed this, and decided that it was alright ot use this method despite the flaws as this is a one-time migration and this is how other migrations are written.

File: site/app/controllers/pdf/PDFController.php (hunk 23 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: Removed the double decode

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py (hunk 16 above)
Comment (MasterOdin) [reply migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:40]: Sorry for not making my question fully explicit. Why mode `x` instead of `w` here? Both will create a new file if it does not exist, with `x` having the added thing of throwing an error if the file already exists.

File: site/app/controllers/pdf/PDFController.php (hunk 19 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: Rewritten to remove unneeded if statement

File: site/app/controllers/pdf/PDFController.php (hunk 20 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: deleted

File: site/app/controllers/pdf/PDFController.php (hunk 21 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: replaced with !==

File: site/app/controllers/pdf/PDFController.php (hunk 18 above)
Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: Replaced with FileSystemIterator and removed the if statement

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py (hunk 15 above)
Comment (jchulton) [reply migration/migrator/migrations/course/20200514034200_annotations_file_directory.py]: Rewritten as above

File: site/app/views/AutoGradingView.php (hunk 22 above)
Comment (jchulton) [reply site/app/views/AutoGradingView.php]: Rewritten to be similar to how PDFController manages annotations, removing the unneeded checks above

**Comment by bmcutler** [comment]
@MasterOdin 
Can you do a final review & approve please?

File: site/app/controllers/pdf/PDFController.php [hunk 24]
```diff
@@ -195,28 +195,31 @@ public function showGraderPDFEmbedded(string $gradeable_id) {
...
+        $params = [
+            "gradeable_id" => $gradeable_id,
+            "id" => $id,
+            "file_name" => $filename,
+            "file_path" => $file_path,
+            "annotation_jsons" => $annotation_jsons,
+            "is_student" => false,
+            "page_num" => $page_num
+        ];
+        $this->core->getOutput()->renderOutput(['PDF'], 'showPDFEmbedded', $params);
```
Comment (MasterOdin) [inline site/app/controllers/pdf/PDFController.php:222]: Bad merge. The signature for `showPDFEmbedded` was changed to accept individual parameters, not an amorphous array.

Comment (jchulton) [reply site/app/controllers/pdf/PDFController.php]: Reverted the call to showPDFEmbedded  above to use individual parameters

**Comment by bmcutler** [comment]
@jchulton Did you mean to add the sample course gradeables in this PR?

**Comment by jchulton** [comment]
@bmcutler I did not mean to add sample courses. They have been removed

**Comment by bmcutler** [comment]
@MasterOdin 
Please re-review

File: site/app/templates/autograding/TAResults.twig [hunk 25]
```diff
@@ -82,6 +82,11 @@ $( document ).ready(function() {
                             {% endif %}
                         {% endfor %}
                         {% for file in uploaded_pdfs %}
+                            {% if file.encoded_name in annotated_file_names %}
+                                {% if can_download %}
+                                    <button class = 'btn btn-default key_to_click' onclick='downloadStudentAnnotations("{{ student_pdf_download_url }}?filename={{ file.name }}&path={{ file.path|url_encode }}", "{{file.path|url_encode}}", "annotated_pdfs")' aria-label="Download the file"> Download
+                                        <i class="fas fa-download" title="Download the file"></i></button>
+                                {% endif %}
```
Comment (MasterOdin) [inline site/app/templates/autograding/TAResults.twig:89]:
```suggestion
                                {% endif %}
                            {% endif %}
```

Comment (MasterOdin) [reply site/app/templates/autograding/TAResults.twig:89]: Also, the download button this adds breaks formatting, and it's not clear what each button would do without clicking them and looking at the result.

Screenshot 2020-07-11 16 32 42

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 26]
```diff
@@ -0,0 +1,51 @@
...
+                            json_data['grader_id'] = grader_id[:-5]
+                            json_data['file_name'] = file_name
+                            file_path = Path(annotations_dir, gradeable_level_dir, user_level_dir, version_level_dir)
+                            new_json_file = open(Path(annotation_full_path, md5_file_name.hexdigest() + "_" + grader_id), 'x')
+                            json.dump(json_data, new_json_file)
+                            new_json_file.close()
+                            os.remove(Path(annotation_full_path,name))
+                            os.system("chown -R "+php_user+":"+course_group+ " "+ str(annotation_full_path))
+                            os.system("chmod -R u+rwx "+str(annotation_full_path))
+                            os.system("chmod -R g+rxs "+str(annotation_full_path))
```
Comment (MasterOdin) [inline migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:46]: Why the `s` here?

It looks like files created regularly have a `640` permission set (`rw-r-----`)

File: site/app/templates/autograding/TAResults.twig [hunk 27]
```diff
@@ -82,6 +82,11 @@ $( document ).ready(function() {
...
                             {% if file.name in annotated_file_names %}
```
Comment (MasterOdin) [inline site/app/templates/autograding/TAResults.twig:90]: With the changes, can this if statement ever be entered, or would it only enter the one above?

Comment (jchulton) [reply site/app/templates/autograding/TAResults.twig]: Only the one above. This is why the View Popup button is gone. This has been fixed

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py (hunk 26 above)
Comment (jchulton) [reply migration/migrator/migrations/course/20200514034200_annotations_file_directory.py:46]: You mean x right? Changed to w

File: migration/migrator/migrations/course/20200514034200_annotations_file_directory.py [hunk 28]
```diff
@@ -0,0 +1,51 @@
...
+                            #Hash folder + file_name + grader_id where folder is the directory structure after the version directory
+                            json_data = {};
+                            for submission_root, submission_dirs, submission_files in os.walk(submissions_full_path):
+                                for submission_file in submission_files:
+                                    if(submission_file[:-4] == file_name):
+                                        md5_file_name = hashlib.md5((os.path.abspath(os.path.join(submission_root, submission_file))).encode())
+                            with Path(annotation_full_path, name).open() as initial_file:
+                                json_data['annotations'] = json.dumps(json.load(initial_file))
+                            json_data['grader_id'] = grader_id[:-5]
+                            json_data['file_name'] = file_name
```
[the remark this answers is not in the document]
Comment (jchulton) [reply migration/migrator/migrations/course/20200514034200_annotations_file_directory.py]: Made the above change

File: site/app/templates/autograding/TAResults.twig (hunk 25 above)
Comment (jchulton) [reply site/app/templates/autograding/TAResults.twig]: The above if statement has be rewritten, as described below. This no longer applies

**Comment by bmcutler** [comment]
@jchulton 
Please resolve conflicts

**Comment by jchulton** [comment]
Resolved conflicts

**Comment by bmcutler** [comment]
@jchulton please follow up on MasterOdin's comment above.

**Comment by jchulton** [comment]
Logically, it should be file.encoded_name instead of file.name, like in TAResults.twig. Unforunately I am unable to annotate a pdf as a peer on both this branch and master so I can't actually test much. Still, those errors seem to be the same on this branch and master, and the changes seem fine after a review
