### PR TITLE
[Bugfix:Forum] Validate Forum Thread IDs

### LINKED ISSUE #7955: Discussion Forum -- error in /var/local/submitty/logs/site_errors
This error was found in the site_errors log.
I don't have a report from a user about a problem, so I can't say how exactly it was produced.

-----------------------

00:09:15 05/24/2022 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 188) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: ""

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(794): app\libraries\database\AbstractDatabase->query()
#1 /usr/local/submitty/site/app/views/forum/ForumThreadView.php(713): app\libraries\database\DatabaseQueries->getFirstPostForThread()
#2 /usr/local/submitty/site/app/views/forum/ForumThreadView.php(607): app\views\forum\ForumThreadView->displayThreadList()
#3 unknown file(unknown line): app\views\forum\ForumThreadView->showAlteredDisplayList()
#4 /usr/local/submitty/site/app/libraries/Output.php(228): call_user_func_array()
#5 /usr/local/submitty/site/app/controllers/forum/ForumController.php(927): app\libraries\Output->renderTemplate()
#6 unknown file(unknown line): app\controllers\forum\ForumController->getSingleThread()
#7 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(241): call_user_func_array()
#8 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(219): app\libraries\routers\WebRouter->run()
#9 /usr/local/submitty/site/public/index.php(131): app\libraries\routers\WebRouter::getWebResponse()
Extra Details:
	query: SELECT * FROM posts WHERE parent_id = -1 AND thread_id = ?
	parameters:
		

URL: https://submitty.cs.rpi.edu//courses/u22/csci2600/forum/threads/single

### PR DESCRIPTION
**Pull request by MBon1**
### Please check if the PR fulfills these requirements:

* [X] Tests for the changes have been added/updated (if possible)
* [X] Documentation has been updated/added if relevant

### What is the current behavior?

- Fixes #7955 
  - If a thread is queried in the Discussion Form using an invalid (a null or non-integer value) or non-existent thread id, a server error would be displayed prompting for the page to be refreshed.

### What is the new behavior?
Now, the thread id is checked when a thread is being retrieved to make sure that it and its corresponding thread exists.  If the thread id is invalid or the thread does not exist, a "fail" JSON response case will be rendered that says that the id is not valid.  

### Other information?

I had two pages opened to the discussion forum.  One of these pages had the Inspector Console panel opened and the other with with the Inspector Network panel  opened.  In the Console, the following commands were entered: 
  - Commands that Rendered a "successful" JSON response case
    - window.socketClient.send({type: "new_thread", thread_id: "1"})
    - window.socketClient.send({type: "new_thread", thread_id: 3})
  - Commands that Rendered a "fail" JSON response case
    - window.socketClient.send({type: "new_thread", thread_id: "100"})
    - window.socketClient.send({type: "new_thread", thread_id: ""})
    - window.socketClient.send({type: "new_thread", thread_id: "thread id 1"})

After each command was entered, I checked the page with the Inspector Network panel opened to see if the "Error parsing new post" message was displayed onto the page and the command's corresponding request in the Inspector Network panel.  If a valid thread id was used in the command (the two commands under "Commands that Rendered a 'successful' JSON response case"), I checked if the request's preview had a line saying that the status was "success".  If an invalid or non-existent thread id was used (the commands under "Commands that Rendered a 'fail' JSON response case"), I check to see that the "Error parsing new post" message does not display and a line saying that the status was "fail" in the command's corresponding request's preview.

### CODE REVIEW

File: site/app/controllers/forum/ForumController.php [hunk 1]
```diff
@@ -916,6 +916,18 @@ public function getThreads($page_number = null) {
      * @Route("/courses/{_semester}/{_course}/forum/threads/single", methods={"POST"})
      */
     public function getSingleThread() {
+        // Checks if thread id is null. If so, render "fail" json response case informing that thread id is null.
+        if ($_POST['thread_id'] == null) {
```
Comment (akshatbatra) [inline site/app/controllers/forum/ForumController.php:920]: I've been told that using === is always better.

File: site/app/controllers/forum/ForumController.php [hunk 2]
```diff
@@ -916,6 +916,18 @@ public function getThreads($page_number = null) {
...
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NULL ID)", $_POST['thread_id']);
+        }
+        // Checks if thread id is not an integer value. If so, render "fail" json response case informing that thread id is not an integer value.
+        if (!ctype_digit($_POST['thread_id'])) {
```
Comment (akshatbatra) [inline site/app/controllers/forum/ForumController.php:924]: Should there be !(is_int($_POST['thread_id']) || ctype_digit($_POST['thread_id'])) ?

File: site/app/controllers/forum/ForumController.php [hunk 3]
```diff
@@ -916,6 +916,18 @@ public function getThreads($page_number = null) {
...
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NON-INTEGER ID)", $_POST['thread_id']);
+        }
+        // Checks if thread id does not exist. If so, render "fail" json response case informing that the thread does not exist.
+        if (!$this->core->getQueries()->existsThread($_POST['thread_id'])) {
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NON-EXISTANT ID)", $_POST['thread_id']);
```
Comment (akshatbatra) [inline site/app/controllers/forum/ForumController.php:929]: EXISTENT*

**Review by akshatbatra — CHANGES_REQUESTED** [review]
You may also want to have a look at `showThreads($thread_id = null, $option = 'tree')`, it also isn't handling non-existent thread ids gracefully.

File: site/app/views/forum/ForumThreadView.php [hunk 4]
```diff
@@ -710,6 +710,10 @@ public function displayThreadList($threads, $filtering, &$activeThreadAnnounceme
         $thread_content = [];
 
         foreach ($threads as $thread) {
+            // Checks if thread ID is null. If so, skip this threads.
+            if ($thread["id"] == null) {
```
[the remark this answers is not in the document]
Comment (MBon1) [reply site/app/views/forum/ForumThreadView.php:714]: Changed `==` to `===`.

**Comment by MBon1** [comment]
> Also, do we really need to return $_POST['thread_id'] as error data? I would rather avoid returning a malformed string as it is to the client.

That makes sense.  I guess return $_POST['thread_id'] would be extraneous information for the client.

File: site/app/controllers/forum/ForumController.php (hunk 1 above)
Comment (MBon1) [reply site/app/controllers/forum/ForumController.php:920]: While testing, it looks like if I used `===` instead of `==`, the null value would get caught when when the function checks if the thread id is an integer, so I think it might be better to use `==` in this case.

Comment (MBon1) [reply site/app/controllers/forum/ForumController.php:920]: I also added a check to see if the thread id is unset using `isset`.  Interestingly, `isset` did not catch either of the aforementioned thread ids used when testing for null.

Comment (cjreed121) [reply site/app/controllers/forum/ForumController.php:924]: You could look into using the `empty` function

File: site/app/controllers/forum/ForumController.php [hunk 5]
```diff
@@ -916,6 +916,22 @@ public function getThreads($page_number = null) {
...
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NULL ID)");
+        }
+        // Checks if thread id is not an integer value. If so, render "fail" json response case informing that thread id is not an integer value.
+        if (!(is_int($_POST['thread_id']) || ctype_digit($_POST['thread_id']))) {
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NON-INTEGER)");
+        }
+        // Checks if thread id does not exist. If so, render "fail" json response case informing that the thread does not exist.
+        if (!$this->core->getQueries()->existsThread($_POST['thread_id'])) {
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NON-EXISTENT ID)");
+        }
```
Comment (cjreed121) [inline site/app/controllers/forum/ForumController.php:934]: You could probably just check the result of the below getThread function call rather than doing this.

**Review by cjreed121 — CHANGES_REQUESTED** [review]

File: site/app/controllers/forum/ForumController.php (hunk 1 above)
Comment (MBon1) [reply site/app/controllers/forum/ForumController.php:924]: I looked into `empty`, and it handles of both `$_POST['thread_id']) == null` and  `!isset($_POST['thread_id']))`.  I'll change it to use `empty`.  Thank you.

File: site/app/controllers/forum/ForumController.php [hunk 6]
```diff
@@ -916,6 +916,22 @@ public function getThreads($page_number = null) {
...
+        // Checks if thread id is undefined. If so, render "fail" json response case informing that thread id is not set.
+        if (!isset($_POST['thread_id'])) {
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (UNSET ID)");
+        }
+        // Checks if thread id is null. If so, render "fail" json response case informing that thread id is null.
+        if ($_POST['thread_id'] == null) {
+            return $this->core->getOutput()->renderJsonFail("Invalid thread id (NULL ID)");
+        }
+        // Checks if thread id is not an integer value. If so, render "fail" json response case informing that thread id is not an integer value.
+        if (!(is_int($_POST['thread_id']) || ctype_digit($_POST['thread_id']))) {
```
[the remark this answers is not in the document]
Comment (MBon1) [reply site/app/controllers/forum/ForumController.php:928]: I'm torn with using only `is_int`.  I'm not exactly sure if it can be assume that `$_Post`  should only contain integers since strings composed of only numeric characters can currently be used interchangeably with their corresponding integer equivalent (i.e. using `"1"` vs `1`) when querying for a thread.

File: site/app/controllers/forum/ForumController.php (hunk 5 above)
Comment (MBon1) [reply site/app/controllers/forum/ForumController.php:934]: Okay.  I'll use `!(count($thread) > 1)` instead of `!$this->core->getQueries()->existsThread($thread_id)`.  Thank you.

File: site/app/views/forum/ForumThreadView.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (MBon1) [reply site/app/views/forum/ForumThreadView.php:714]: I decided to use `empty` instead to check if the id is also set.

**Review by cjreed121 — APPROVED** [review]

**Comment by bmcutler** [comment]
@akshatbatra 
Can you re-review and let us know if you approve?  Thanks!

**Review by akshatbatra — APPROVED** [review]

**Comment by akshatbatra** [comment]
Things look good now.
