### PR TITLE
[Bugfix:Calendar] Accessing future gradeables in calendar

### LINKED ISSUE #9711: Show Unreleased Gradeables on Calendar
**What problem are you trying to solve with Submitty**
Gradeables that aren’t visible to students (not released yet) aren’t in Calendar.

**Describe the way you'd like to solve this problem**
Gradeables that aren't released yet should be shown in the calendar, and they should have some indication to show they can't be clicked. (this can be a different shade or different text color).

**Describe any potential alternatives you'd tried to solve the problem**

**Additional context**

### LINKED ISSUE #10234: Instructor user cannot see gradeables that have not been opened to students on the calendar
Bug Report:
If there is a gradeable which has an open date that has not occurred yet (i.e. a future gradeable), then the corresponding due date will not show on the calendar for instructor users.

Expected Behavior:
Ideally, the instructor should still be able to see the due date of an assignment on the calendar view, even if it is not open to students yet.

1. As an instructor user, create a gradeable with an open date that is earlier than the current day.
2. See that it is visible on the calendar under its due date
3. Now edit the gradeable to have an open date that is later than the current day.
4. See that it is missing on calendar

 - OS: Fedora Linux
 - Browser Firefox

Additional context:
This bug is likely connected to Issue #9711 which is where students cannot see future gradeables. It will probably be much harder/bigger change to show it for students if not even instructors can see it.

### PR DESCRIPTION
**Pull request by GO-viper7**
Closes #10234 
Closes #9711 

### Please check if the PR fulfills these requirements:

* [✅] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
An instructor is unable to view+access a future gradeable item in calendar
A student is unable to view a future gradeable item in calendar

A future gradeable item is the one which has `submission_open_date` in the future

### What is the new behavior?
Instructor can open the future gradeable from the calendar whereas student cannot
A tooltip stating : "You can access this gradeable, once the submission opens" is used to notify the students in the calendar

[Instructor-Student-Calendar.webm](https://github.com/Submitty/Submitty/assets/81346327/c49c15e3-ef45-4350-ad8b-0759bf31c28d)

### Date configuration for `leaderboard` gradeable : 
image

### Before -> Calendar view as Instructor : 
image

### After -> Calendar view as Instructor : 
image

### Before -> Calendar view as Student : 
image

### After -> Calendar view as Student : 
image

### Other information?
Please note that, this PR solves both the above mentioned issues.

### CODE REVIEW

File: site/app/models/gradeable/GradeableList.php [hunk 1]
```diff
@@ -312,10 +312,10 @@ public static function getGradeableSection(Core $core, Gradeable $gradeable): in
         ) {
             return self::OPEN;
         }
-        elseif ($core->getUser()->accessGrading() && $gradeable->getTaViewStartDate() <= $now) {
+        elseif ($gradeable->getTaViewStartDate() <= $now) {
             return self::BETA;
         }
-        elseif ($core->getUser()->accessAdmin()) {
+        else {
```
Comment (arougey) [inline site/app/models/gradeable/GradeableList.php:318]: maybe an elseif here is better instead of an else just in case

**Review by arougey — CHANGES_REQUESTED** [review]
Tested it on both future and beta gradeables on both student and instructor profiles with several different test gradeables and couldn't find any errors. Small changes requested

**Review by williamlin6803 — APPROVED** [review]
I tested the above PR and it works as the future gradeable were able to be viewed. The changes to the calendar tooltip enhancements make the information more clear on hover.

File: site/app/models/gradeable/GradeableList.php (hunk 1 above)
Comment (GO-viper7) [reply site/app/models/gradeable/GradeableList.php]: alright, I rewrote that specific elseif and pushed the change
you may review.

File: site/app/models/gradeable/GradeableList.php [hunk 2]
```diff
@@ -312,10 +312,10 @@ public static function getGradeableSection(Core $core, Gradeable $gradeable): in
         ) {
             return self::OPEN;
         }
-        elseif ($core->getUser()->accessGrading() && $gradeable->getTaViewStartDate() <= $now) {
+        elseif ($gradeable->getTaViewStartDate() <= $now) {
             return self::BETA;
         }
-        elseif ($core->getUser()->accessAdmin()) {
+        elseif ($gradeable->getTaViewStartDate() > $now) {
```
Comment (IDzyre) [inline site/app/models/gradeable/GradeableList.php:318]: Would changing these to not include if the user can access them make everyone be able to access them?

Comment (GO-viper7) [reply site/app/models/gradeable/GradeableList.php:318]: So, let me explain this clearly
There are only two instances of GradeableList which are being used : 

1. `Submitty\site\app\controllers\NavigationController.php`, as you can see in the below image
Access is getting checked already for both beta and future gradeables and is getting displayed on gradeables page as per the logged in user level

image


2. `Submitty\site\app\models\CalendarInfo.php`, as you can see in the below image

image

Access check is not necessary for this, because calendar is only used to display future/beta gradeables  for the students but not to access them with the help of below implementation in `calendar.js`
image

Comment (GO-viper7) [reply site/app/models/gradeable/GradeableList.php:318]: Let me know if its not clear @IDzyre

**Review by ArnavPawar — APPROVED** [review]
Code looks good and makes sence. Tested and it works. I remember discussing this issue in class and it does exactly what we talked about.

**Comment by GO-viper7** [comment]
Hey @arougey 
Could you run the tests, just want to make sure there are no static and lint errors
Thanks.

**Review by arougey — APPROVED** [review]
Everything looks good and after testing I can't find any edge cases.

**Comment by williamjallen** [comment]
The video in your PR description appears to be broken.  Can you add some before/after screenshots instead?

**Comment by GO-viper7** [comment]
> The video in your PR description appears to be broken. Can you add some before/after screenshots instead?

Sure
Thanks for pointing it out.
Added before/after screenshots for both instructor view and student's, as I'm trying to close both the issues which are linked above

**Comment by williamjallen** [comment]
@cjreed121 Can you do a security review on this one whenever you get the chance?

**Review by cjreed121 — CHANGES_REQUESTED** [review]

**Comment by cjreed121** [comment]
Security wise this PR is fine

File: site/public/js/calendar.js [hunk 3]
```diff
@@ -168,6 +177,10 @@ function generateCalendarItem(item) {
     if (item['status'] === 'text' || item['status'] === 'ann') {
         element.style.setProperty('background-color', item['color']);
     }
+    // disabling element for student access level if submission is not open
+    if (item['disabled']) {
+        element.style.setProperty('background-color', 'grey');
+    }
```
[the remark this answers is not in the document]
Comment (GO-viper7) [reply site/public/js/calendar.js]: Sure, reverted the color back and changed cursor to default for disabled items

**Review by williamjallen — APPROVED** [review]

**Comment by bmcutler** [comment]
@GO-viper7 

It's not clearly stated in the original issue, but the unreleased gradeables need to be more clearly different.   It appears to me that the only difference is the hover text.  In my opinion this is too subtle and may just be frustrating.  A student looking at a calendar of upcoming gradeables won't have a visual indication when something has changed.  

In this screenshot x is available to submit and y is not yet released.

Screenshot 2024-05-17 at 4 54 16 PM

This is an image taken from the student view.   This doesn't match what is shown in your screenshot -- where the unreleased gradeable is grey(??).  Ideally the unreleased gradeables would still visually indicate which course they were part of.   Maybe solid color (red or purple or etc) for released, and a thick red (or purple or etc) color outline with a grey solid middle color?  Here's a mockup from another student (sadly no PR was submitted):

Screenshot 2024-05-17 at 5 03 24 PM

**Review by bmcutler — CHANGES_REQUESTED** [review]
please see my comment

**Comment by GO-viper7** [comment]
> please see my comment

Hello @bmcutler 
Thanks for the idea of stripes
Added css properties to enable them for disabled items without disturbing theme of existing colors
Here's the student view of calendar :
CalendarTest

you may review

**Comment by bmcutler** [comment]
@GO-viper7 

Thanks!  Looks good when I test it on Chrome & Firefox.  However on Safari it's not rendering for me correctly.
Screenshot 2024-05-20 at 10 44 58 AM
(Maybe @ziesski or @williamjallen or @cjreed121 can confirm or help debug what's wrong with Safari)


Also, can I request another change...  let's always display the unavailable-to-students gradeables with the striped background -- whether student or TA or instructor.  It's important for instructors to be able to visually confirm which gradeables are or are not available to students.  Instructors should be able to click on the striped unreleased gradeable and go to the submission page for testing.

**Comment by GO-viper7** [comment]
> @GO-viper7
> 
> Thanks! Looks good when I test it on Chrome & Firefox. However on Safari it's not rendering for me correctly. Screenshot 2024-05-20 at 10 44 58 AM (Maybe @ziesski or @williamjallen or @cjreed121 can confirm or help debug what's wrong with Safari)
> 
> Also, can I request another change... let's always display the unavailable-to-students gradeables with the striped background -- whether student or TA or instructor. It's important for instructors to be able to visually confirm which gradeables are or are not available to students. Instructors should be able to click on the striped unreleased gradeable and go to the submission page for testing.

Sure, the change is implemented
Instructors can now visually classify the future gradeables and access them for testing
If any other changes, please let me know and debugging in safari is the only thing left to wrap this up.

File: site/public/js/calendar.js [hunk 4]
```diff
@@ -125,28 +125,65 @@ function darken(colorstr) {
     }
 }
 
+/**
+ * This function returns a slightly lighter color than the color variable name passed.
+ *
+ * @param colorstr : string the color to lighten in the form "var(--color-name)"
+ * @returns {string} a hex code for a slightly lighter shade
+ */
+function lighten(colorstr) {
```
Comment (skara9) [inline site/public/js/calendar.js:134]: This function does not always return a valid hex code.
For example, `#1B5E20 => #3D7G42`
So for some course colors, the background color won't display.

File: site/public/js/calendar.js [hunk 5]
```diff
@@ -168,9 +205,16 @@ function generateCalendarItem(item) {
...
+    }
+    if (!item['disabled'] || exists) {
         element.style.setProperty('cursor', 'pointer');
     }
+    else {
+        element.style.setProperty('cursor', 'default');
+    }
     element.title = tooltip;
     if (link !== '') {
         element.href = link;
```
Comment (skara9) [inline site/public/js/calendar.js:220]: These mouse event handlers are breaking the css gradient. Once either one of them is fired, the background property is deleted.

**Review by skara9 — CHANGES_REQUESTED** [review]
I didn't find any differences in behavior across browsers, but this could be what caused the issue in testing.

**Comment by GO-viper7** [comment]
thanks for pointing out the bug @skara9
It was indeed returning the invalid characters
So, I rewrote the function again, which now adjusts brightness of rgb and converts back to hex code
I have tested striped items for all the colors and its working pretty well
You may check it as well

**Review by bmcutler — APPROVED** [review]
