### PR TITLE
[Bugfix:Forum] Fix Firefox thread edit alert

### LINKED ISSUE #11535: error is displayed on firefox when changing thread lock date
**Describe the bug**
When changing the thread lock date on an existing forum thread an error pops up that says "Something went wrong when adding new thread. Please refresh the page.". The page automatically reloads after a few seconds and the update is saved. This error also occurs when editing a thread with a lock date, even if you do not change the lock date or any other fields. This error is likely to do with the websocket reconnect timing on firefox that makes this error appear to the user where it doesn't on Chrome or Edge.

**Expected behavior**
No error should pop-up since the thread is changed appropriately. 

**To Reproduce**
1. Open Submitty on firefox and log in as instructor
2. Edit a thread that has a non-null Lock Thread Date
3. Hit Update Post

**Configuration**
 - OS: Windows
 - Browser: Firefox

**Screenshots**

https://github.com/user-attachments/assets/115b0634-4585-41db-8dad-2eae758cd86b

**Additional context**
This is not connected to setting the Thread Lock Date to null. I tested this on firefox, chrome, and edge. I found the error function in forum.js socketNewOrEditThreadHandler.

### PR DESCRIPTION
**Pull request by Akarshkushwaha**
### Why is this Change Important & Necessary?

Fixes #11535

On Firefox, editing a thread that has a lock date causes a false-positive "Something went wrong when adding new thread. Please refresh the page." alert to appear. The page then reloads anyway and the update saves correctly.

The root cause is a race condition: when the user submits an edit, [modifyOrSplitPost()] calls `window.location.reload()`, while simultaneously the WebSocket server broadcasts an `edit_thread` event triggering [socketNewOrEditThreadHandler()] to fire an AJAX request. Firefox aggressively aborts this background AJAX request during the page unload, setting `jqXHR.status` to `0`. The previous [error] callback had no guard for this case and unconditionally called `window.alert()`, interrupting the reload.

### What is the New Behavior?

- The AJAX error callback in [socketNewOrEditThreadHandler] now silently returns if `textStatus === 'abort'` or `jqXHR.status === 0`, which are signatures of a request cancelled during Firefox navigation.
- Replaced `window.alert()` with the standard Submitty [displayErrorMessage()] for genuine errors, which provides a better user experience.

**Before:**
image

**After:**
image

### What steps should a reviewer take to reproduce or test the bug or new feature?

1. Open Submitty in **Firefox** and log in as an instructor.
2. Navigate to the Discussion Forum and open any thread that has a **Lock Thread Date** set.
3. Click the three dots (**⋮**) on the first post → **Edit**.
4. Click **Update Post** without changing anything.
5. **Before this fix:** A "Something went wrong" alert will appear and pause the reload.
6. **After this fix:** The page reloads cleanly with no alert.

### Automated Testing & Documentation

No automated tests exist for this specific frontend race condition behavior.
This was manually verified on Firefox (v135) on Linux.

No documentation update is required for this bug fix.

### Other information

- Not a breaking change.
- No migrations required.
- No security concerns.

### CODE REVIEW

**Comment by Akarshkushwaha** [comment]
Hi @williamjallen @bmcutler  I've opened PR #12472 to fix this. The root cause is Firefox aggressively aborting WebSocket-triggered AJAX requests during page reloads, which incorrectly fired the error alert. The fix silently ignores those aborted requests. Please take a look when you get a chance!

File: site/public/js/forum.js [hunk 1]
```diff
@@ -480,7 +484,7 @@ function socketAnnounceThreadHandler(thread_id) {
     hr.remove(); // removing this sibling <hr>
     // if there exists other announcements
     if ($('.thread-announcement').length !== 0) {
-    // if thread to announce is already bookmarked
+        // if thread to announce is already bookmarked
```
Comment (JManion32) [inline site/public/js/forum.js]: Revert this

File: site/public/js/forum.js [hunk 2]
```diff
@@ -554,7 +558,7 @@ function socketAnnounceThreadHandler(thread_id) {
     // if user's current thread is the one modified -> update
     // eslint-disable-next-line eqeqeq
     if ($('#current-thread').val() == thread_id) {
-    // if is instructor
+        // if is instructor
```
Comment (JManion32) [inline site/public/js/forum.js]: Revert this

File: site/public/js/forum.js [hunk 3]
```diff
@@ -652,7 +656,7 @@ function socketUnpinThreadHandler(thread_id) {
...
```
Comment (JManion32) [inline site/public/js/forum.js]: Revert this

File: site/public/js/forum.js [hunk 4]
```diff
@@ -2162,7 +2166,7 @@ function loadInlineImages(encoded_data) {
 
     // if they're no images loaded for this well
     if (attachment_well.children().length === 0) {
-    // add image tags
+        // add image tags
```
Comment (JManion32) [inline site/public/js/forum.js]: Revert this

**Comment by Akarshkushwaha** [comment]
@JManion32  Thanks for the review I've reverted the unintended whitespace/indentation changes as requested.

**Review by williamjallen — APPROVED** [review]
Code seems reasonable to me.

**Comment by williamjallen** [comment]
@Akarshkushwaha Please see the failing PR title check.
