### PR TITLE
[BugFix:Submission] Team Edit History

### LINKED ISSUE #5821: team edit history
**Describe the bug**

We store the complete team membership history in this file:
/var/local/submitty/courses/f20/sample/submissions/open_team_homework/00109_whitel/user_assignment_settings.json

 { 
  "team_history": [
        {
            "action": "create",
            "time": "2020-08-14 11:46:42-0400 America/New_York",
            "user": "whitel"
        },
        {
            "action": "send_invitation",
            "time": "2020-08-14 11:46:44-0400 America/New_York",
            "sent_by_user": "whitel",
            "sent_to_user": "student"
        },
        {
            "action": "accept_invitation",
            "time": "2020-08-14 11:48:29-0400 America/New_York",
            "user": "student"
        },
        {
            "action": "admin_add_user",
            "time": "2020-08-14 11:50:17-0400 America/New_York",
            "admin_user": "instructor",
            "added_user": "lockmc"
        },
        {
            "action": "leave",
            "time": "2020-08-14 11:59:33-0400 America/New_York",
            "user": "whitel"
        },
        {
            "action": "send_invitation",
            "time": "2020-08-14 11:59:47-0400 America/New_York",
            "sent_by_user": "student",
            "sent_to_user": "whitel"
        },
        {
            "action": "accept_invitation",
            "time": "2020-08-14 12:00:03-0400 America/New_York",
            "user": "whitel"
        },
        {
            "action": "admin_remove_user",
            "time": "2020-08-14 12:02:20-0400 America/New_York",
            "admin_user": "instructor",
            "removed_user": "student"
        }
    ]
}

Some, but not all, of this information is displayed in the GUI:

after_joe_accepts

Let's update that "edit history" to show *ALL* actions.

Let's also highlight in pink any actions that were performed *AFTER* the team lock date.  If a pending invite was accepted after the lock date, please highlight that.  And any instructor edits after that lock date also.  We don't have to worry about "what if the lock date is changed midway through team making".  Just highlight based on the current setting for team lock date.    Maybe we could add a little icon next to the edit team pencil that indicates that any team edits (e.g., pending invite accepted or instructor edit) were made after the team lock date.

### PR DESCRIPTION
**Pull request by listeph**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #5821 Part 2

The current behavior is that if two different teams invite the same student, then on the student interface, the student sees 2 invite buttons, and can accept 1 and the other will be declined automatically. On the instructor side, it shows that the student has pending membership in 2 different teams, but there is no explicit warning about this for the instructor even though they should only be allowed to join one of them!

### What is the new behavior?
The new behavior is that now for team gradeables, if you click Preview Grading --> Grading Index as an Instructor (which leads you to Grade Details), there is now an indication of students that were invited to multiple teams.

Also I found a bug where on master, accepting a pending invite for a student from the instructor UI doesn't work, so I also fixed that in this PR.

Screen Shot 2020-10-14 at 1 51 46 AM

Screen Shot 2020-10-14 at 1 52 00 AM

Currently the warning message that explains the red highlighting just disappears if the instructor clicks "Add More Users" (easier to implement) but I didn't think this would be a big problem. Let me know what you think!

### CODE REVIEW

File: site/app/libraries/database/DatabaseQueries.php [hunk 1]
```diff
@@ -2762,6 +2762,26 @@ public function getTeamByGradeableAndUser($g_id, $user_id) {
...
     }
 
+    /**
+     * Returns a boolean for whether the given user has multiple pending team invites for the given gradeable
+     *
+     * @param string $user_id
+     * @param string $g_id
+     * @return bool
+     */
+    public function getUserMultipleTeamInvites($g_id, $user_id) {
```
Comment (shailpatels) [inline site/app/libraries/database/DatabaseQueries.php:2772]: lets add php type hints here to improve static analysis 
E.g:
```php
getUserMultipleTeamInvites(string $g_id, string $user_id) : bool { ...
```

File: site/public/js/server.js [hunk 2]
```diff
@@ -754,6 +758,8 @@ function adminTeamForm(new_team, who_id, reg_section, rot_section, user_assignme
     var param = (new_team ? 3 : members.length+2);
     members_div.append('<span style="cursor: pointer;" onclick="addTeamMemberInput(this, '+param+');" aria-label="Add More Users"><i class="fas fa-plus-square"></i> \
         Add More Users</span>');
+    if (exists_multiple_invite_member) members_div.append('<div id="multiple_invites_warning" style="color:red;font-size:small;margin-top:3px;width:75%">\
```
Comment (shailpatels) [inline site/public/js/server.js:761]: Instead of adding this div through javascript let's add this div to the edit team form by default and set its display to none.
Then in this `if` statement you can toggle its visibility if the condition is reached. You can use jquery's `.toggle()` to accomplish this.

Comment (shailpatels) [inline site/public/js/server.js:761]: Use curly braces around javascript statements to improve readability and try to use existing CSS whenever possible, see `.red-message` class in `server.css` to make the warning message more consistent with the rest of Submitty

Comment (shailpatels) [inline site/public/js/server.js:761]: Use dashes instead of underscores for CSS ids and classes.

**Review by shailpatels — CHANGES_REQUESTED** [review]
Works as described and I'm able to see the warning messages on the index page and in the team edit form.

A couple of small code style requested changes.
Also, there is an accessibility issue with the color of the warning messages, the light gray on gray on the index page and the light gray on the disabled textarea on the edit team form should have higher contrast see [here](https://submitty.org/developer/interface_design_style_guide/web_accessibility#all-visual-elements-need-to-adhere-to-a-minimum-contrast-ratio)

Also, keep in mind if you use a custom color for the font it will also need its equivalent CSS for dark mode

File: site/public/js/server.js (hunk 2 above)
Comment (listeph) [reply site/public/js/server.js:761]: Haha, I always forget this, thank you for reminding me again. And thanks for the thorough reviews Shail! :)

Comment (listeph) [reply site/public/js/server.js:761]: I'm adding it to members_div, and that gets emptied at the start of this function (since it is a popup, and that changes each time it's opened again). I tried to make it its own separate div but that also messes things up when "Add More Users" is clicked.

**Comment by listeph** [comment]
> Works as described and I'm able to see the warning messages on the index page and in the team edit form.
> 
> A couple of small code style requested changes.
> Also, there is an accessibility issue with the color of the warning messages, the light gray on gray on the index page and the light gray on the disabled textarea on the edit team form should have higher contrast see [here](https://submitty.org/developer/interface_design_style_guide/web_accessibility#all-visual-elements-need-to-adhere-to-a-minimum-contrast-ratio)
> 
> Also, keep in mind if you use a custom color for the font it will also need its equivalent CSS for dark mode

Thanks Shail! I have changed the foreground color of the texts to be var(--standard-medium-dark-gray) instead of just grey, which is #666666. The background is currently --standard-hover-light-gray, which is #e5e5e5. The contrast ratio is currently 4.55 : 1, which is better than before but not the ideal 7:1. I made all the changes except for the one about adding the div to html instead of javascript -- I replied to that comment separately.

**Review by shailpatels — APPROVED** [review]
Looks good and works as described 
New changes are VPAT compliant.

Note there are some existing errors which are documented under https://github.com/Submitty/Submitty/issues/5957 that need to be fixed later but is lower priority since this is an instructor interface.

**Comment by zhehua-zhang** [comment]
I've reproduced as discribed. (I've reviewed this since I can not find any open PR relate with team assginment, and it help me to  understand some code)
