### PR TITLE
Fixed "who got this mark" queries

### LINKED ISSUE #3150: 'Who got this mark' exception
reported by a full access grader when clicking 'who got this mark'

Failed to get stats for mark: SQLSTATE[42883]: Undefined function: 7 ERROR:  function pg_catalog.substring(integer, unknown) does not exist
LINE 3:              ORDER BY SUBSTRING(sections_rotating_id, '^[^0-...
                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

### PR DESCRIPTION
**Pull request by LeonMontealegre**
Completely didn't work for rotating sections. Not sure how it broke so badly I feel like I was re-writing some things there but it's fixed now.

Fix #3150

### CODE REVIEW

File: site/app/controllers/grading/ElectronicGraderController.php [hunk 1]
```diff
@@ -2238,26 +2238,28 @@ private function getMarkStats(Mark $mark, User $grader) {
...
      */
     private function getStats(Gradeable $gradeable, User $grader, bool $full_stats, &$total_graded, &$total_total) {
         $num_components = $this->core->getQueries()->getTotalComponentCount($gradeable->getId());
         $sections = ($full_stats) ?
                     $this->core->getQueries()->getAllSectionsForGradeable($gradeable) :
-                    $this->core->getQueries()->getSectionsForGradeableAndUser($gradeable, $grader);
-        
+                    ($gradeable->isGradeByRegistration()) ?
+                        $grader->getGradingRegistrationSections() :
+                        $this->core->getQueries()->getRotatingSectionsForGradeableAndUser($gradeable->getId(), $grader->getId());
```
Comment (MasterOdin) [inline site/app/controllers/grading/ElectronicGraderController.php]: Let's not chain together ternary statements. Just use an if/elseif/else.
```
if ($full_stats) {
    $sections = $this->core->getQueries()->getAllSectionsForGradeable($gradeable);
}
elseif ($gradeable->isGradeByRegistration()) {
    $sections = $grader->getGradingRegistrationSections();
}
else {
    $sections = $this->core->getQueries()->getRotatingSectionsForGradeableAndUser($gradeable->getId(), $grader->getId());
}
```

File: site/app/libraries/database/DatabaseQueries.php [hunk 2]
```diff
@@ -1186,12 +1186,15 @@ public function getGradersForRotatingSections($g_id, $sections) {
...
+        if ($user_id !== null) {
             $params[] = $user_id;
-            $query .= " AND user_id=?";
+            $where = " AND g.user_id=?";
         }
-        $this->course_db->query($query, $params);
+        $this->course_db->query("
+            SELECT g.sections_rotating_id
+            FROM grading_rotating AS g
+            WHERE g.g_id=? {$where}", $params);
```
Comment (MasterOdin) [inline site/app/libraries/database/DatabaseQueries.php]: Don't need the alias `g` here, there's only one table being selected from.
