### PR TITLE
[Bugfix:TAGrading] Fix failure to download checkout files

### LINKED ISSUE #3619: download of zip files from checkout browser buggy
**Describe the bug**
If a student has checked in a zip file to their repository, I cannot download that single file from the ta grading panel.

We apparently *still* have lots of places where download of zip file fails, this one is possibly a little different because it is not a zip generated on the fly, but a submitted zip file.  (most submitted zip files are unzipped before they are stored).

### PR DESCRIPTION
**Pull request by zjxiaohan**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
Fixes #3619 . Note that the failure happens not only for zip files, but all other files in the `checkout` directory.

### What is the new behavior?
The files can be downloaded correctly.

### CODE REVIEW

File: site/public/js/ta-grading.js [hunk 1]
```diff
@@ -746,6 +746,9 @@ function downloadFile(html_file, url_file) {
     else if (url_file.includes("results")) {
         directory = "results";
     }
+    else if (url_file.includes("checkout")) {
```
Comment (bmcutler) [inline site/public/js/ta-grading.js]: What is the contents of url_file?  Is it the path to a students file?
If the student names a file in their repository "my_src/my_submissions_results.cpp" for example
will this code break because url_file will be "checkout/my_src/my_submissions_results.cpp"?

Should this be a more specific check so we don't get confused by the file name?

Comment (zjxiaohan) [reply site/public/js/ta-grading.js]: True. This is too crude a way to locate a directory. Will fix it.
