### PR TITLE
Fixed Issues with Image Display for Paragraph Textboxes

### LINKED ISSUE #1260: image file errors on paragraph_textboxes sample autograding config

### PR DESCRIPTION
**Pull request by emaicus**
Closes #1260
Changed the way that paths are built in paragraph textboxes. This fixes an issue which caused errors to be thrown/files not to be displayed if the assignment name had spaces in it.

### CODE REVIEW

File: site/app/views/submission/HomeworkView.php [hunk 1]
```diff
@@ -178,16 +178,15 @@ public function showGradeable($gradeable, $days_late) {
...
+                    $images = $gradeable->getTextboxes()[$i]['images'];
                 }
                 else{
-                    $tester = array();
+                    $images = array();
                 }
 
-                //
-                foreach((array)$tester as $currImage){
+                foreach((array)$images as $currImage){
```
Comment (MasterOdin) [inline site/app/views/submission/HomeworkView.php]: Same comment as I made in #1250, there's no reason to have this cast to `(array)` here.
