### PR TITLE
[Bugfix:TAGrading] Fix Mobile Scrolling on PDF Edit

### LINKED ISSUE #5348: Make sure TA Grading & PDF Annotation interface work on iPad
**What problem are you trying to solve with Submitty**
An instructor/TA should be able to do all of the rubric grading actions from an iPad interface (or other touch or pen based tablet computer).  For example, grading essays that involve annotation PDFs using the touch or pencil interface and select common marks or typing simple custom mark scores per student.

### PR DESCRIPTION
**Pull request by eddiekrystowski**
### What is the current behavior?
Closes #5348
On mobile, if you switch to the pencil tool and then back to the cursor, you will be unable to scroll. This makes your only option of scrolling to use the eraser tool which can be inconvenient.

### What is the new behavior?
* The cursor tool always allows scrolling of the page.
* Black is selected as the pen color in the toolbar the first time you go on the page (as opposed to a transparent box if ```localStorage.main_color``` is empty)

### Other information?
I believe this closes #5348 since the rest of the interface seems to work well on mobile.
Tested on iPad Pro with Apple Pencil

### CODE REVIEW

**Review by cjreed121 — APPROVED** [review]
Works as expected. Tested on iPad Pro.

File: site/public/js/pdf/PDFInitToolbar.js [hunk 1]
```diff
@@ -57,8 +57,10 @@ function renderPDFToolbar() {
                 case 'eraser':
                     currentTool = 'eraser';
                     PDFAnnotate.UI.enableEraser();
+                    PDFAnnotate.UI.disableEdit();
```
Comment (MasterOdin) [inline site/public/js/pdf/PDFInitToolbar.js:60]: I'm still not clear on how we would hit an instance where on hitting `eraser`, `disableEdit` would not have already been called above?

File: site/public/js/pdf/PDFInitToolbar.js [hunk 2]
```diff
@@ -187,7 +189,7 @@ function renderPDFToolbar() {
         document.getElementById("size_selector").addEventListener('click', sizeMenuToggle);
         document.addEventListener('colorchange', changeColor);
         let init_color = localStorage.getItem('main_color');
-        setColor(init_color);
+        setColor(init_color ? init_color : '#000000');
```
Comment (MasterOdin) [inline site/public/js/pdf/PDFInitToolbar.js:192]: if `init_color` is either a string or undefined, can do the following shorthand in JS:
```suggestion
        setColor(init_color || '#000000');
```

File: site/public/js/pdf/PDFInitToolbar.js (hunk 1 above)
Comment (eddiekrystowski) [reply site/public/js/pdf/PDFInitToolbar.js:60]: I suppose you're right, I just added that line since I somehow managed to get to a state where scrolling with the eraser was leaving tiny marks where I first initiated the scroll. I haven't been able to reproduce it with/without that line so I can remove that line if you want.

Comment (MasterOdin) [reply site/public/js/pdf/PDFInitToolbar.js:60]: Please do.
