### PR TITLE
[UI/UX:InstructorUI] Manage Student lateday column

### LINKED ISSUE #8518: Improve clarity of late days & expceptions on TA Grading student information panel
**What problem are you trying to solve with Submitty**

The "My late days & Exceptions" page is formatted with rows alternating white & grey:
(this shows MY data)

Screen Shot 2022-10-17 at 7 44 02 PM

The same data for a student can be view in TA grading for any TA graded upload gradeable on the "Student Information" panel.   But that information is harder to read because the rows are all the same background color with no separators:

Screen Shot 2022-10-17 at 7 43 10 PM

**Describe the way you'd like to solve this problem**

Two Requests:

* add alternating row background color to the version on the TA grading page.  And any other minor formatting improvements make sense.

* add link from the manage students page to a specific students my late days/exceptions page.  put it next to the 'View Grades" column.  (View grades opens up the "My Rainbow Grades" information for a specific student.

Screen Shot 2022-10-17 at 7 54 41 PM

### PR DESCRIPTION
**Pull request by ziesski**
### Please check if the PR fulfills these requirements:

* [X] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Currently there is no column to access student's late day info directly from Manage Student page.
closes #8518

### What is the new behavior?

Added column to access each individual student's late day info directly from Manage Student page. 
Screen Shot 2023-04-05 at 11 39 10

Screen Shot 2023-04-05 at 14 27 26

### CODE REVIEW

**Review by hansongu123 — COMMENTED** [review]
~~This PR seems to be still a work in progress, so I'm going to convert it to draft for now.~~

The new column and the icon for students' late days seem to be looking pretty good to me, but clicking on a linked icon currently would result in a PHP page error meaning the link is not set up correctly.
 
I know this is likely the proposal in the original issue, but to me design-wise, adding another column in the manage student section seems to be a little excessive considering we're now at the maximum width for the entire form (there are already a lot of columns/information) and there could potentially be more functional columns added to it in the future. We could consider embedding the link to late days to the student's view grade page using the same method.

**Comment by ziesski** [comment]
Thanks for pointing out my mistake, I did make adequate changes. 

Design-wise, yes it is indeed the original request from Barb. In fact, we did discuss about potential cluster of info may harm the clarity of table, and eventually switch to scroll. (which would be a new PR). I think adding late day table under rainbow grade could be a valid option. I will further discuss with Barb and make a new PR about it.

**Review by hansongu123 — COMMENTED** [review]
The functionality is looking good now. I just have some small suggestions/questions.

Is it necessary to add a new twig file to display the late days table for an instructor? I can see the only difference between it and `LateDaysTable.twig` is just the first word in the headings. We generally want to avoid creating new files as much as possible for the ease of future development. 

Would you also fix the linting on the new functions you added in the PHP files, so the site tests can run. Thanks.

**Review by hansongu123 — APPROVED** [review]
I've reviewed the functionality and it is now passing all the site tests, so I'll approve this.

Great job on the PR!

**Comment by hansongu123** [comment]
Another suggestion is to remove the late days column for the graders and instructors, but this should work if the page exists for them.

**Comment by ziesski** [comment]
I think new twig is necessary for few reasons, without it, the current way the  aside column is designed will block the content of table. 
Moreover, your suggestion of "remove the late days column for graders and instructors" do you mean the aside class (column on the left of submitty, containing Gradeable, Notifications etc)? - if so, I also think  "My Late Days/Extensions" element is useless. I doubt any instructor or grader will ever use it. I will see what I can do Thanks👍

**Comment by hansongu123** [comment]
> Moreover, your suggestion of "remove the late days column for graders and instructors" do you mean the aside class (column on the left of submitty, containing Gradeable, Notifications etc)? - if so, I also think "My Late Days/Extensions" element is useless. I doubt any instructor or grader will ever use it. I will see what I can do Thanks👍

Those tabs usually wouldn't show for the instructors or graders on the left side menu. I meant the columns inside of the "manage students" table, I doubt that the "view grade" and "late days" columns would have any use for them. But it's alright unless those links for them start to break in the future.

File: site/app/views/admin/UsersView.php [hunk 1]
```diff
@@ -34,6 +35,7 @@ public function listStudents($sorted_students, $reg_sections, $rot_sections, $do
             "delete_user_url" => $this->core->buildCourseUrl(['delete_user']),
             "return_url_upload_class_list" => $this->core->buildCourseUrl(['users', 'upload']) . '?' . http_build_query(['list_type' => 'classlist']),
             'view_grades_url' => $this->core->buildCourseUrl() . '/users/view_grades',
+            'view_latedays_url' => $this->core->buildCourseUrl() . '/users/view_latedays',
```
Comment (cjreed121) [inline site/app/views/admin/UsersView.php:38]: It's usually preferred to do `$this->core->buildCourseUrl(['users', 'view_latedays'])` instead

**Review by ziesski — COMMENTED** [review]
Made appropriate changes

**Review by hansongu123 — APPROVED** [review]
LGTM. Functionality after changes should be the same as what we found in our last meeting. 

Chris may have some more comments about coding style, but other wise it is good to be merged.

File: site/app/controllers/admin/LateController.php [hunk 2]
```diff
@@ -280,6 +281,27 @@ public function updateExtension() {
...
+            return JsonResponse::getFailResponse($error);
+        }
+        $student_id = $_POST["student_id"];
+        $user = $this->core->getQueries()->getUserById($student_id);
+        if ($user === null) {
+            $error = "Invalid Student ID";
+            $this->core->addErrorMessage($error);
+            return JsonResponse::getFailResponse($error);
+        }
+          return $this->core->getOutput()->renderOutput(['LateDaysTable'], 'showLateTabletoInstructor', LateDays::fromUser($this->core, $this->core->getQueries()->getUserById($student_id)));
```
[the remark this answers is not in the document]
Comment (ziesski) [reply site/app/controllers/admin/LateController.php]: ddid change to webResponse

File: site/app/controllers/admin/LateController.php [hunk 3]
```diff
@@ -280,6 +281,29 @@ public function updateExtension() {
...
+            return new RedirectResponse($this->core->buildCourseUrl(['users']));
+        }
+        $student_id = $_GET["student_id"];
+        $user = $this->core->getQueries()->getUserById($student_id);
+        if ($user === null) {
+            $this->core->addErrorMessage("Invalid Student ID \"" . $_POST["student_id"] . "\"");
+            return new RedirectResponse($this->core->buildCourseUrl(['users']));
+        }
+        return new WebResponse(
+            ['LateDaysTable'],
```
Comment (williamjallen) [inline site/app/controllers/admin/LateController.php:301]: You don't need the square brackets here

File: site/app/views/LateDaysTableView.php [hunk 4]
```diff
@@ -27,4 +27,18 @@ public function showLateTablePage(LateDays $late_days) {
             'grade_inquiry_enabled' => $this->core->getConfig()->isRegradeEnabled()
         ]);
     }
+
+    public function showLateTabletoInstructor(LateDays $late_days) {
```
Comment (williamjallen) [inline site/app/views/LateDaysTableView.php:31]: A PHP type declaration for the return type should be added here

File: site/app/controllers/admin/LateController.php [hunk 5]
```diff
@@ -280,6 +281,29 @@ public function updateExtension() {
...
+     **/
+    public function viewStudentLatedays() {
+        if (!isset($_GET["student_id"])) {
+            $this->core->addErrorMessage("No student ID provided");
+            return new RedirectResponse($this->core->buildCourseUrl(['users']));
+        }
+        $student_id = $_GET["student_id"];
+        $user = $this->core->getQueries()->getUserById($student_id);
+        if ($user === null) {
+            $this->core->addErrorMessage("Invalid Student ID \"" . $_POST["student_id"] . "\"");
```
Comment (williamjallen) [inline site/app/controllers/admin/LateController.php:297]: Why not use single quotes here?  I think you also forgot to switch `$_POST` to `$_GET` here.

File: site/app/controllers/admin/LateController.php [hunk 6]
```diff
@@ -280,6 +281,29 @@ public function updateExtension() {
...
+            return new RedirectResponse($this->core->buildCourseUrl(['users']));
+        }
+        return new WebResponse(
+            ['LateDaysTable'],
+            'showLateTabletoInstructor',
+            LateDays::fromUser($this->core, $this->core->getQueries()->getUserById($student_id))
```
Comment (williamjallen) [inline site/app/controllers/admin/LateController.php:303]: You already have a variable `$user` defined.  Use that instead of calling `$this->core->getQueries()->getUserById()` again.

File: site/app/views/LateDaysTableView.php [hunk 7]
```diff
@@ -27,4 +27,18 @@ public function showLateTablePage(LateDays $late_days) {
...
+        $manage_url = $this->core->buildCourseUrl(['users']);
+        $this->core->getOutput()->addBreadcrumb('Manage Students', $manage_url);
+        $this->core->getOutput()->addBreadcrumb($late_days->getUser()->getDisplayFullName());
+        $this->core->getOutput()->addInternalCss('table.css');
+        $this->core->getOutput()->addInternalCss('latedaystableplugin.css');
+        $this->core->getOutput()->enableMobileViewport();
+        $preferred_name = $late_days->getUser()->getDisplayFullName();
```
Comment (williamjallen) [inline site/app/views/LateDaysTableView.php:38]: Is this used anywhere?

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/views/LateDaysTableView.php (hunk 7 above)
Comment (ziesski) [reply site/app/views/LateDaysTableView.php]: Thanks for pointing out. Removed -> 2 less queries.

File: site/app/controllers/admin/LateController.php (hunk 6 above)
Comment (ziesski) [reply site/app/controllers/admin/LateController.php]: Made adequate changes.

File: site/app/controllers/admin/LateController.php (hunk 5 above)
Comment (ziesski) [reply site/app/controllers/admin/LateController.php]: Changed to single quote with strings inside of [] - Coherent with rest of the code

File: site/app/views/LateDaysTableView.php (hunk 4 above)
Comment (ziesski) [reply site/app/views/LateDaysTableView.php:35]: Return type and parameter added

File: site/app/controllers/admin/LateController.php (hunk 3 above)
Comment (ziesski) [reply site/app/controllers/admin/LateController.php]: box brackets removed

File: site/app/views/LateDaysTableView.php [hunk 8]
```diff
@@ -27,4 +27,21 @@ public function showLateTablePage(LateDays $late_days) {
             'grade_inquiry_enabled' => $this->core->getConfig()->isRegradeEnabled()
         ]);
     }
+
+    /**
+     * @param LateDays $late_days
+     * @return string
```
Comment (williamjallen) [inline site/app/views/LateDaysTableView.php:33]: Since there's just one type here, it would be change this to a native PHP type declaration.

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/app/controllers/admin/LateController.php [hunk 9]
```diff
@@ -280,6 +281,29 @@ public function updateExtension() {
         }
     }
 
+    /**
+     * @AccessControl(role="INSTRUCTOR")
+     * @Route("/courses/{_semester}/{_course}/users/view_latedays", methods={"GET"})
+     * @return RedirectResponse|WebResponse
+     **/
+    public function viewStudentLatedays() {
```
Comment (ziesski) [inline site/app/controllers/admin/LateController.php:289]: I wonder if you @williamjallen  would like viewStudentLatedays function to have native PHP type declaration too.

**Review by mahi-pas — APPROVED** [review]
Looks good to me

File: site/app/controllers/admin/LateController.php (hunk 9 above)
Comment (williamjallen) [reply site/app/controllers/admin/LateController.php:289]: certainly!

Comment (ziesski) [reply site/app/controllers/admin/LateController.php]: Did make change

**Comment by bmcutler** [comment]
@williamjallen 
please re-review
