### PR TITLE
[Bugfix:TAGrading] save components before redirecting to main grading page

### LINKED ISSUE #5190: Failure to save marks in open component when we jump back to index page
**Describe the bug**
When we are TA grading with a complex gradeable.
We have a specific component open for a specific student,
We select a couple marks for that component, but don't press "save"...
Then we press the house icon button to jump to the index of all students.
It does not save the marks for that last open, unsaved component.

**Expected behavior**
In other cases, the components for the open component ARE saved.
E.g., If we press the left or right arrows to go to the next or prev student.

### PR DESCRIPTION
**Pull request by jportorreal00**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Fixes #5190- If a TA is grading a component and clicks on the home button to go to the main page, none of the changes are fixed, unlike the next and previous buttons.

### What is the new behavior?
The home page button now behaves like the next and previous buttons and saves the components before redirecting

### Other information?
 
 
Create complex gradable components and make sure they save
Used windows with chrome and firefox

### CODE REVIEW

File: site/public/js/ta-grading-v2.js [hunk 1]
```diff
@@ -330,6 +330,29 @@ function updateCookies(){
...
 // Student navigation
+function gotoMainPage() {
+
+  let selector;
+  let window_location;
+
+  selector = "#main-page";
+  window_location = $(selector)[0].dataset.href
+
+  console.log(window_location);
```
Comment (mukul-kmr-jha) [inline site/public/js/ta-grading-v2.js:341]: I think you can make this a little compact by removing the `selector` variable (not used anywhere other $(selector)[0].dataset.href), then declaring the `window_location` at the same line and removing the console line (used for testing). Thanks :)
