### PR TITLE
[Bugfix:TAGrading] peer grading statistics

### LINKED ISSUE #5372: Statistics for progress/completion of peer grading
Currently we only have data on the percentage of instructor/TA grading that is complete (and this might actually be buggy for gradeables with peer grading... )

1. We would like to know the percentage of peer grading that is complete...  if you have 100 students, and each was supposed to grading 3 other students for 2 components, there are 600 units of peer grading to be completed.  It would be nice to have information on the fraction of the grading that is complete.  Note:  Unlike TA grading, it is probably unrealistic to expect that peer grading will get to 100% in large courses!

2. Statistics for the peer graded components -- just like the ta/instructor manual graded components.  Would also be neat to have them in the charts too!

### LINKED ISSUE #5506: Peer "Current percentage of grading done" incorrect on status page
Possibly related to #5505

At present, the `Current percentage of student grading done` on the status page is incorrect for peer graders. 

To reproduce: 
1. Create a peer gradeable with one peer component and one TA component
2. Assign peer `A` to assign peers `B` and `C`. 
3. Make a submission for peer `B`
4. As peer `A`, grade peer `B`.
5. Navigate to the status page to see that it says grading is `1/4` complete.

bugged_peer_points

percentage

### PR DESCRIPTION
**Pull request by josharsh**
closes #5506
closes #5372 

### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
* At present, the Current percentage of student grading done on the status page is incorrect for peer graders.
* The grading percentage data on TA/instructor view is incorrect for a gradeable with peer component(s).
* Manual Grading stats are not displayed when peer components are involved.
### What is the new behavior?
* Current percentage of student grading done on the status page is correct for peer graders.
* The grading percentage data on TA/instructor view is correct for a gradeable with peer component(s).
* Manual Grading stats are displayed with correct data when peer components are involved.

### CODE REVIEW

**Comment by jchulton** [comment]
The Current Percentage of TA grading done and Peer Percentage of Grading done are miscalculated. In both examples, the Current percentage done is double what is should be. Note that the TA Grading By sections is caulcated corretly.

image

image

**Comment by jchulton** [comment]
It should be noted that many of the team stats are still broken: 

image

Teams who have submitted is a decimal, Number of teams where at least one member viewed is 1 / 0.5, number of students who have viewed is 1 / 0. However, these are broken on master and should be tackled in a future PR in my opinion

**Comment by jchulton** [comment]
Stats are inconsistent for full access graders: stats on the left are an instructor (correct), on the right are a full access grader for the same gradeable. 

image

File: site/app/views/grading/ElectronicGraderView.php [hunk 1]
```diff
@@ -66,6 +66,12 @@ public function statusPage(
         $peer_total = 0;
         $peer_graded = 0;
         $peer_percentage = 0;
+        $entire_peer_graded = 0;
+        $entire_peer_total = 0;
+        $total_students_submitted = 0;
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:71]: total_students_submitted is an input for the statusPage method. I don't think it should be immediately overrided with 0?

File: site/app/views/grading/ElectronicGraderView.php [hunk 2]
```diff
@@ -105,13 +111,19 @@ public function statusPage(
             else {
                 $total_students = $total_submissions;
             }
-            $num_components = count($gradeable->getNonPeerComponents());
+            $num_peer_components = 0;
+            $ta_graded_percentage = 0;
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:115]: This isn't needed, you set $ta_graded_percentage to 0 on line 74 and it hasn't been modified between then and here

File: site/app/views/grading/ElectronicGraderView.php [hunk 3]
```diff
@@ -135,32 +147,57 @@ public function statusPage(
...
+                $entire_peer_graded = 0;
+                $entire_peer_percentage = 0;
+                if ($peer_count > 0 && array_key_exists("peer_stu_grad", $sections)) {
+                    if ($num_peer_components > 0) {
+                        $total_students_submitted =  floor(($sections['peer_stu_grad']['total_who_submitted']));
+                        $total_grading_percentage =  number_format(($graded_total / $total_students_submitted ) * 100, 1);
+                        $entire_peer_total =  floor(($sections['peer_stu_grad']['total_who_submitted']));
+                        $entire_peer_graded =  $sections['peer_stu_grad']['view_peer_graded_components'] / $num_peer_components;
+                    }
+                    else {
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:162]: This else statement is not needed, just leave the varaibles defined above at 0

File: site/app/views/grading/ElectronicGraderView.php [hunk 4]
```diff
@@ -135,32 +147,57 @@ public function statusPage(
...
+                        $entire_peer_total = 0;
+                        $entire_peer_graded = 0;
+                    }
 
-                if ($peer_count > 0 && array_key_exists("stu_grad", $sections)) {
-                    $peer_percentage = number_format(($sections['stu_grad']['graded_components'] / ($sections['stu_grad']['total_components'] * $sections['stu_grad']['num_gradeables'])) * 100, 1);
-                    $peer_total =  floor(($sections['stu_grad']['total_components'] * $sections['stu_grad']['num_gradeables']) / $peer_count);
-                    $peer_graded =  floor($sections['stu_grad']['graded_components'] / $peer_count);
+                    $entire_peer_percentage = number_format(($entire_peer_graded / ($entire_peer_total) ) * 100, 1);
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:167]: Is it possible for this to be a divide by 0 (if entire_peer_total is 0)?

File: site/app/views/grading/ElectronicGraderView.php [hunk 5]
```diff
@@ -135,32 +147,57 @@ public function statusPage(
                 $peer_percentage = 0;
                 $peer_total = 0;
                 $peer_graded = 0;
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:149]: these peer variables were defined above, extraneous

File: site/app/views/grading/ElectronicGraderView.php [hunk 6]
```diff
@@ -135,32 +147,57 @@ public function statusPage(
...
-                        $section['percentage'] = 0;
+                if ($peer_count > 0 && array_key_exists("stu_grad", $sections)) {
+                    if ($num_components > 0) {
+                        $peer_total =  floor(($sections['stu_grad']['total_components']) / $num_peer_components);
+                        $peer_graded =  $sections['stu_grad']['graded_components'] / $num_peer_components;
+                        $peer_percentage = number_format(($sections['stu_grad']['graded_components'] / ($sections['stu_grad']['total_components'] * $sections['stu_grad']['num_gradeables'])) * 100, 1);
                     }
                     else {
-                        $section['percentage'] = number_format(($section['graded_components'] / $section['total_components']) * 100, 1);
+                        $peer_total = 0;
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:176]: Uneeded else statement, these will stay at 0 if the if statement isn't executed

File: site/app/views/grading/ElectronicGraderView.php [hunk 7]
```diff
@@ -135,32 +147,57 @@ public function statusPage(
...
+                        $peer_graded = 0;
                     }
-                    $section['graded'] = round($section['graded_components'] / $num_components, 1);
-                    $section['total'] = $section['total_components'] / $num_components;
+                    $peer_percentage = number_format(($peer_graded / ($peer_total) ) * 100, 1);
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:179]: Possible divide by 0 if peer_total = 0?

File: site/app/views/grading/ElectronicGraderView.php [hunk 8]
```diff
@@ -135,32 +147,57 @@ public function statusPage(
...
                 }
+            }
+            {
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:182]: Extraneous {

File: site/app/views/grading/ElectronicGraderView.php [hunk 9]
```diff
@@ -227,9 +264,14 @@ public function statusPage(
             "submitted_percentage" => $submitted_percentage,
             "graded_total" => $graded_total,
             "graded_percentage" => $graded_percentage,
+            "ta_graded_percentage" => $ta_graded_percentage,
```
Comment (jchulton) [inline site/app/views/grading/ElectronicGraderView.php:267]: ta_graded_percentage isn't used

File: site/app/views/grading/ElectronicGraderView.php (hunk 1 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:71]: Yes, I thought it was anyway to be set when $peer and $peerGradeable were both set (Non Peer View for Peer Gradeable), but it is extraneous here, Removed it.

File: site/app/views/grading/ElectronicGraderView.php (hunk 2 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:115]: Updated percentage calculation in recent commits and removed using $ta_graded_percentage at all.

File: site/app/views/grading/ElectronicGraderView.php (hunk 3 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:162]: Recent commits update this,

File: site/app/views/grading/ElectronicGraderView.php (hunk 4 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:167]: Yes, Noted!

File: site/app/views/grading/ElectronicGraderView.php (hunk 6 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:176]: Corrected!

File: site/app/views/grading/ElectronicGraderView.php (hunk 8 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:182]: Corrected

File: site/app/views/grading/ElectronicGraderView.php (hunk 7 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:179]: Noted

File: site/app/views/grading/ElectronicGraderView.php (hunk 9 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:267]: Removed

File: site/app/views/grading/ElectronicGraderView.php (hunk 5 above)
Comment (josharsh) [reply site/app/views/grading/ElectronicGraderView.php:149]: Removed

File: site/app/controllers/grading/ElectronicGraderController.php [hunk 10]
```diff
@@ -311,7 +311,7 @@ public function showStatus($gradeable_id) {
         $this->core->getOutput()->addBreadcrumb("{$gradeable->getTitle()} Grading", $gradeableUrl);
 
         $isPeerGradeable = false;
-        if ($gradeable->isPeerGrading() && ($this->core->getUser()->getGroup() == User::GROUP_INSTRUCTOR)) {
+        if ($gradeable->isPeerGrading() && ($this->core->getUser()->getGroup() == User::GROUP_INSTRUCTOR || $this->core->getUser()->getGroup() == User::GROUP_FULL_ACCESS_GRADER || $this->core->getUser()->getGroup() == User::GROUP_LIMITED_ACCESS_GRADER)) {
```
Comment (jchulton) [inline site/app/controllers/grading/ElectronicGraderController.php:314]: You can just say $this->core->getUser()->getGroup() < User:GROUP_STUDENT

File: site/app/controllers/grading/ElectronicGraderController.php [hunk 11]
```diff
@@ -468,27 +468,58 @@ public function showStatus($gradeable_id) {
...
-                $sections['all'] = [
-                    'total_components' => 0,
-                    'graded_components' => 0,
-                    'graders' => []
-                ];
-                foreach ($total_users as $key => $value) {
-                    if ($key == 'NULL') {
-                        continue;
+                 // If not a team assignment => Team Peer Grading Stats Should be Visible
+                if ($gradeable->isTeamAssignment()) {
```
Comment (jchulton) [inline site/app/controllers/grading/ElectronicGraderController.php:474]: This if statement is odd to me. A lot of code is repeated in both clauses (the foreach loop for example). I also don't understand why the total_components is just getPeerComponents for a team assignment: shouldn't it still be # of components times # of teams to grade?

File: site/app/controllers/grading/ElectronicGraderController.php (hunk 10 above)
Comment (josharsh) [reply site/app/controllers/grading/ElectronicGraderController.php:314]: done!

File: site/app/controllers/grading/ElectronicGraderController.php (hunk 11 above)
Comment (josharsh) [reply site/app/controllers/grading/ElectronicGraderController.php:474]: Yes, I tried fixing Peer stats when Teams are used but I found teams still needs to have a better way around peer assignments. [I think there we might need additional columns in some of the relations ( so that we can use joins aptly)]
It looked out of scope of this PR (and this already looks complex) so I have disabled peer view team gradeable stats while non peer view team gradeable stats are working fine. 

[Maybe we should talk more about it during meeting] 
Apart from this, I have worked on the fixes you suggested.

**Comment by jchulton** [comment]
Getting 1 / 0 on the instructor stats page for Current percetage of TA grading done for a freshly made Non Peer Non Team gradeable:
image

**Comment by josharsh** [comment]
@jchulton noted, it was due to same variable being used for peer and non peer gradeable ("submitted_total" for both instead of "total_students_submitted" for peer and "Submitted_total" for non peer". Fixed by  commit f56a7a4
P.S: However when this and Totals and Subtotals is merged I will try to refactor for clean code.

**Comment by josharsh** [comment]
For a Non Peer Non Team Gradeable with 2 Components (Out of which One is graded)
image

**Comment by josharsh** [comment]
For a Peer Gradeable with 4 components (2 peer, 2 non peer), one submission and 1 peer component graded, 1 non peer component graded. 
image

**Comment by josharsh** [comment]
@jchulton I am not able to reproduce this using Peer Marks, 
Can you please let me know what I am missing.
Here are the screenshots when I try to add marks, stats seem to work fine. 
image

Grading Stats Page:
image

It looks correct. Am I misinterpreting something?

**Comment by jchulton** [comment]
Yes that is correct, and I can't reproduce after merging with master...
One odd thing is that for an instructor stats for a peer gradeable, the number of students who have viewed their grade stat is missing:
image

Also, for a non-peer non-team gradeable, the demoninator is half of what it should be (should be 3, not 1.5): 
image

**Comment by jchulton** [comment]
It seems that, for peer gradeables, the #of students who have viewed their grade is based of the number of components still 
image

**Comment by jchulton** [comment]
Getting this on stats page for a team gradeable 
image

**Comment by josharsh** [comment]
@jchulton I am not able to reproduce this for peer gradeable
I tried this with a peer gradeable with 2 peer and single non peer component. It shows correct stats.
image

**Comment by jchulton** [comment]
You can still get the Division by 0 error if you create a team gradeable and preview grading before a submission.
image

Also, if you grade peer components as an instructor, that peer grading is not reflected as complete by the Current percentage of Peer grading done. Not sure if this is correct behavior or not @bmcutler?

**Comment by josharsh** [comment]
image
Doesn't break for teams without submissions for both peer and non peer gradeables now!

**Comment by josharsh** [comment]
@jchulton Tested it all over again, please tell if I missed any case:
1 - For Peer Gradeables:
     1.1 - Stats when there is no submission - CORRECT
     1.2 - Stats after few submissions have been made - CORRECT
     1.3 - Stats after submissions are closed - CORRECT
     1.4 - Stats when grading is in progress - CORRECT
     1.5 - Stats when grades are released - CORRECT

1 - For Non -Peer Gradeables:
     1.1 - Stats when there is no submission - CORRECT
     1.2 - Stats after few submissions have been made - CORRECT
     1.3 - Stats after submissions are closed - CORRECT
     1.4 - Stats when grading is in progress - CORRECT
     1.5 - Stats when grades are released - CORRECT

Team Stats are not complete (as we discussed earlier) for both peer/non peer, same as master but team gradeables are not breaking anymore. 
As far as "if you grade peer components as an instructor, that peer grading is not reflected as complete by the Current percentage of Peer grading done" is concerned, there are some issues which restrict this in this PR (hopefully PR on subtotals shall cover). We can discuss this restriction in meeting if I am missing something.

**Comment by jchulton** [comment]
Agreed with Evan. Tested and working.
