### PR TITLE
[Bugfix:Notifications] Grade Inquiry Draft After Submission

### LINKED ISSUE #10247: Submitting grade inquiry clears other grade inquiries that haven't been submitted
**Describe the bug**

When submitting grade inquiries for multiple questions on the same assignment, if you work on more than one before submitting, the rest of them get cleared after you submit one.

**Expected behavior**

The text in the other grade inquiry boxes should not get cleared when submitting a grade inquiry for a different question.

**To Reproduce**
1. Type text in one grade inquiry box.
2. Type text in another grade inquiry box.
3. Submit the first grade inquiry.

**Configuration**
 - OS: Windows
 - Browser: Chrome

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by hanyunguo**
### Please check if the PR fulfills these requirements:

* [X] Test that for sample- rainbow grades can be configured automatically.
* [X] Test that for sample- rainbow grades can generate grade summaries and customize what to show.
* [X] Check if the results/grades are some for both the instructor and student UI

### What is the current behavior?

Fixes #10247. Currently, when student submit grade inquiries for multiple questions on the same assignment. The text entered in other grade inquiry boxes gets cleared after submitting an inquiry for one question.

### What is the new behavior?

The new behavior introduced by this pull request ensures that the text in the other grade inquiry boxes is not cleared when submitting a grade inquiry for a different question on the same assignment. Users can now submit multiple grade inquiries without losing the entered text, improving the overall user experience and preventing data loss.

### Other information?

The video below demonstrates how to reproduce the issue

https://github.com/Submitty/Submitty/assets/77653905/e53cf416-8dd9-44a5-9f50-450224841c91

and below is new behavior (with saved unsubmitted grade inquiry feature)

https://github.com/Submitty/Submitty/assets/77653905/cc60439d-4734-4b15-896f-cb4c1fb19347

### CODE REVIEW

**Review by thegame615 — COMMENTED** [review]
Hello,

I was not able to reproduce the issue that this PR is fixing. The issue is that the text disappears when you switch between grade inquiry tabs, correct? I tested it on the most recent main branch and it seems that the text does not get deleted when switched between tabs.  Also, I do not understand your changes to the README.

**Comment by hanyunguo** [comment]
> Hello,
> 
> I was not able to reproduce the issue that this PR is fixing. The issue is that the text disappears when you switch between grade inquiry tabs, correct? I tested it on the most recent main branch and it seems that the text does not get deleted when switched between tabs. Also, I do not understand your changes to the README.
Hello, the in main branch does not cause text disappear, it happens when trying to click "Submit Grade Inquiry". For instance, if you have two questions, and you firstly type in both question 1 and question 2. Then, submit only question 1 grade inquiry. The text in question 2 grade inquiry will disappear. Hope it helps. If you still unsure about this issue, I can record a video about this current bug. For the README. changes, I accidentally commit it, I will revert all these changes as soon as possible.

**Comment by thegame615** [comment]
> Hello, the in main branch does not cause text disappear, it happens when trying to click "Submit Grade Inquiry". For instance, if you have two questions, and you firstly type in both question 1 and question 2. Then, submit only question 1 grade inquiry. The text in question 2 grade inquiry will disappear. Hope it helps. If you still unsure about this issue, I can record a video about this current bug. For the README. changes, I accidentally commit it, I will revert all these changes as soon as possible.

If you wouldn't mind, I would like to see a video of the actual bug. I haven't been able to reproduce it yet.

**Comment by hanyunguo** [comment]
I've included captions in the video to help explain.

The bug in the most recent main branch version:

https://github.com/Submitty/Submitty/assets/77653905/f712ac56-ed1d-4e62-b815-a869e17f8d08

The version with the bug fixed (PR version):

https://github.com/Submitty/Submitty/assets/77653905/eb6b7c25-120b-430c-918e-526f23616c2c


Also, here's how to produce an assignment with the 'Submit Grade Inquiry' button: 

https://github.com/Submitty/Submitty/assets/77653905/64c057cf-26d8-4cd4-be61-a8ac581a7e6a

**Comment by thegame615** [comment]
> I've included captions in the video to help explain.
> 
> The bug in the most recent main branch version:
> copy_A57B16D3-EF29-4006-89B2-5CAA09C2CF1D.mov
> 
> The version with the bug fixed (PR version):
> New_compressed.mp4
> 
> Also, here's how to produce an assignment with the 'Submit Grade Inquiry' button:
> reproduce_compress.MOV

Thanks for the video.
It's weird, since that is what I tested for and there didn't seem to be a problem on my machine. I'll ask someone else to review it in my stead.

**Review by wuj18 — DISMISSED** [review]
Hello, I've managed to refactor the issue, and the PR does fix the issue. However, I believe it would be better to remove the console logs.

**Comment by hanyunguo** [comment]
Hello,

Thank you for taking the time to review the changes. I've made several improvements:

1. Removed unnecessary console logs to ensure cleaner code.
2. Refactored the code by relocating the function implementation from the <script> section of the Discussion.twig file to the grade-inquiry.js file.
3. Fixed any failed code style check testcases to ensure the code meets quality standards.

Please review the updated code and let me know if there are any further adjustments needed.

File: site/public/js/grade-inquiry.js [hunk 1]
```diff
@@ -1,6 +1,25 @@
...
+function saveDraft() { 
+    //display the saved draft text on grade inquiry box
+    var draftContent = localStorage.getItem('content');
+    if(draftContent === null) {
+        draftContent = {};
+    }else{
+        draftContent = JSON.parse(draftContent);
+    }
+    var elements = document.getElementsByClassName('markdown-textarea fill-available ');
+    for (var i = 0; i < elements.length; i++) {
```
Comment (04vmatsibekker) [inline site/public/js/grade-inquiry.js:13]: instead of using the variable var, please use let or const instead

File: site/public/js/grade-inquiry.js [hunk 2]
```diff
@@ -1,6 +1,25 @@
...
+        var element = elements[i];
+        var elementId = element.getAttribute('id');
+        const reply_text_area = $(element);
+        if(draftContent.hasOwnProperty(elementId)){
```
Comment (04vmatsibekker) [inline site/public/js/grade-inquiry.js:17]: fix formatting here

**Review by 04vmatsibekker — DISMISSED** [review]

File: site/public/js/grade-inquiry.js (hunk 2 above)
Comment (hanyunguo) [reply site/public/js/grade-inquiry.js:17]: Thank you for the feedback. I have fixed the formatting.

File: site/public/js/grade-inquiry.js (hunk 1 above)
Comment (hanyunguo) [reply site/public/js/grade-inquiry.js]: Hello,

I have made some coding style changes to the code. Would you mind taking a moment to review it when you have a chance? Thank you

File: site/public/js/grade-inquiry.js [hunk 3]
```diff
@@ -1,6 +1,27 @@
 /* global buildCourseUrl, WebSocketClient */
 /* exported initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
```
Comment (powe97) [inline site/public/js/grade-inquiry.js:2]:
```suggestion
/* exported saveDraft, initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
```
To fix JS-lint, add `saveDraft` to the exported list.

File: site/public/js/grade-inquiry.js [hunk 4]
```diff
@@ -1,6 +1,27 @@
...
 
+function saveDraft() {
```
Comment (powe97) [inline site/public/js/grade-inquiry.js:4]:
```suggestion
function saveDraft() {
```
Remove the trailing space here.

File: site/public/js/grade-inquiry.js [hunk 5]
```diff
@@ -1,6 +1,27 @@
...
+    }
+    else {
+        draftContent = JSON.parse(draftContent);
+    }
+    const elements = document.getElementsByClassName('markdown-textarea fill-available ');
+    for (let i = 0; i < elements.length; i++) {
+        const element = elements[i];
+        const elementId = element.getAttribute('id');
+        const reply_text_area = $(element);
+        if (draftContent.hasOwnProperty(elementId)){
```
Comment (powe97) [inline site/public/js/grade-inquiry.js:18]:
```suggestion
        if (Object.prototype.hasOwnProperty.call(draftContent, elementId)) {
```
Change this to use `Object.prototype.hasOwnProperty.call`, because for whatever reason that is what the linter wants.

File: site/public/js/grade-inquiry.js [hunk 6]
```diff
@@ -1,6 +1,27 @@
...
+            var value = draftContent[elementId];
+            reply_text_area.val(value);
```
Comment (powe97) [inline site/public/js/grade-inquiry.js:20]:
```suggestion
            reply_text_area.val(draftContent[elementId]);
```
No need for a variable here. Also, use `const` or `let`, never `var`.

File: site/public/js/grade-inquiry.js [hunk 7]
```diff
@@ -50,12 +70,25 @@ function onComponentTabClicked(tab) {
...
     must_be_empty_buttons.prop('disabled', reply_text_area.val() !== '');
 
+    const component_selected = $('.btn-selected');
+    const component_id = component_selected.length ? component_selected.data('component_id') : 0;
+    localStorage.setItem('selected_tab', `.component-${component_id}`);
+    let draftContent = localStorage.getItem('content');
+    if (draftContent === null) {
+        draftContent = {};
+    } else {
+        draftContent = JSON.parse(draftContent);}
```
Comment (powe97) [inline site/public/js/grade-inquiry.js:87]:
```suggestion
    }
    else {
        draftContent = JSON.parse(draftContent);
    }
```

**Review by powe97 — CHANGES_REQUESTED** [review]
Code looks fine, just need to fix linting issues. I have given suggested changes that should work for fixing this.

**Review by powe97 — APPROVED** [review]

File: site/public/js/grade-inquiry.js [hunk 8]
```diff
@@ -30,7 +50,6 @@ function onReady() {
 
 function onComponentTabClicked(tab) {
     const component_id = $(tab).data('component_id');
-
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:33]: This whitespace change should be reverted

File: site/public/js/grade-inquiry.js [hunk 9]
```diff
@@ -112,7 +146,6 @@ function onGradeInquirySubmitClicked(button) {
                 const json = JSON.parse(response);
                 if (json['status'] === 'success') {
                     const data = json['data'];
-
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:115]: Same here

File: site/public/js/grade-inquiry.js [hunk 10]
```diff
@@ -1,5 +1,25 @@
 /* global buildCourseUrl, WebSocketClient */
-/* exported initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
+/* exported saveDraft, initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
+
+function saveDraft() {
+    //saveDraft function displays the saved draft text on grade inquiry box
+    let draftContent = localStorage.getItem('content');
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:6]: `content` isn't a very descriptive key.  Additionally, won't it conflict with other drafts?

File: site/app/templates/submission/grade_inquiry/Discussion.twig [hunk 11]
```diff
@@ -125,6 +125,9 @@
     </div>
 
     <script>
+        window.onload = function() {
+            saveDraft();
+        };
```
Comment (williamjallen) [inline site/app/templates/submission/grade_inquiry/Discussion.twig:130]: Shouldn't this load the draft instead of saving it?

File: site/public/js/grade-inquiry.js [hunk 12]
```diff
@@ -1,5 +1,25 @@
...
+    if (draftContent === null) {
+        draftContent = {};
+    }
+    else {
+        draftContent = JSON.parse(draftContent);
+    }
+    const elements = document.getElementsByClassName('markdown-textarea fill-available ');
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:13]: It would be better to identify elements via a more specific identifier, such as by ID, or by class.  Additionally, it would be better to use jQuery for this.

File: site/public/js/grade-inquiry.js [hunk 13]
```diff
@@ -1,5 +1,25 @@
...
+    for (let i = 0; i < elements.length; i++) {
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:14]: You can use [`.forEach()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) for this instead.

**Review by williamjallen — CHANGES_REQUESTED** [review]

File: site/public/js/grade-inquiry.js (hunk 8 above)
Comment (hanyunguo) [reply site/public/js/grade-inquiry.js:33]: Hi William, I removed the whitespace

File: site/public/js/grade-inquiry.js (hunk 10 above)
Comment (hanyunguo) [reply site/public/js/grade-inquiry.js]: Hi William, I renamed the "content" to "draftContent".

File: site/app/templates/submission/grade_inquiry/Discussion.twig (hunk 11 above)
Comment (hanyunguo) [reply site/app/templates/submission/grade_inquiry/Discussion.twig:130]: Hi William, I changed the function name "saveDraft" to "loadDraft"

File: site/public/js/grade-inquiry.js (hunk 8 above)
Comment (williamjallen) [reply site/public/js/grade-inquiry.js:33]: It looks like a line is still being deleted here

**Review by williamjallen — COMMENTED** [review]
It looks like this PR is still waiting for some stylistic issues to be addressed.

From the reviewing side, we also need someone to do a functionality review once the stylistic changes are complete.

File: site/public/js/grade-inquiry.js (hunk 12 above)
Comment (ZheyuDeng) [reply site/public/js/grade-inquiry.js:13]: image
It doesn't seem to have a more specific identifier we can use, I have also switched into jquery.

File: site/app/templates/submission/grade_inquiry/Discussion.twig [hunk 14]
```diff
@@ -125,6 +125,9 @@
     </div>
 
     <script>
+        window.onload = function() {
+            loadDraft();
+        };
```
Comment (williamjallen) [inline site/app/templates/submission/grade_inquiry/Discussion.twig:130]: Can this be moved to an external JS file?  Also, it would be better to use jQuery for this: `$(document).ready(() => {...`

File: site/public/js/grade-inquiry.js [hunk 15]
```diff
@@ -1,5 +1,23 @@
 /* global buildCourseUrl, WebSocketClient */
-/* exported initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
+/* exported loadDraft, initGradingInquirySocketClient, onComponentTabClicked, onGradeInquirySubmitClicked, onReady, onReplyTextAreaKeyUp */
+
+function loadDraft() {
+    // LoadDraft function displays the saved draft text on grade inquiry box
+    let draftContent = localStorage.getItem('draftContent');
```
Comment (williamjallen) [inline site/public/js/grade-inquiry.js:6]: This key isn't very unique.  Won't grade inquiries on different gradeables conflict with each other?

**Review by williamjallen — CHANGES_REQUESTED** [review]
Can you also write a basic Cypress test for this feature?  Small features like this are prone to breaking in non-obvious ways.

**Review by zacharymnp — APPROVED** [review]
works as intended

**Review by williamjallen — APPROVED** [review]
Code seems reasonable to me.
